package com.hand.hqm.hqm_online_sku_rule_his.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_ONLINE_SKU_RULE_HIS")
public class OnlineSkuRuleHis extends BaseDTO {

	@Id
	@GeneratedValue
	private Float eventId;

	private Long eventBy;

	private Date eventTime;

	private Float kid;

	private Float plantId;

	@Length(max = 5)
	private String skuType;

	private Float inspectQty;

	private Float passPercent;

	@Length(max = 5)
	private String enableFlag;

	public void setEventId(Float eventId) {
		this.eventId = eventId;
	}

	public Float getEventId() {
		return eventId;
	}

	public void setEventBy(Long eventBy) {
		this.eventBy = eventBy;
	}

	public Long getEventBy() {
		return eventBy;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	public Date getEventTime() {
		return eventTime;
	}

	public void setKid(Float kid) {
		this.kid = kid;
	}

	public Float getKid() {
		return kid;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setSkuType(String skuType) {
		this.skuType = skuType;
	}

	public String getSkuType() {
		return skuType;
	}

	public void setInspectQty(Float inspectQty) {
		this.inspectQty = inspectQty;
	}

	public Float getInspectQty() {
		return inspectQty;
	}

	public void setPassPercent(Float passPercent) {
		this.passPercent = passPercent;
	}

	public Float getPassPercent() {
		return passPercent;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

}
