package com.hand.hqm.hqm_inspection_attribute.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = false)
@Table(name = "HQM_INSPECTION_ATTRIBUTE")
public class InspectionAttribute extends BaseDTO {


	@Id
	@GeneratedValue
	private Float attributeId;
	
	@Transient
	private String attributeTypeMeaning;

	private Float precision;

	private String inspectionMethod;

	@Length(max = 30)
	private String attributeType;

	@Length(max = 30)
	private String sampleProcedureType;

	private String inspectionAttribute;

	@Length(max = 30)
	private String inspectionLevels;

	@Length(max = 30)
	private String qualityCharacterGrade;

	@Length(max = 30)
	private String acceptanceQualityLimit;

	@Length(max = 30)
	private String sourceType;

	@Length(max = 30)
	private String standardType;

	@Length(max = 30)
	private String fillInType;

	@Length(max = 30)
	private String frequencyType;

	private Float frequency;


	private String inspectionTool;

	@Length(max = 1)
	private String enableFlag;

	@Length(max = 200)
	private String remark;

	public Float getPrecision() {
		return precision;
	}

	public void setPrecision(Float precision) {
		this.precision = precision;
	}

	public String getInspectionMethod() {
		return inspectionMethod;
	}

	public void setInspectionMethod(String inspectionMethod) {
		this.inspectionMethod = inspectionMethod;
	}

	public String getAttributeTypeMeaning() {
		return attributeTypeMeaning;
	}

	public void setAttributeTypeMeaning(String attributeTypeMeaning) {
		this.attributeTypeMeaning = attributeTypeMeaning;
	}

	public Float getAttributeId() {
		return attributeId;
	}

	public void setAttributeId(Float attributeId) {
		this.attributeId = attributeId;
	}

	public String getAttributeType() {
		return attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	public void setSampleProcedureType(String sampleProcedureType) {
		this.sampleProcedureType = sampleProcedureType;
	}

	public String getSampleProcedureType() {
		return sampleProcedureType;
	}

	public void setInspectionAttribute(String inspectionAttribute) {
		this.inspectionAttribute = inspectionAttribute;
	}

	public String getInspectionAttribute() {
		return inspectionAttribute;
	}

	public void setInspectionLevels(String inspectionLevels) {
		this.inspectionLevels = inspectionLevels;
	}

	public String getInspectionLevels() {
		return inspectionLevels;
	}

	public void setQualityCharacterGrade(String qualityCharacterGrade) {
		this.qualityCharacterGrade = qualityCharacterGrade;
	}

	public String getQualityCharacterGrade() {
		return qualityCharacterGrade;
	}

	public void setAcceptanceQualityLimit(String acceptanceQualityLimit) {
		this.acceptanceQualityLimit = acceptanceQualityLimit;
	}

	public String getAcceptanceQualityLimit() {
		return acceptanceQualityLimit;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	public String getSourceType() {
		return sourceType;
	}

	public void setStandardType(String standardType) {
		this.standardType = standardType;
	}

	public String getStandardType() {
		return standardType;
	}

	public void setFillInType(String fillInType) {
		this.fillInType = fillInType;
	}

	public String getFillInType() {
		return fillInType;
	}

	public void setFrequencyType(String frequencyType) {
		this.frequencyType = frequencyType;
	}

	public String getFrequencyType() {
		return frequencyType;
	}

	public void setFrequency(Float frequency) {
		this.frequency = frequency;
	}

	public Float getFrequency() {
		return frequency;
	}

	public void setInspectionTool(String inspectionTool) {
		this.inspectionTool = inspectionTool;
	}

	public String getInspectionTool() {
		return inspectionTool;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRemark() {
		return remark;
	}

}
