package com.hand.hqm.hqm_fqc_inspection_template_h.dto;

import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_FQC_INSPECTION_TEMPLATE_H")
public class FqcInspectionTemplateH extends BaseDTO {

     @Id
     @GeneratedValue
     private Float headerId;

     private Float plantId;

     private Float itemId;

     @Length(max = 30)
     private String itemCategory;

     @Length(max = 30)
     private String versionNum;

     @Length(max = 30)
     private String drawingNumber;

     @Length(max = 1)
     private String enableFlag;

     private Float historyNum;

     @Length(max = 30)
     private String status;

     @Length(max = 150)
     private String globalAttribute1;

     @Length(max = 150)
     private String globalAttribute2;

     @Length(max = 150)
     private String globalAttribute3;

     @Length(max = 150)
     private String globalAttribute4;

     @Length(max = 150)
     private String globalAttribute5;

     @Length(max = 150)
     private String globalAttribute6;

     @Length(max = 150)
     private String globalAttribute7;

     @Length(max = 150)
     private String globalAttribute8;

     @Length(max = 150)
     private String globalAttribute9;

     @Length(max = 150)
     private String globalAttribute10;

     @Length(max = 150)
     private String globalAttribute11;

     @Length(max = 150)
     private String globalAttribute12;

     @Length(max = 150)
     private String globalAttribute13;

     @Length(max = 150)
     private String globalAttribute14;

     @Length(max = 150)
     private String globalAttribute15;

     @Length(max = 30)
     private String sourceType;
     @Transient
 	private String itemCode;

 	@Transient
 	private String itemDescriptions;
 	@Transient
 	private String plantCode;
 	@Transient
 	private Date columnCreationDate;
 	@Transient
 	private String itemCategoryCode;
     public String getItemCategoryCode() {
		return itemCategoryCode;
	}

	public void setItemCategoryCode(String itemCategoryCode) {
		this.itemCategoryCode = itemCategoryCode;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemDescriptions() {
		return itemDescriptions;
	}

	public void setItemDescriptions(String itemDescriptions) {
		this.itemDescriptions = itemDescriptions;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public Date getColumnCreationDate() {
		return columnCreationDate;
	}

	public void setColumnCreationDate(Date columnCreationDate) {
		this.columnCreationDate = columnCreationDate;
	}

	public void setHeaderId(Float headerId){
         this.headerId = headerId;
     }

     public Float getHeaderId(){
         return headerId;
     }

     public void setPlantId(Float plantId){
         this.plantId = plantId;
     }

     public Float getPlantId(){
         return plantId;
     }

     public void setItemId(Float itemId){
         this.itemId = itemId;
     }

     public Float getItemId(){
         return itemId;
     }

     public void setItemCategory(String itemCategory){
         this.itemCategory = itemCategory;
     }

     public String getItemCategory(){
         return itemCategory;
     }

     public void setVersionNum(String versionNum){
         this.versionNum = versionNum;
     }

     public String getVersionNum(){
         return versionNum;
     }

     public void setDrawingNumber(String drawingNumber){
         this.drawingNumber = drawingNumber;
     }

     public String getDrawingNumber(){
         return drawingNumber;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setHistoryNum(Float historyNum){
         this.historyNum = historyNum;
     }

     public Float getHistoryNum(){
         return historyNum;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setGlobalAttribute1(String globalAttribute1){
         this.globalAttribute1 = globalAttribute1;
     }

     public String getGlobalAttribute1(){
         return globalAttribute1;
     }

     public void setGlobalAttribute2(String globalAttribute2){
         this.globalAttribute2 = globalAttribute2;
     }

     public String getGlobalAttribute2(){
         return globalAttribute2;
     }

     public void setGlobalAttribute3(String globalAttribute3){
         this.globalAttribute3 = globalAttribute3;
     }

     public String getGlobalAttribute3(){
         return globalAttribute3;
     }

     public void setGlobalAttribute4(String globalAttribute4){
         this.globalAttribute4 = globalAttribute4;
     }

     public String getGlobalAttribute4(){
         return globalAttribute4;
     }

     public void setGlobalAttribute5(String globalAttribute5){
         this.globalAttribute5 = globalAttribute5;
     }

     public String getGlobalAttribute5(){
         return globalAttribute5;
     }

     public void setGlobalAttribute6(String globalAttribute6){
         this.globalAttribute6 = globalAttribute6;
     }

     public String getGlobalAttribute6(){
         return globalAttribute6;
     }

     public void setGlobalAttribute7(String globalAttribute7){
         this.globalAttribute7 = globalAttribute7;
     }

     public String getGlobalAttribute7(){
         return globalAttribute7;
     }

     public void setGlobalAttribute8(String globalAttribute8){
         this.globalAttribute8 = globalAttribute8;
     }

     public String getGlobalAttribute8(){
         return globalAttribute8;
     }

     public void setGlobalAttribute9(String globalAttribute9){
         this.globalAttribute9 = globalAttribute9;
     }

     public String getGlobalAttribute9(){
         return globalAttribute9;
     }

     public void setGlobalAttribute10(String globalAttribute10){
         this.globalAttribute10 = globalAttribute10;
     }

     public String getGlobalAttribute10(){
         return globalAttribute10;
     }

     public void setGlobalAttribute11(String globalAttribute11){
         this.globalAttribute11 = globalAttribute11;
     }

     public String getGlobalAttribute11(){
         return globalAttribute11;
     }

     public void setGlobalAttribute12(String globalAttribute12){
         this.globalAttribute12 = globalAttribute12;
     }

     public String getGlobalAttribute12(){
         return globalAttribute12;
     }

     public void setGlobalAttribute13(String globalAttribute13){
         this.globalAttribute13 = globalAttribute13;
     }

     public String getGlobalAttribute13(){
         return globalAttribute13;
     }

     public void setGlobalAttribute14(String globalAttribute14){
         this.globalAttribute14 = globalAttribute14;
     }

     public String getGlobalAttribute14(){
         return globalAttribute14;
     }

     public void setGlobalAttribute15(String globalAttribute15){
         this.globalAttribute15 = globalAttribute15;
     }

     public String getGlobalAttribute15(){
         return globalAttribute15;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     }
