package com.hand.plm.plm_product_basic_data.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "PLM_PRODUCT_BASIC_DATA")
public class ProductBasicData extends BaseDTO {

     public static final String FIELD_PRODUCT_ID = "productId";
     public static final String FIELD_PRODUCT_NAME = "productName";
     public static final String FIELD_PRODUCT_DESCRIPTION = "productDescription";


     @Id
     @GeneratedValue
     private String productId;

     @Length(max = 100)
     private String productName;

     @Length(max = 300)
     private String productDescription;


     public void setProductId(String productId){
         this.productId = productId;
     }

     public String getProductId(){
         return productId;
     }

     public void setProductName(String productName){
         this.productName = productName;
     }

     public String getProductName(){
         return productName;
     }

     public void setProductDescription(String productDescription){
         this.productDescription = productDescription;
     }

     public String getProductDescription(){
         return productDescription;
     }

     }
