package com.hand.hqm.file_manager_his.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "FILE_MANAGER_HIS")
public class ManagerHis extends BaseDTO {

     public static final String FIELD_FILE_ID = "fileId";
     public static final String FIELD_FILE_NUM = "fileNum";
     public static final String FIELD_FILE_TITLE = "fileTitle";
     public static final String FIELD_EDITION = "edition";
     public static final String FIELD_FILE_CLASSIFY = "fileClassify";
     public static final String FIELD_UPLOAD_DATE = "uploadDate";
     public static final String FIELD_ENABLE_FLAG = "enableFlag";
     public static final String FIELD_IP = "ip";
     public static final String FIELD_MENU_PATH = "menuPath";


     @Id
     @GeneratedValue
     private Float fileHisId;
     
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date expirationDate;
     
     public Date getExpirationDate() {
		return expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public Float getFileHisId() {
		return fileHisId;
	}

	public void setFileHisId(Float fileHisId) {
		this.fileHisId = fileHisId;
	}

	private Float fileId;

     @Length(max = 30)
     private String fileNum;

     @Length(max = 30)
     private String fileTitle;

     @Length(max = 30)
     private String edition;
     @Transient
     @Length(max = 30)
     private String fileClassify;

     private Date uploadDate;

     @Length(max = 15)
     private String enableFlag;

     @Length(max = 30)
     private String ip;

     @Length(max = 100)
     private String menuPath;

    private String fileUrl;
    
    @Transient
    private String classifyIds;
    @Transient
    private String remark;
     public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getClassifyIds() {
		return classifyIds;
	}

	public void setClassifyIds(String classifyIds) {
		this.classifyIds = classifyIds;
	}

	public String getFileUrl() {
		return fileUrl;
	 }

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}
     public void setFileId(Float fileId){
         this.fileId = fileId;
     }

     public Float getFileId(){
         return fileId;
     }

     public void setFileNum(String fileNum){
         this.fileNum = fileNum;
     }

     public String getFileNum(){
         return fileNum;
     }

     public void setFileTitle(String fileTitle){
         this.fileTitle = fileTitle;
     }

     public String getFileTitle(){
         return fileTitle;
     }

     public void setEdition(String edition){
         this.edition = edition;
     }

     public String getEdition(){
         return edition;
     }

     public void setFileClassify(String fileClassify){
         this.fileClassify = fileClassify;
     }

     public String getFileClassify(){
         return fileClassify;
     }

     public void setUploadDate(Date uploadDate){
         this.uploadDate = uploadDate;
     }

     public Date getUploadDate(){
         return uploadDate;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setIp(String ip){
         this.ip = ip;
     }

     public String getIp(){
         return ip;
     }

     public void setMenuPath(String menuPath){
         this.menuPath = menuPath;
     }

     public String getMenuPath(){
         return menuPath;
     }

     }
