package com.hand.hqm.hqm_inspection_group_l.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import org.apache.xpath.operations.Bool;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_INSPECTION_GROUP_L")
public class InspectionGroupL extends BaseDTO {

     
     @Id
     @GeneratedValue
     private Float lineId;
   
     private Float attributeId ;
      
     private Float groupId;

     private Float precision;

     private String standradFrom;

     private String standradTo;

     @Length(max = 30)
     private String standradUom;

     @Length(max = 200)
     private String textStandrad;


     private String inspectionTool;

     @Length(max = 100)
     private String inspectionMethod;

     @Length(max = 30)
     private String fillInType;

     private Float sampleWayId;

     @Length(max = 30)
     private String enableType;

     private Date enableTime;

     private Date disableTime;

     @Length(max = 1)
     private String enableFlag;

     @Length(max = 200)
     private String remark;
     
     @Transient
     @Length(max = 100)
     private String groupCode;
     
     @Transient
     @Length(max = 100)
     private String description;
     
     @Transient
     private Float plantId;
     
     @Transient
     @Length(max = 1)
     private String headEnableFlag;
     
     @Transient
     @Length(max = 200)
     private String inspectionAttribute;
     
     @Transient
     @Length(max = 200)
     private String attributeType;
     
     @Transient
     @Length(max = 200)
     private String sampleWayCode;
     
     
     public String getSampleWayCode() {
		return sampleWayCode;
	}

	public void setSampleWayCode(String sampleWayCode) {
		this.sampleWayCode = sampleWayCode;
	}

	@Transient
     @Length(max = 200)
     private String qualityCharacterGrade;
	
	@Transient
    @Length(max = 200)
    private String ids;


	@Transient
    private boolean flagCopy;
	 
     public void setFlagCopy(boolean flagCopy) {
		this.flagCopy = flagCopy;
	}

 	public boolean getFlagCopy() {
		return flagCopy;
	}
	public String getIds() {
		return ids;
	}

	public void setIds(String ids) {
		this.ids = ids;
	}

	@Transient
     @Length(max = 200)
     private String plantCode;
     
     
     @Transient
     @Length(max = 200)
     private String standardType;
     
     public Float getAttributeId() {
		return attributeId;
	}

	public void setAttributeId(Float attributeId) {
		this.attributeId = attributeId;
	}

	public String getInspectionAttribute() {
		return inspectionAttribute;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public void setInspectionAttribute(String inspectionAttribute) {
		this.inspectionAttribute = inspectionAttribute;
	}

	public String getAttributeType() {
		return attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	public String getQualityCharacterGrade() {
		return qualityCharacterGrade;
	}

	public void setQualityCharacterGrade(String qualityCharacterGrade) {
		this.qualityCharacterGrade = qualityCharacterGrade;
	}

	public String getStandardType() {
		return standardType;
	}

	public void setStandardType(String standardType) {
		this.standardType = standardType;
	}

	@Transient
     @Length(max = 200)
     private String headRemark;
       
     public String getGroupCode() {
		return groupCode;
	}

	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public String getHeadEnableFlag() {
		return headEnableFlag;
	}

	public void setHeadEnableFlag(String headEnableFlag) {
		this.headEnableFlag = headEnableFlag;
	}

	public String getHeadRemark() {
		return headRemark;
	}

	public void setHeadRemark(String headRemark) {
		this.headRemark = headRemark;
	}

	
     
     public void setLineId(Float lineId){
         this.lineId = lineId;
     }

     public Float getLineId(){
         return lineId;
     }

     public void setGroupId(Float groupId){
         this.groupId = groupId;
     }

     public Float getGroupId(){
         return groupId;
     }

     public void setPrecision(Float precision){
         this.precision = precision;
     }

     public Float getPrecision(){
         return precision;
     }

     public void setStandradFrom(String standradFrom){
         this.standradFrom = standradFrom;
     }

     public String getStandradFrom(){
         return standradFrom;
     }

     public void setStandradTo(String standradTo){
         this.standradTo = standradTo;
     }

     public String getStandradTo(){
         return standradTo;
     }

     public void setStandradUom(String standradUom){
         this.standradUom = standradUom;
     }

     public String getStandradUom(){
         return standradUom;
     }

     public void setTextStandrad(String textStandrad){
         this.textStandrad = textStandrad;
     }

     public String getTextStandrad(){
         return textStandrad;
     }

     public void setInspectionTool(String inspectionTool){
         this.inspectionTool = inspectionTool;
     }

     public String getInspectionTool(){
         return inspectionTool;
     }

     public void setInspectionMethod(String inspectionMethod){
         this.inspectionMethod = inspectionMethod;
     }

     public String getInspectionMethod(){
         return inspectionMethod;
     }

     public void setFillInType(String fillInType){
         this.fillInType = fillInType;
     }

     public String getFillInType(){
         return fillInType;
     }

     public void setSampleWayId(Float sampleWayId){
         this.sampleWayId = sampleWayId;
     }

     public Float getSampleWayId(){
         return sampleWayId;
     }

     public void setEnableType(String enableType){
         this.enableType = enableType;
     }

     public String getEnableType(){
         return enableType;
     }

     public void setEnableTime(Date enableTime){
         this.enableTime = enableTime;
     }

     public Date getEnableTime(){
         return enableTime;
     }

     public void setDisableTime(Date disableTime){
         this.disableTime = disableTime;
     }

     public Date getDisableTime(){
         return disableTime;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     }
