package com.hand.hqm.hqm_sam_use_order_h.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_SAM_USE_ORDER_H")
public class SamUseOrderH extends BaseDTO {

     public static final String FIELD_USE_ORDER_NUMBER = "useOrderNumber";
     public static final String FIELD_KID = "kid";
     public static final String FIELD_USE_ORDER_STATUS = "useOrderStatus";
     public static final String FIELD_USE_DEPARTMENT = "useDepartment";
     public static final String FIELD_USE_REASON = "useReason";
     public static final String FIELD_PLANT_ID = "plantId";
     public static final String FIELD_APPLICANT = "applicant";
     public static final String FIELD_APPLICATION_DATE = "applicationDate";
     public static final String FIELD_APPROVER = "approver";
     public static final String FIELD_APPROVAL_DATE = "approvalDate";
     public static final String FIELD_REMARK = "remark";
     public static final String FIELD_PRINT_FLAG = "printFlag";


     @Length(max = 50)
     private String useOrderNumber;

     @Id
     @GeneratedValue
     private Float kid;

     @Length(max = 5)
     private String useOrderStatus;

     @Length(max = 20)
     private String useDepartment;

     @Length(max = 300)
     private String useReason;

     private Float plantId;

     private Float applicant;

     private Date applicationDate;

     private Float approver;

     private Date approvalDate;

     @Length(max = 100)
     private String remark;

     @Length(max = 1)
     private String printFlag;

     @Transient
     private String plantCode;
     
     @Transient
     private String approverUserName;
     
     @Transient
     private String approvalDateStartTime;
     
     @Transient
     private String approvalDateEndTime;
     
     @Transient
     private String applicationDateStartTime;
     
     @Transient
     private String applicationDateEndTime;
     
     @Transient
     private String applicantUserName;
     
     
     
     public String getApprovalDateStartTime() {
		return approvalDateStartTime;
	}

	public void setApprovalDateStartTime(String approvalDateStartTime) {
		this.approvalDateStartTime = approvalDateStartTime;
	}

	public String getApprovalDateEndTime() {
		return approvalDateEndTime;
	}

	public void setApprovalDateEndTime(String approvalDateEndTime) {
		this.approvalDateEndTime = approvalDateEndTime;
	}

	public String getApplicationDateStartTime() {
		return applicationDateStartTime;
	}

	public void setApplicationDateStartTime(String applicationDateStartTime) {
		this.applicationDateStartTime = applicationDateStartTime;
	}

	public String getApplicationDateEndTime() {
		return applicationDateEndTime;
	}

	public void setApplicationDateEndTime(String applicationDateEndTime) {
		this.applicationDateEndTime = applicationDateEndTime;
	}

	
     
     public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getApplicantUserName() {
		return applicantUserName;
	}

	public void setApplicantUserName(String applicantUserName) {
		this.applicantUserName = applicantUserName;
	}

	public String getApproverUserName() {
		return approverUserName;
	}

	public void setApproverUserName(String approverUserName) {
		this.approverUserName = approverUserName;
	}

	
     public void setUseOrderNumber(String useOrderNumber){
         this.useOrderNumber = useOrderNumber;
     }

     public String getUseOrderNumber(){
         return useOrderNumber;
     }

     public void setKid(Float kid){
         this.kid = kid;
     }

     public Float getKid(){
         return kid;
     }

     public void setUseOrderStatus(String useOrderStatus){
         this.useOrderStatus = useOrderStatus;
     }

     public String getUseOrderStatus(){
         return useOrderStatus;
     }

     public void setUseDepartment(String useDepartment){
         this.useDepartment = useDepartment;
     }

     public String getUseDepartment(){
         return useDepartment;
     }

     public void setUseReason(String useReason){
         this.useReason = useReason;
     }

     public String getUseReason(){
         return useReason;
     }

     public void setPlantId(Float plantId){
         this.plantId = plantId;
     }

     public Float getPlantId(){
         return plantId;
     }

     public void setApplicant(Float applicant){
         this.applicant = applicant;
     }

     public Float getApplicant(){
         return applicant;
     }

     public void setApplicationDate(Date applicationDate){
         this.applicationDate = applicationDate;
     }

     public Date getApplicationDate(){
         return applicationDate;
     }

     public void setApprover(Float approver){
         this.approver = approver;
     }

     public Float getApprover(){
         return approver;
     }

     public void setApprovalDate(Date approvalDate){
         this.approvalDate = approvalDate;
     }

     public Date getApprovalDate(){
         return approvalDate;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setPrintFlag(String printFlag){
         this.printFlag = printFlag;
     }

     public String getPrintFlag(){
         return printFlag;
     }

     }
