package com.hand.hqm.hqm_sample.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_SAMPLE")
public class Sample extends BaseDTO {

     public static final String FIELD_SAMPLE_ID = "sampleId";
     public static final String FIELD_SAMPLE_NUMBER = "sampleNumber";
     public static final String FIELD_SAMPLE_TYPE = "sampleType";
     public static final String FIELD_SAMPLE_POSITION_STATUS = "samplePositionStatus";
     public static final String FIELD_SAMPLE_STATUS = "sampleStatus";
     public static final String FIELD_DESCRIPTION = "description";
     public static final String FIELD_SAMPLE_PROPERTIES = "sampleProperties";
     public static final String FIELD_SAMPLE_GIVER = "sampleGiver";
     public static final String FIELD_SAMPLE_GIVE_DATE = "sampleGiveDate";
     public static final String FIELD_SAMPLE_USER = "sampleUser";
     public static final String FIELD_SAMPLE_USE_DATE = "sampleUseDate";
     public static final String FIELD_SAMPLE_USE_DEPARTMENT = "sampleUseDepartment";
     public static final String FIELD_SAMPLE_DISPOSAL_METHOD = "sampleDisposalMethod";
     public static final String FIELD_SAMPLE_DISPOSAL_DATE = "sampleDisposalDate";
     public static final String FIELD_ASSOCIATED_DOCUMENT = "associatedDocument";
     public static final String FIELD_ENABLE_FLAG = "enableFlag";
     public static final String FIELD_PLANT_ID = "plantId";
     
     

     @Id
     @GeneratedValue
     private Float sampleId;

     @Length(max = 50)
     private String sampleNumber;

     @Length(max = 50)
     private String sampleType;

     @Length(max = 5)
     private String samplePositionStatus;

     @Length(max = 5)
     private String sampleStatus;

     @Length(max = 50)
     private String description;

     @Length(max = 50)
     private String sampleProperties;

     private Float sampleGiver;
     
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     private Date sampleGiveDate;

     private Float sampleUser;

     private Date sampleUseDate;

     @Length(max = 5)
     private String sampleUseDepartment;

     @Length(max = 5)
     private String sampleDisposalMethod;

     private Date sampleDisposalDate;

     @Length(max = 50)
     private String associatedDocument;

     @Length(max = 5)
     private String enableFlag;
     @Transient 
     private Float num;
    
    
	private Float plantId;
     
     @Transient 
     private String sampleUserUserName;
     
     @Transient    
     private String plantCode;
     
     @Transient 
     private String sampleGiverUserName;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     @Transient
     private Date sampleGiveDateStartTime;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     @Transient
     private Date sampleGiveDateEndTime;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     @Transient
     private Date sampleUseDateStartTime;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     @Transient
     private Date sampleUseDateEndTime;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     @Transient
     private Date sampleDisposalDateStartTime;
     @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
     @Transient
     private Date sampleDisposalDateEndTime;
     
     
     public Float getNum() {
 		return num;
 	}

 	public void setNum(Float num) {
 		this.num = num;
 	}

     public Date getSampleGiveDateStartTime() {
		return sampleGiveDateStartTime;
	}

	public void setSampleGiveDateStartTime(Date sampleGiveDateStartTime) {
		this.sampleGiveDateStartTime = sampleGiveDateStartTime;
	}

	public Date getSampleGiveDateEndTime() {
		return sampleGiveDateEndTime;
	}

	public void setSampleGiveDateEndTime(Date sampleGiveDateEndTime) {
		this.sampleGiveDateEndTime = sampleGiveDateEndTime;
	}

	public Date getSampleUseDateStartTime() {
		return sampleUseDateStartTime;
	}

	public void setSampleUseDateStartTime(Date sampleUseDateStartTime) {
		this.sampleUseDateStartTime = sampleUseDateStartTime;
	}

	public Date getSampleUseDateEndTime() {
		return sampleUseDateEndTime;
	}

	public void setSampleUseDateEndTime(Date sampleUseDateEndTime) {
		this.sampleUseDateEndTime = sampleUseDateEndTime;
	}

	public Date getSampleDisposalDateStartTime() {
		return sampleDisposalDateStartTime;
	}

	public void setSampleDisposalDateStartTime(Date sampleDisposalDateStartTime) {
		this.sampleDisposalDateStartTime = sampleDisposalDateStartTime;
	}

	public Date getSampleDisposalDateEndTime() {
		return sampleDisposalDateEndTime;
	}

	public void setSampleDisposalDateEndTime(Date sampleDisposalDateEndTime) {
		this.sampleDisposalDateEndTime = sampleDisposalDateEndTime;
	}

	

     public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getSampleGiverUserName() {
		return sampleGiverUserName;
	}

	public void setSampleGiverUserName(String sampleGiverUserName) {
		this.sampleGiverUserName = sampleGiverUserName;
	}

	public String getSampleUserUserName() {
		return sampleUserUserName;
	}

	public void setSampleUserUserName(String sampleUserUserName) {
		this.sampleUserUserName = sampleUserUserName;
	}	
     
     public void setSampleId(Float sampleId){
         this.sampleId = sampleId;
     }

     public Float getSampleId(){
         return sampleId;
     }

     public void setSampleNumber(String sampleNumber){
         this.sampleNumber = sampleNumber;
     }

     public String getSampleNumber(){
         return sampleNumber;
     }

     public void setSampleType(String sampleType){
         this.sampleType = sampleType;
     }

     public String getSampleType(){
         return sampleType;
     }

     public void setSamplePositionStatus(String samplePositionStatus){
         this.samplePositionStatus = samplePositionStatus;
     }

     public String getSamplePositionStatus(){
         return samplePositionStatus;
     }

     public void setSampleStatus(String sampleStatus){
         this.sampleStatus = sampleStatus;
     }

     public String getSampleStatus(){
         return sampleStatus;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setSampleProperties(String sampleProperties){
         this.sampleProperties = sampleProperties;
     }

     public String getSampleProperties(){
         return sampleProperties;
     }

     public void setSampleGiver(Float sampleGiver){
         this.sampleGiver = sampleGiver;
     }

     public Float getSampleGiver(){
         return sampleGiver;
     }

     public void setSampleGiveDate(Date sampleGiveDate){
         this.sampleGiveDate = sampleGiveDate;
     }

     public Date getSampleGiveDate(){
         return sampleGiveDate;
     }

     public void setSampleUser(Float sampleUser){
         this.sampleUser = sampleUser;
     }

     public Float getSampleUser(){
         return sampleUser;
     }

     public void setSampleUseDate(Date sampleUseDate){
         this.sampleUseDate = sampleUseDate;
     }

     public Date getSampleUseDate(){
         return sampleUseDate;
     }

     public void setSampleUseDepartment(String sampleUseDepartment){
         this.sampleUseDepartment = sampleUseDepartment;
     }

     public String getSampleUseDepartment(){
         return sampleUseDepartment;
     }

     public void setSampleDisposalMethod(String sampleDisposalMethod){
         this.sampleDisposalMethod = sampleDisposalMethod;
     }

     public String getSampleDisposalMethod(){
         return sampleDisposalMethod;
     }

     public void setSampleDisposalDate(Date sampleDisposalDate){
         this.sampleDisposalDate = sampleDisposalDate;
     }

     public Date getSampleDisposalDate(){
         return sampleDisposalDate;
     }

     public void setAssociatedDocument(String associatedDocument){
         this.associatedDocument = associatedDocument;
     }

     public String getAssociatedDocument(){
         return associatedDocument;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setPlantId(Float plantId){
         this.plantId = plantId;
     }

     public Float getPlantId(){
         return plantId;
     }

     }
