package com.hand.hqm.hqm_asl_iqc_control.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_ASL_IQC_CONTROL")
public class AslIqcControl extends BaseDTO {

    @Id
    @GeneratedValue
    private Float controlId;

    private Float itemId;

    private Float plantId;

    private Float supplierId;

    private Float supplierSitId;

    @Length(max = 1)
    private String isInspection;

    @Length(max = 1)
    private String isSuppInspection;

    @Length(max = 1)
    private String enableFlag;

    @Length(max = 1)
    private String isupload;

    @Length(max = 1)
    private String isshipment;

    @Length(max = 1)
    private String isIqcMigrate;

    private Float batchUpLimit;

    private Float supplierExcessRatio;

    private Float deliveryRegionId;

    @Length(max = 150)
    private String globalAttribute1;

    @Length(max = 150)
    private String globalAttribute2;

    @Length(max = 150)
    private String globalAttribute3;

    @Length(max = 150)
    private String globalAttribute4;

    @Length(max = 150)
    private String globalAttribute5;

    @Length(max = 150)
    private String globalAttribute6;

    @Length(max = 150)
    private String globalAttribute7;

    @Length(max = 150)
    private String globalAttribute8;

    @Length(max = 150)
    private String globalAttribute9;

    @Length(max = 150)
    private String globalAttribute10;

    @Length(max = 150)
    private String globalAttribute11;

    @Length(max = 150)
    private String globalAttribute12;

    @Length(max = 150)
    private String globalAttribute13;

    @Length(max = 150)
    private String globalAttribute14;

    @Length(max = 150)
    private String globalAttribute15;
    @Transient
    private Float scoreId;
    @Transient
    private String itemCode;
    @Transient
    private String supplierCode;
    @Transient
    private String supplierName;
    @Transient
    private String supplierSiteCode;
    @Transient
    private String itemDescriptions;
    @Transient
    private String plantCode;
    @Transient
    @Length(max = 30)
    private String samplePlanTypeNow;
    @Transient
    @Length(max = 30)
    private String samplePlanTypeNext;
    @Transient
    private Float nonnconformingLot;
    @Transient
    private Float consecutiveConformingLot;
    @Transient
    private Float switchScore;
    @Transient
    private String changeFlag;
    
    @Transient
    private String supplierSiteDescription;
    
    public String getSupplierSiteDescription() {
		return supplierSiteDescription;
	}

	public void setSupplierSiteDescription(String supplierSiteDescription) {
		this.supplierSiteDescription = supplierSiteDescription;
	}

	public String getChangeFlag() {
		return changeFlag;
	}

	public void setChangeFlag(String changeFlag) {
		this.changeFlag = changeFlag;
	}

	public void setScoreId(Float scoreId) {
        this.scoreId = scoreId;
    }

    public Float getScoreId() {
        return scoreId;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getSupplierCode() {
        return supplierCode;
    }

    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode;
    }

    public String getSupplierName() {
        return supplierName;
    }

    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    public String getSupplierSiteCode() {
        return supplierSiteCode;
    }

    public void setSupplierSiteCode(String supplierSiteCode) {
        this.supplierSiteCode = supplierSiteCode;
    }

    public String getItemDescriptions() {
        return itemDescriptions;
    }

    public void setItemDescriptions(String itemDescriptions) {
        this.itemDescriptions = itemDescriptions;
    }

    public String getPlantCode() {
        return plantCode;
    }

    public void setPlantCode(String plantCode) {
        this.plantCode = plantCode;
    }

    public String getSamplePlanTypeNow() {
        return samplePlanTypeNow;
    }

    public void setSamplePlanTypeNow(String samplePlanTypeNow) {
        this.samplePlanTypeNow = samplePlanTypeNow;
    }

    public String getSamplePlanTypeNext() {
        return samplePlanTypeNext;
    }

    public void setSamplePlanTypeNext(String samplePlanTypeNext) {
        this.samplePlanTypeNext = samplePlanTypeNext;
    }

    public Float getNonnconformingLot() {
        return nonnconformingLot;
    }

    public void setNonnconformingLot(Float nonnconformingLot) {
        this.nonnconformingLot = nonnconformingLot;
    }

    public Float getConsecutiveConformingLot() {
        return consecutiveConformingLot;
    }

    public void setConsecutiveConformingLot(Float consecutiveConformingLot) {
        this.consecutiveConformingLot = consecutiveConformingLot;
    }

    public Float getSwitchScore() {
        return switchScore;
    }

    public void setSwitchScore(Float switchScore) {
        this.switchScore = switchScore;
    }


    public void setItemId(Float itemId) {
        this.itemId = itemId;
    }

    public Float getItemId() {
        return itemId;
    }

    public void setPlantId(Float plantId) {
        this.plantId = plantId;
    }

    public Float getPlantId() {
        return plantId;
    }

    public void setSupplierId(Float supplierId) {
        this.supplierId = supplierId;
    }

    public Float getSupplierId() {
        return supplierId;
    }

    public void setSupplierSitId(Float supplierSitId) {
        this.supplierSitId = supplierSitId;
    }

    public Float getSupplierSitId() {
        return supplierSitId;
    }

    public void setIsInspection(String isInspection) {
        this.isInspection = isInspection;
    }

    public String getIsInspection() {
        return isInspection;
    }

    public void setIsSuppInspection(String isSuppInspection) {
        this.isSuppInspection = isSuppInspection;
    }

    public String getIsSuppInspection() {
        return isSuppInspection;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

    public void setIsupload(String isupload) {
        this.isupload = isupload;
    }

    public String getIsupload() {
        return isupload;
    }

    public void setIsshipment(String isshipment) {
        this.isshipment = isshipment;
    }

    public String getIsshipment() {
        return isshipment;
    }

    public void setIsIqcMigrate(String isIqcMigrate) {
        this.isIqcMigrate = isIqcMigrate;
    }

    public String getIsIqcMigrate() {
        return isIqcMigrate;
    }

    public void setBatchUpLimit(Float batchUpLimit) {
        this.batchUpLimit = batchUpLimit;
    }

    public Float getBatchUpLimit() {
        return batchUpLimit;
    }

    public void setSupplierExcessRatio(Float supplierExcessRatio) {
        this.supplierExcessRatio = supplierExcessRatio;
    }

    public Float getSupplierExcessRatio() {
        return supplierExcessRatio;
    }

    public void setDeliveryRegionId(Float deliveryRegionId) {
        this.deliveryRegionId = deliveryRegionId;
    }

    public Float getDeliveryRegionId() {
        return deliveryRegionId;
    }

    public void setGlobalAttribute1(String globalAttribute1) {
        this.globalAttribute1 = globalAttribute1;
    }

    public String getGlobalAttribute1() {
        return globalAttribute1;
    }

    public void setGlobalAttribute2(String globalAttribute2) {
        this.globalAttribute2 = globalAttribute2;
    }

    public String getGlobalAttribute2() {
        return globalAttribute2;
    }

    public void setGlobalAttribute3(String globalAttribute3) {
        this.globalAttribute3 = globalAttribute3;
    }

    public String getGlobalAttribute3() {
        return globalAttribute3;
    }

    public void setGlobalAttribute4(String globalAttribute4) {
        this.globalAttribute4 = globalAttribute4;
    }

    public String getGlobalAttribute4() {
        return globalAttribute4;
    }

    public void setGlobalAttribute5(String globalAttribute5) {
        this.globalAttribute5 = globalAttribute5;
    }

    public String getGlobalAttribute5() {
        return globalAttribute5;
    }

    public void setGlobalAttribute6(String globalAttribute6) {
        this.globalAttribute6 = globalAttribute6;
    }

    public String getGlobalAttribute6() {
        return globalAttribute6;
    }

    public void setGlobalAttribute7(String globalAttribute7) {
        this.globalAttribute7 = globalAttribute7;
    }

    public String getGlobalAttribute7() {
        return globalAttribute7;
    }

    public void setGlobalAttribute8(String globalAttribute8) {
        this.globalAttribute8 = globalAttribute8;
    }

    public String getGlobalAttribute8() {
        return globalAttribute8;
    }

    public void setGlobalAttribute9(String globalAttribute9) {
        this.globalAttribute9 = globalAttribute9;
    }

    public String getGlobalAttribute9() {
        return globalAttribute9;
    }

    public void setGlobalAttribute10(String globalAttribute10) {
        this.globalAttribute10 = globalAttribute10;
    }

    public String getGlobalAttribute10() {
        return globalAttribute10;
    }

    public void setGlobalAttribute11(String globalAttribute11) {
        this.globalAttribute11 = globalAttribute11;
    }

    public String getGlobalAttribute11() {
        return globalAttribute11;
    }

    public void setGlobalAttribute12(String globalAttribute12) {
        this.globalAttribute12 = globalAttribute12;
    }

    public String getGlobalAttribute12() {
        return globalAttribute12;
    }

    public void setGlobalAttribute13(String globalAttribute13) {
        this.globalAttribute13 = globalAttribute13;
    }

    public String getGlobalAttribute13() {
        return globalAttribute13;
    }

    public void setGlobalAttribute14(String globalAttribute14) {
        this.globalAttribute14 = globalAttribute14;
    }

    public String getGlobalAttribute14() {
        return globalAttribute14;
    }

    public void setGlobalAttribute15(String globalAttribute15) {
        this.globalAttribute15 = globalAttribute15;
    }

    public String getGlobalAttribute15() {
        return globalAttribute15;
    }

    public void setControlId(Float controlId) {
        this.controlId = controlId;
    }

    public Float getControlId() {
        return controlId;
    }

}
