package com.hand.hqm.hqm_iqc_inspection_l.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = false)
@Table(name = "HQM_IQC_INSPECTION_L")
public class IqcInspectionL extends BaseDTO {

	@Id
	@GeneratedValue
	private Float lineId;

	private Float headerId;

	@Length(max = 100)
	private String inspectionAttribute;

	private Float orderCode;

	@Length(max = 30)
	private String sampleProcedureType;

	@Length(max = 30)
	private String inspectionLevels;

	@Length(max = 30)
	private String qualityCharacterGrade;

	@Length(max = 30)
	private String sizeCodeLetter;

	@Length(max = 30)
	private String acceptanceQualityLimit;

	private Float sampleSize;

	@Length(max = 30)
	private String standardType;

	@Length(max = 30)
	private String ac;

	@Length(max = 30)
	private String re;

	@Length(max = 200)
	private String textStandrad;

	@Length(max = 30)
	private String standradUom;

	private String standradFrom;

	private String standradTo;

	@Length(max = 30)
	private String frequencyType;

	private Float frequency;

	@Length(max = 90)
	private String inspectionTool;

	@Length(max = 200)
	private String remark;

	private Float inspectionCount;

	private Float conformingQty;

	private Float nonConformingQty;

	@Length(max = 1)
	private String isAdd;

	@Length(max = 1)
	private String enableType;

	@Length(max = 30)
	private String dataFrom;

	private Float precision;
	
	private Float sampleWayId;
	
	private Float sampleType;
	
	private Float parameter;
	
	private Float attributeId;
	
	private String inspectionMethod;
	
	private String attributeType;

	private String attributeInspectionRes;
	
	@Transient
	private String inspectionHistory;
	
	@Transient
	private Float rowN;
	
	private Float templateLineId;
	
	@Transient
	private String lineListString; //_D表数据List的JSON
	
	@Transient
	private String headerString; //_H表数据JSON
	
	private String samplePlan;
	
	@Transient
	private Integer valueN;
	
	@Transient
	private Integer valueM;
	
	@Transient
	private String sampleWayCode;
	
	
	public String getSampleWayCode() {
		return sampleWayCode;
	}

	public void setSampleWayCode(String sampleWayCode) {
		this.sampleWayCode = sampleWayCode;
	}

	public Integer getValueN() {
		return valueN;
	}

	public void setValueN(Integer valueN) {
		this.valueN = valueN;
	}

	public Integer getValueM() {
		return valueM;
	}

	public void setValueM(Integer valueM) {
		this.valueM = valueM;
	}

	public String getSamplePlan() {
		return samplePlan;
	}

	public void setSamplePlan(String samplePlan) {
		this.samplePlan = samplePlan;
	}

	public String getHeaderString() {
		return headerString;
	}

	public void setHeaderString(String headerString) {
		this.headerString = headerString;
	}

	public String getLineListString() {
		return lineListString;
	}

	public void setLineListString(String lineListString) {
		this.lineListString = lineListString;
	}

	public Float getTemplateLineId() {
		return templateLineId;
	}

	public void setTemplateLineId(Float templateLineId) {
		this.templateLineId = templateLineId;
	}

	public Float getRowN() {
		return rowN;
	}

	public void setRowN(Float rowN) {
		this.rowN = rowN;
	}

	private String fillInType;
	
	public String getFillInType() {
		return fillInType;
	}

	public void setFillInType(String fillInType) {
		this.fillInType = fillInType;
	}

	public Float getPrecision() {
		return precision;
	}

	public void setPrecision(Float precision) {
		this.precision = precision;
	}

	public Float getSampleWayId() {
		return sampleWayId;
	}

	public void setSampleWayId(Float sampleWayId) {
		this.sampleWayId = sampleWayId;
	}

	public Float getSampleType() {
		return sampleType;
	}

	public void setSampleType(Float sampleType) {
		this.sampleType = sampleType;
	}

	public Float getParameter() {
		return parameter;
	}

	public void setParameter(Float parameter) {
		this.parameter = parameter;
	}

	public String getInspectionMethod() {
		return inspectionMethod;
	}

	public void setInspectionMethod(String inspectionMethod) {
		this.inspectionMethod = inspectionMethod;
	}

	public String getInspectionHistory() {
		return inspectionHistory;
	}

	public void setInspectionHistory(String inspectionHistory) {
		this.inspectionHistory = inspectionHistory;
	}

	public Float getAttributeId() {
		return attributeId;
	}

	public void setAttributeId(Float attributeId) {
		this.attributeId = attributeId;
	}

	public String getAttributeType() {
		return attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	public String getAttributeInspectionRes() {
		return attributeInspectionRes;
	}

	public void setAttributeInspectionRes(String attributeInspectionRes) {
		this.attributeInspectionRes = attributeInspectionRes;
	}

	public String getDataFrom() {
		return dataFrom;
	}

	public void setDataFrom(String dataFrom) {
		this.dataFrom = dataFrom;
	}

	public void setLineId(Float lineId) {
		this.lineId = lineId;
	}

	public Float getLineId() {
		return lineId;
	}

	public void setHeaderId(Float headerId) {
		this.headerId = headerId;
	}

	public Float getHeaderId() {
		return headerId;
	}

	public void setInspectionAttribute(String inspectionAttribute) {
		this.inspectionAttribute = inspectionAttribute;
	}

	public String getInspectionAttribute() {
		return inspectionAttribute;
	}

	public void setOrderCode(Float orderCode) {
		this.orderCode = orderCode;
	}

	public Float getOrderCode() {
		return orderCode;
	}

	public void setSampleProcedureType(String sampleProcedureType) {
		this.sampleProcedureType = sampleProcedureType;
	}

	public String getSampleProcedureType() {
		return sampleProcedureType;
	}

	public void setInspectionLevels(String inspectionLevels) {
		this.inspectionLevels = inspectionLevels;
	}

	public String getInspectionLevels() {
		return inspectionLevels;
	}

	public void setQualityCharacterGrade(String qualityCharacterGrade) {
		this.qualityCharacterGrade = qualityCharacterGrade;
	}

	public String getQualityCharacterGrade() {
		return qualityCharacterGrade;
	}

	public void setSizeCodeLetter(String sizeCodeLetter) {
		this.sizeCodeLetter = sizeCodeLetter;
	}

	public String getSizeCodeLetter() {
		return sizeCodeLetter;
	}

	public void setAcceptanceQualityLimit(String acceptanceQualityLimit) {
		this.acceptanceQualityLimit = acceptanceQualityLimit;
	}

	public String getAcceptanceQualityLimit() {
		return acceptanceQualityLimit;
	}

	public void setSampleSize(Float sampleSize) {
		this.sampleSize = sampleSize;
	}

	public Float getSampleSize() {
		return sampleSize;
	}

	public void setStandardType(String standardType) {
		this.standardType = standardType;
	}

	public String getStandardType() {
		return standardType;
	}

	public void setAc(String ac) {
		this.ac = ac;
	}

	public String getAc() {
		return ac;
	}

	public void setRe(String re) {
		this.re = re;
	}

	public String getRe() {
		return re;
	}

	public void setTextStandrad(String textStandrad) {
		this.textStandrad = textStandrad;
	}

	public String getTextStandrad() {
		return textStandrad;
	}

	public void setStandradUom(String standradUom) {
		this.standradUom = standradUom;
	}

	public String getStandradUom() {
		return standradUom;
	}

	public void setStandradFrom(String standradFrom) {
		this.standradFrom = standradFrom;
	}

	public String getStandradFrom() {
		return standradFrom;
	}

	public void setStandradTo(String standradTo) {
		this.standradTo = standradTo;
	}

	public String getStandradTo() {
		return standradTo;
	}

	public void setFrequencyType(String frequencyType) {
		this.frequencyType = frequencyType;
	}

	public String getFrequencyType() {
		return frequencyType;
	}

	public void setFrequency(Float frequency) {
		this.frequency = frequency;
	}

	public Float getFrequency() {
		return frequency;
	}

	public void setInspectionTool(String inspectionTool) {
		this.inspectionTool = inspectionTool;
	}

	public String getInspectionTool() {
		return inspectionTool;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRemark() {
		return remark;
	}

	public void setInspectionCount(Float inspectionCount) {
		this.inspectionCount = inspectionCount;
	}

	public Float getInspectionCount() {
		return inspectionCount;
	}

	public void setConformingQty(Float conformingQty) {
		this.conformingQty = conformingQty;
	}

	public Float getConformingQty() {
		return conformingQty;
	}

	public void setNonConformingQty(Float nonConformingQty) {
		this.nonConformingQty = nonConformingQty;
	}

	public Float getNonConformingQty() {
		return nonConformingQty;
	}

	public void setIsAdd(String isAdd) {
		this.isAdd = isAdd;
	}

	public String getIsAdd() {
		return isAdd;
	}

	public void setEnableType(String enableType) {
		this.enableType = enableType;
	}

	public String getEnableType() {
		return enableType;
	}

}
