package com.hand.hqm.hqm_supplier_inspector_rel_his.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_SUPPLIER_INSPECTOR_REL_HIS")
public class SupplierInspectorRelHis extends BaseDTO {

	@Id
	@GeneratedValue
	private Float eventId;

	private Long eventBy;

	private Date eventTime;

	private Float relId;

	private Float plantId;

	private Float supplierId;

	private Float inspectorId;

	private Float preInspectorId;

	private Float sqeInspectorId;

	private Float preSqeId;

	@Length(max = 1)
	private String enableFlag;

	@Transient
	private String plantCode;
	@Transient
	private String supplierName;
	@Transient
	private String inspectorEmployeeName;
	@Transient
	private String preInspectorEmployeeName;
	@Transient
	private String sqeInspectorEmployeeName;
	@Transient
	private String preSqeEmployeeName;
	@Transient
	private String eventEmployeeName;

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getInspectorEmployeeName() {
		return inspectorEmployeeName;
	}

	public void setInspectorEmployeeName(String inspectorEmployeeName) {
		this.inspectorEmployeeName = inspectorEmployeeName;
	}

	public String getPreInspectorEmployeeName() {
		return preInspectorEmployeeName;
	}

	public void setPreInspectorEmployeeName(String preInspectorEmployeeName) {
		this.preInspectorEmployeeName = preInspectorEmployeeName;
	}

	public String getSqeInspectorEmployeeName() {
		return sqeInspectorEmployeeName;
	}

	public void setSqeInspectorEmployeeName(String sqeInspectorEmployeeName) {
		this.sqeInspectorEmployeeName = sqeInspectorEmployeeName;
	}

	public String getPreSqeEmployeeName() {
		return preSqeEmployeeName;
	}

	public void setPreSqeEmployeeName(String preSqeEmployeeName) {
		this.preSqeEmployeeName = preSqeEmployeeName;
	}

	public String getEventEmployeeName() {
		return eventEmployeeName;
	}

	public void setEventEmployeeName(String eventEmployeeName) {
		this.eventEmployeeName = eventEmployeeName;
	}

	public void setEventId(Float eventId) {
		this.eventId = eventId;
	}

	public Float getEventId() {
		return eventId;
	}

	public void setEventBy(Long eventBy) {
		this.eventBy = eventBy;
	}

	public Long getEventBy() {
		return eventBy;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

	public Date getEventTime() {
		return eventTime;
	}

	public void setRelId(Float relId) {
		this.relId = relId;
	}

	public Float getRelId() {
		return relId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setInspectorId(Float inspectorId) {
		this.inspectorId = inspectorId;
	}

	public Float getInspectorId() {
		return inspectorId;
	}

	public void setPreInspectorId(Float preInspectorId) {
		this.preInspectorId = preInspectorId;
	}

	public Float getPreInspectorId() {
		return preInspectorId;
	}

	public void setSqeInspectorId(Float sqeInspectorId) {
		this.sqeInspectorId = sqeInspectorId;
	}

	public Float getSqeInspectorId() {
		return sqeInspectorId;
	}

	public void setPreSqeId(Float preSqeId) {
		this.preSqeId = preSqeId;
	}

	public Float getPreSqeId() {
		return preSqeId;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

}
