package com.hand.hcs.hcs_supplier_item_version.dto;

import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.Length;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HCS_SUPPLIER_ITEM_VERSION")
public class SupplierItemVersion extends BaseDTO {

     public static final String FIELD_KID = "kid";
     public static final String FIELD_PLANT_ID = "plantId";
     public static final String FIELD_ITEM_ID = "itemId";
     public static final String FIELD_ITEM_VERSION = "itemVersion";
     public static final String FIELD_REMARKS = "remarks";
     public static final String FIELD_ENABLE_FLAG = "enableFlag";
     public static final String FIELD_MAIN_VERSION = "mainVersion";
     public static final String FIELD_STOCK_QTY = "stockQty";
     public static final String FIELD_WIP_QTY = "wipQty";
     public static final String FIELD_OUT_ORDER_QTY = "outOrderQty";
     public static final String FIELD_SUPPLIER_ID = "supplierId";


     @Id
     @GeneratedValue
     private Float kid;

     private Float plantId;

     private Float itemId;

     @Length(max = 30)
     private String itemVersion;

     @Length(max = 240)
     private String remarks;

     @Length(max = 1)
     private String enableFlag;

     @Length(max = 1)
     private String mainVersion;

     private Float stockQty;

     private Float wipQty;

     private Float outOrderQty;

     private Float supplierId;

     private Float bomId;
     
     private Date creationDate;
     
     @Transient
     private String userName;
     
     

     public Date getCreationDate() {
		return creationDate;
	}

	public String getUserName() {
		return userName;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Float getBomId() {
		return bomId;
	}

	public void setBomId(Float bomId) {
		this.bomId = bomId;
	}

	public void setKid(Float kid){
         this.kid = kid;
     }

     public Float getKid(){
         return kid;
     }

     public void setPlantId(Float plantId){
         this.plantId = plantId;
     }

     public Float getPlantId(){
         return plantId;
     }

     public void setItemId(Float itemId){
         this.itemId = itemId;
     }

     public Float getItemId(){
         return itemId;
     }

     public void setItemVersion(String itemVersion){
         this.itemVersion = itemVersion;
     }

     public String getItemVersion(){
         return itemVersion;
     }

     public void setRemarks(String remarks){
         this.remarks = remarks;
     }

     public String getRemarks(){
         return remarks;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setMainVersion(String mainVersion){
         this.mainVersion = mainVersion;
     }

     public String getMainVersion(){
         return mainVersion;
     }

     public void setStockQty(Float stockQty){
         this.stockQty = stockQty;
     }

     public Float getStockQty(){
         return stockQty;
     }

     public void setWipQty(Float wipQty){
         this.wipQty = wipQty;
     }

     public Float getWipQty(){
         return wipQty;
     }

     public void setOutOrderQty(Float outOrderQty){
         this.outOrderQty = outOrderQty;
     }

     public Float getOutOrderQty(){
         return outOrderQty;
     }

     public void setSupplierId(Float supplierId){
         this.supplierId = supplierId;
     }

     public Float getSupplierId(){
         return supplierId;
     }

     }
