package com.hand.hcs.hcs_po_headers.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "HCS_PO_HEADERS")
public class PoHeaders extends BaseDTO {

	public static final String FIELD_PO_HEADER_ID = "poHeaderId";
	public static final String FIELD_PO_NUMBER = "poNumber";
	public static final String FIELD_ORG_ID = "orgId";
	public static final String FIELD_PLANT_ID = "plantId";
	public static final String FIELD_SUPPLIER_ID = "supplierId";
	public static final String FIELD_SUPPLIER_SITE_ID = "supplierSiteId";
	public static final String FIELD_PO_AGENT_ID = "poAgentId";
	public static final String FIELD_AGENT_FULL_NAME = "agentFullName";
	public static final String FIELD_AGENT_EMAIL = "agentEmail";
	public static final String FIELD_PO_ORDER_TYPE = "poOrderType";
	public static final String FIELD_PO_STATUS = "poStatus";
	public static final String FIELD_APPROVED_STATUS = "approvedStatus";
	public static final String FIELD_CANCELED_DATE = "canceledDate";
	public static final String FIELD_CLOSED_FLAG = "closedFlag";
	public static final String FIELD_CLOSED_DATE = "closedDate";
	public static final String FIELD_CONFIRM_FLAG = "confirmFlag";
	public static final String FIELD_CONFIRM_TIME = "confirmTime";
	public static final String FIELD_SOURCE_ID = "sourceId";
	public static final String FIELD_SOURCE_REFERENCE = "sourceReference";
	public static final String FIELD_SOURCE_CODE = "sourceCode";
	public static final String FIELD_AGENT_DESC = "agentDesc";
	public static final String FIELD_SUPPLIER_DESC = "supplierDesc";
	public static final String FIELD_EDITION = "edition";
	public static final String FIELD_CURRENCY = "currency";
	public static final String FIELD_TAX_RATE = "taxRate";
	public static final String FIELD_REMARKS = "remarks";
	public static final String FIELD_ABSTRACTS = "abstracts";
	public static final String FIELD_CONTACTS = "contacts";
	public static final String FIELD_CID = "cid";
	public static final String FIELD_CANCELED_FLAG = "canceledFlag";
	public static final String FIELD_RELEASE_DATE = "releaseDate";

	@Id
	@GeneratedValue
	private Float poHeaderId;

	@Length(max = 30)
	private String poNumber;

	private Float orgId;

	private Float plantId;

	private Float supplierId;

	private Float supplierSiteId;

	private Float poAgentId;

	@Length(max = 240)
	private String agentFullName;

	@Length(max = 240)
	private String agentEmail;

	@Length(max = 240)
	private String poOrderType;

	@Length(max = 240)
	private String poStatus;

	@Length(max = 240)
	private String approvedStatus;

	private Date canceledDate;

	@Length(max = 30)
	private String closedFlag;

	@Length(max = 30)
	private String urgentStatus;

	private Date urgentTime;

	private Date closedDate;

	@Length(max = 1)
	private String confirmFlag;

	private Date confirmTime;

	private Float sourceId;

	@Length(max = 240)
	private String sourceReference;

	@Length(max = 30)
	private String sourceCode;

	@Length(max = 240)
	private String agentDesc;

	@Length(max = 240)
	private String supplierDesc;

	private Float edition;

	@Length(max = 30)
	private String currency;

	@Length(max = 30)
	private String taxRate;

	@Length(max = 30)
	private String remarks;

	@Length(max = 240)
	private String abstracts;

	@Length(max = 100)
	private String contacts;

	private Float cid;

	@Length(max = 1)
	private String canceledFlag;

	private Date releaseDate;

	private Float totalPrice;

	@Transient
	private String supplierSiteCode;// 供应商地点编码

	@Transient
	private String supplierSiteName;// 供应商地点描述

	@Transient
	private Float businessUnitId;// 业务实体Id

	@Transient
	private String businessUnitCode;// 业务实体编码

	@Transient
	private String businessUnitName;// 业务实体描述

	@Transient
	private String plantCode;// 工厂编码

	@Transient
	private String plantName;// 工厂描述

	@Transient
	private String userType;// 用户类型

	@Transient
	private String startTime;// 发布日期从

	@Transient
	private String endTime;// 发布日期至

	@Transient
	private List<Float> idList;

	@Transient
	private String supplierName;// 供应商名称
	@Transient
	private String supplierCode;// 供应商编码
	@Transient
	private String unPriceSum;// 不含税总额
	@Transient
	private String priceSum;// 含税总额

	@Transient
	private String purchaseGroup;// 采购组

	@Transient
	private Float itemId; 
	
	public Float getItemId() {
		return itemId;
	}

	public void setItemId(Float itemId) {
		this.itemId = itemId;
	}

	public String getPurchaseGroup() {
		return purchaseGroup;
	}

	public void setPurchaseGroup(String purchaseGroup) {
		this.purchaseGroup = purchaseGroup;
	}

	public String getUnPriceSum() {
		return unPriceSum;
	}

	public void setUnPriceSum(String unPriceSum) {
		this.unPriceSum = unPriceSum;
	}

	public String getPriceSum() {
		return priceSum;
	}

	public void setPriceSum(String priceSum) {
		this.priceSum = priceSum;
	}

	public Float getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getSupplierCode() {
		return supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public void setPoHeaderId(Float poHeaderId) {
		this.poHeaderId = poHeaderId;
	}

	public Float getPoHeaderId() {
		return poHeaderId;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	public String getPoNumber() {
		return poNumber;
	}

	public void setOrgId(Float orgId) {
		this.orgId = orgId;
	}

	public Float getOrgId() {
		return orgId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setSupplierSiteId(Float supplierSiteId) {
		this.supplierSiteId = supplierSiteId;
	}

	public Float getSupplierSiteId() {
		return supplierSiteId;
	}

	public void setPoAgentId(Float poAgentId) {
		this.poAgentId = poAgentId;
	}

	public Float getPoAgentId() {
		return poAgentId;
	}

	public void setAgentFullName(String agentFullName) {
		this.agentFullName = agentFullName;
	}

	public String getAgentFullName() {
		return agentFullName;
	}

	public void setAgentEmail(String agentEmail) {
		this.agentEmail = agentEmail;
	}

	public String getAgentEmail() {
		return agentEmail;
	}

	public void setPoOrderType(String poOrderType) {
		this.poOrderType = poOrderType;
	}

	public String getPoOrderType() {
		return poOrderType;
	}

	public void setPoStatus(String poStatus) {
		this.poStatus = poStatus;
	}

	public String getPoStatus() {
		return poStatus;
	}

	public void setApprovedStatus(String approvedStatus) {
		this.approvedStatus = approvedStatus;
	}

	public String getApprovedStatus() {
		return approvedStatus;
	}

	public void setCanceledDate(Date canceledDate) {
		this.canceledDate = canceledDate;
	}

	public Date getCanceledDate() {
		return canceledDate;
	}

	public void setClosedFlag(String closedFlag) {
		this.closedFlag = closedFlag;
	}

	public String getClosedFlag() {
		return closedFlag;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	public Date getClosedDate() {
		return closedDate;
	}

	public void setConfirmFlag(String confirmFlag) {
		this.confirmFlag = confirmFlag;
	}

	public String getConfirmFlag() {
		return confirmFlag;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	public Date getConfirmTime() {
		return confirmTime;
	}

	public void setSourceId(Float sourceId) {
		this.sourceId = sourceId;
	}

	public Float getSourceId() {
		return sourceId;
	}

	public void setSourceReference(String sourceReference) {
		this.sourceReference = sourceReference;
	}

	public String getSourceReference() {
		return sourceReference;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	public String getSourceCode() {
		return sourceCode;
	}

	public void setAgentDesc(String agentDesc) {
		this.agentDesc = agentDesc;
	}

	public String getAgentDesc() {
		return agentDesc;
	}

	public void setSupplierDesc(String supplierDesc) {
		this.supplierDesc = supplierDesc;
	}

	public String getSupplierDesc() {
		return supplierDesc;
	}

	public void setEdition(Float edition) {
		this.edition = edition;
	}

	public Float getEdition() {
		return edition;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getCurrency() {
		return currency;
	}

	public void setTaxRate(String taxRate) {
		this.taxRate = taxRate;
	}

	public String getTaxRate() {
		return taxRate;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setAbstracts(String abstracts) {
		this.abstracts = abstracts;
	}

	public String getAbstracts() {
		return abstracts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	public String getContacts() {
		return contacts;
	}

	public void setCid(Float cid) {
		this.cid = cid;
	}

	public Float getCid() {
		return cid;
	}

	public void setCanceledFlag(String canceledFlag) {
		this.canceledFlag = canceledFlag;
	}

	public String getCanceledFlag() {
		return canceledFlag;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public Date getReleaseDate() {
		return releaseDate;
	}

	public String getSupplierSiteCode() {
		return supplierSiteCode;
	}

	public void setSupplierSiteCode(String supplierSiteCode) {
		this.supplierSiteCode = supplierSiteCode;
	}

	public String getSupplierSiteName() {
		return supplierSiteName;
	}

	public void setSupplierSiteName(String supplierSiteName) {
		this.supplierSiteName = supplierSiteName;
	}

	public Float getBusinessUnitId() {
		return businessUnitId;
	}

	public void setBusinessUnitId(Float businessUnitId) {
		this.businessUnitId = businessUnitId;
	}

	public String getBusinessUnitCode() {
		return businessUnitCode;
	}

	public void setBusinessUnitCode(String businessUnitCode) {
		this.businessUnitCode = businessUnitCode;
	}

	public String getBusinessUnitName() {
		return businessUnitName;
	}

	public void setBusinessUnitName(String businessUnitName) {
		this.businessUnitName = businessUnitName;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getPlantName() {
		return plantName;
	}

	public void setPlantName(String plantName) {
		this.plantName = plantName;
	}

	public String getUrgentStatus() {
		return urgentStatus;
	}

	public void setUrgentStatus(String urgentStatus) {
		this.urgentStatus = urgentStatus;
	}

	public Date getUrgentTime() {
		return urgentTime;
	}

	public void setUrgentTime(Date urgentTime) {
		this.urgentTime = urgentTime;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public List<Float> getIdList() {
		return idList;
	}

	public void setIdList(List<Float> idList) {
		this.idList = idList;
	}

}
