package com.hand.hqm.hqm_measure_tool_msa_his.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_MEASURE_TOOL_MSA_HIS")
public class MeasureToolMsaHis extends BaseDTO {

     public static final String FIELD_MEASURE_TOOL_MSA_HIS_ID = "measureToolMsaHisId";
     public static final String FIELD_MEASURE_TOOL_HIS_ID = "measureToolHisId";
     public static final String FIELD_MEASURE_TOOL_MSA_ID = "measureToolMsaId";
     public static final String FIELD_MEASURE_TOOL_ID = "measureToolId";
     public static final String FIELD_MSA_CONTENT = "msaContent";
     public static final String FIELD_MSA_RESULT = "msaResult";


     @Id
     @GeneratedValue
     private Float measureToolMsaHisId;

     private Float measureToolHisId;

     private Float measureToolMsaId;

     private Float measureToolId;

     @Length(max = 50)
     private String msaContent;

     @Length(max = 5)
     private String msaResult;


     public void setMeasureToolMsaHisId(Float measureToolMsaHisId){
         this.measureToolMsaHisId = measureToolMsaHisId;
     }

     public Float getMeasureToolMsaHisId(){
         return measureToolMsaHisId;
     }

     public void setMeasureToolHisId(Float measureToolHisId){
         this.measureToolHisId = measureToolHisId;
     }

     public Float getMeasureToolHisId(){
         return measureToolHisId;
     }

     public void setMeasureToolMsaId(Float measureToolMsaId){
         this.measureToolMsaId = measureToolMsaId;
     }

     public Float getMeasureToolMsaId(){
         return measureToolMsaId;
     }

     public void setMeasureToolId(Float measureToolId){
         this.measureToolId = measureToolId;
     }

     public Float getMeasureToolId(){
         return measureToolId;
     }

     public void setMsaContent(String msaContent){
         this.msaContent = msaContent;
     }

     public String getMsaContent(){
         return msaContent;
     }

     public void setMsaResult(String msaResult){
         this.msaResult = msaResult;
     }

     public String getMsaResult(){
         return msaResult;
     }

     }
