package com.hand.npi.npi_technology.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "NPI_TECHNOLOGY_SPARE_PART")
public class TechnologySparePart extends BaseDTO {

	public static final String FIELD_SPARE_PART_ID = "sparePartId";
	public static final String FIELD_SPARE_PART_CODE = "sparePartCode";
	public static final String FIELD_SPARE_PART_NAME = "sparePartName";
	public static final String FIELD_SPARE_PART_LEVEL = "sparePartLevel";
	public static final String FIELD_PARENT_ID = "parentId";

	@Id
	@GeneratedValue
	private Float sparePartId;

	/**
	 * 零件属性编码
	 */
	@Length(max = 100)
	private String sparePartCode;

	/**
	 * 零件属性名称
	 */
	@Length(max = 100)
	private String sparePartName;

	/**
	 * 层级，有1.2.3三个层级
	 */
	@Length(max = 32)
	private String sparePartLevel;

	private Float parentId;

	public String getSparePartLevel() {
		return sparePartLevel;
	}

	public void setSparePartLevel(String sparePartLevel) {
		this.sparePartLevel = sparePartLevel;
	}

	public void setSparePartId(Float sparePartId) {
		this.sparePartId = sparePartId;
	}

	public Float getSparePartId() {
		return sparePartId;
	}

	public void setSparePartCode(String sparePartCode) {
		this.sparePartCode = sparePartCode;
	}

	public String getSparePartCode() {
		return sparePartCode;
	}

	public void setSparePartName(String sparePartName) {
		this.sparePartName = sparePartName;
	}

	public String getSparePartName() {
		return sparePartName;
	}

	public void setParentId(Float parentId) {
		this.parentId = parentId;
	}

	public Float getParentId() {
		return parentId;
	}

}
