package com.hand.hqm.hqm_qc_task.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_IQC_TASK")
public class IqcTask extends BaseDTO {

	@Id
	@GeneratedValue
	private Float taskId;

	private Float plantId;

	private Float itemId;

	@Length(max = 50)
	private String sourceOrder;

	private Float lineNum;

	@Length(max = 30)
	private String sourceType;

	@Length(max = 50)
	private String itemVersion;

	@Length(max = 50)
	private String spreading;

	@Length(max = 100)
	private String productionBatch;

	private Float supplierId;

	private Float supplierSiteId;

	@Length(max = 30)
	private String inspectionType;

	private Float receiveQty;

	private Float sampleQty;

	private Date receiveDate;

	private Float packQty;

	@Length(max = 30)
	private String packetInfo;

	private Float poNumber;

	@Length(max = 50)
	private String inspectionPlace;

	@Length(max = 30)
	private String recipientNum;

	@Length(max = 30)
	private String taskFrom;

	@Length(max = 30)
	private String isUrgency;

	@Length(max = 30)
	private String solveStatus;

	@Length(max = 100)
	private String errorMsg;

	@Length(max = 30)
	private String inspectionNum;

	@Length(max = 30)
	private String inspectionRes;

	@Length(max = 50)
	private String dealMethod;

	@Transient
	private String itemCode;
	@Transient
	private String itemDescriptions;
	@Transient
	private String plantCode;
	@Transient
	private String supplierCode;
	@Transient
	private String supplierName;
	@Transient
	private String receiveDateFrom;
	@Transient
	private String receiveDateTo;
	
	private String relOrder;
	
	private String recheckSampleWay;
	
	@Length(max = 50)
	private String wareHouseType;
	
	private Float samplePackQty;
	
	@Length(max = 50)
    private String ecrNumber;
	
	@Transient
	private String recipientNumEmployeeName;
	
	public Float getSamplePackQty() {
		return samplePackQty;
	}

	public void setSamplePackQty(Float samplePackQty) {
		this.samplePackQty = samplePackQty;
	}

	public String getRecipientNumEmployeeName() {
		return recipientNumEmployeeName;
	}

	public void setRecipientNumEmployeeName(String recipientNumEmployeeName) {
		this.recipientNumEmployeeName = recipientNumEmployeeName;
	}

	public String getRelOrder() {
		return relOrder;
	}

	public void setRelOrder(String relOrder) {
		this.relOrder = relOrder;
	}

	public String getRecheckSampleWay() {
		return recheckSampleWay;
	}

	public void setRecheckSampleWay(String recheckSampleWay) {
		this.recheckSampleWay = recheckSampleWay;
	}

	public String getReceiveDateFrom() {
		return receiveDateFrom;
	}

	public void setReceiveDateFrom(String receiveDateFrom) {
		this.receiveDateFrom = receiveDateFrom;
	}

	public String getReceiveDateTo() {
		return receiveDateTo;
	}

	public void setReceiveDateTo(String receiveDateTo) {
		this.receiveDateTo = receiveDateTo;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemDescriptions() {
		return itemDescriptions;
	}

	public void setItemDescriptions(String itemDescriptions) {
		this.itemDescriptions = itemDescriptions;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getSupplierCode() {
		return supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public void setTaskId(Float taskId) {
		this.taskId = taskId;
	}

	public Float getTaskId() {
		return taskId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setItemId(Float itemId) {
		this.itemId = itemId;
	}

	public Float getItemId() {
		return itemId;
	}

	public void setSourceOrder(String sourceOrder) {
		this.sourceOrder = sourceOrder;
	}

	public String getSourceOrder() {
		return sourceOrder;
	}

	public void setLineNum(Float lineNum) {
		this.lineNum = lineNum;
	}

	public Float getLineNum() {
		return lineNum;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	public String getSourceType() {
		return sourceType;
	}

	public void setItemVersion(String itemVersion) {
		this.itemVersion = itemVersion;
	}

	public String getItemVersion() {
		return itemVersion;
	}

	public void setSpreading(String spreading) {
		this.spreading = spreading;
	}

	public String getSpreading() {
		return spreading;
	}

	public void setProductionBatch(String productionBatch) {
		this.productionBatch = productionBatch;
	}

	public String getProductionBatch() {
		return productionBatch;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setSupplierSiteId(Float supplierSiteId) {
		this.supplierSiteId = supplierSiteId;
	}

	public Float getSupplierSiteId() {
		return supplierSiteId;
	}

	public void setInspectionType(String inspectionType) {
		this.inspectionType = inspectionType;
	}

	public String getInspectionType() {
		return inspectionType;
	}

	public void setReceiveQty(Float receiveQty) {
		this.receiveQty = receiveQty;
	}

	public Float getReceiveQty() {
		return receiveQty;
	}

	public void setSampleQty(Float sampleQty) {
		this.sampleQty = sampleQty;
	}

	public Float getSampleQty() {
		return sampleQty;
	}

	public void setReceiveDate(Date receiveDate) {
		this.receiveDate = receiveDate;
	}

	public Date getReceiveDate() {
		return receiveDate;
	}

	public void setPackQty(Float packQty) {
		this.packQty = packQty;
	}

	public Float getPackQty() {
		return packQty;
	}

	public void setPacketInfo(String packetInfo) {
		this.packetInfo = packetInfo;
	}

	public String getPacketInfo() {
		return packetInfo;
	}

	public void setPoNumber(Float poNumber) {
		this.poNumber = poNumber;
	}

	public Float getPoNumber() {
		return poNumber;
	}

	public void setInspectionPlace(String inspectionPlace) {
		this.inspectionPlace = inspectionPlace;
	}

	public String getInspectionPlace() {
		return inspectionPlace;
	}

	public void setRecipientNum(String recipientNum) {
		this.recipientNum = recipientNum;
	}

	public String getRecipientNum() {
		return recipientNum;
	}

	public void setTaskFrom(String taskFrom) {
		this.taskFrom = taskFrom;
	}

	public String getTaskFrom() {
		return taskFrom;
	}

	public void setIsUrgency(String isUrgency) {
		this.isUrgency = isUrgency;
	}

	public String getIsUrgency() {
		return isUrgency;
	}

	public void setSolveStatus(String solveStatus) {
		this.solveStatus = solveStatus;
	}

	public String getSolveStatus() {
		return solveStatus;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}

	public String getErrorMsg() {
		return errorMsg;
	}

	public void setInspectionNum(String inspectionNum) {
		this.inspectionNum = inspectionNum;
	}

	public String getInspectionNum() {
		return inspectionNum;
	}

	public void setInspectionRes(String inspectionRes) {
		this.inspectionRes = inspectionRes;
	}

	public String getInspectionRes() {
		return inspectionRes;
	}

	public void setDealMethod(String dealMethod) {
		this.dealMethod = dealMethod;
	}

	public String getDealMethod() {
		return dealMethod;
	}

	public String getWareHouseType() {
		return wareHouseType;
	}

	public void setWareHouseType(String wareHouseType) {
		this.wareHouseType = wareHouseType;
	}

	public String getEcrNumber() {
		return ecrNumber;
	}

	public void setEcrNumber(String ecrNumber) {
		this.ecrNumber = ecrNumber;
	}

}
