package com.hand.hqm.hqm_qc_task.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_OQC_TASK")
public class OqcTask extends BaseDTO {

	public static final String FIELD_TASK_ID = "taskId";
	public static final String FIELD_PLANT_ID = "plantId";
	public static final String FIELD_SOURCE_ORDER = "sourceOrder";
	public static final String FIELD_ITEM_ID = "itemId";
	public static final String FIELD_ITEM_VERSION = "itemVersion";
	public static final String FIELD_SPREADING = "spreading";
	public static final String FIELD_PRODUCTION_BATCH = "productionBatch";
	public static final String FIELD_RECEIVE_QTY = "receiveQty";
	public static final String FIELD_SAMPLE_QTY = "sampleQty";
	public static final String FIELD_WAREHOUSE_CODE = "warehouseCode";
	public static final String FIELD_WARNING_DATE = "warningDate";
	public static final String FIELD_OQC_DATE = "oqcDate";
	public static final String FIELD_IS_URGENCY = "isUrgency";
	public static final String FIELD_SOLVE_STATUS = "solveStatus";
	public static final String FIELD_ERROR_MSG = "errorMsg";
	public static final String FIELD_INSPECTION_NUM = "inspectionNum";
	public static final String FIELD_INSPECTION_RES = "inspectionRes";
	public static final String FIELD_DEAL_METHOD = "dealMethod";

	@Id
	@GeneratedValue
	private Float taskId;

	private Float plantId;

	@Length(max = 50)
	private String sourceOrder;

	private Float itemId;

	@Length(max = 50)
	private String itemVersion;

	@Length(max = 50)
	private String spreading;

	@Length(max = 100)
	private String productionBatch;

	private Float receiveQty;

	private Float sampleQty;

	@Length(max = 50)
	private String warehouseCode;

	private Date warningDate;

	private Date oqcDate;

	@Length(max = 1)
	private String isUrgency;

	@Length(max = 30)
	private String solveStatus;

	@Length(max = 100)
	private String errorMsg;

	@Length(max = 30)
	private String inspectionNum;

	@Length(max = 30)
	private String inspectionRes;

	@Length(max = 50)
	private String dealMethod;

	@Transient
	private String itemCode;

	@Transient
	private String itemDescriptions;

	@Transient
	private String plantCode;

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemDescriptions() {
		return itemDescriptions;
	}

	public void setItemDescriptions(String itemDescriptions) {
		this.itemDescriptions = itemDescriptions;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public void setTaskId(Float taskId) {
		this.taskId = taskId;
	}

	public Float getTaskId() {
		return taskId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setSourceOrder(String sourceOrder) {
		this.sourceOrder = sourceOrder;
	}

	public String getSourceOrder() {
		return sourceOrder;
	}

	public void setItemId(Float itemId) {
		this.itemId = itemId;
	}

	public Float getItemId() {
		return itemId;
	}

	public void setItemVersion(String itemVersion) {
		this.itemVersion = itemVersion;
	}

	public String getItemVersion() {
		return itemVersion;
	}

	public void setSpreading(String spreading) {
		this.spreading = spreading;
	}

	public String getSpreading() {
		return spreading;
	}

	public void setProductionBatch(String productionBatch) {
		this.productionBatch = productionBatch;
	}

	public String getProductionBatch() {
		return productionBatch;
	}

	public void setReceiveQty(Float receiveQty) {
		this.receiveQty = receiveQty;
	}

	public Float getReceiveQty() {
		return receiveQty;
	}

	public void setSampleQty(Float sampleQty) {
		this.sampleQty = sampleQty;
	}

	public Float getSampleQty() {
		return sampleQty;
	}

	public void setWarehouseCode(String warehouseCode) {
		this.warehouseCode = warehouseCode;
	}

	public String getWarehouseCode() {
		return warehouseCode;
	}

	public void setWarningDate(Date warningDate) {
		this.warningDate = warningDate;
	}

	public Date getWarningDate() {
		return warningDate;
	}

	public void setOqcDate(Date oqcDate) {
		this.oqcDate = oqcDate;
	}

	public Date getOqcDate() {
		return oqcDate;
	}

	public void setIsUrgency(String isUrgency) {
		this.isUrgency = isUrgency;
	}

	public String getIsUrgency() {
		return isUrgency;
	}

	public void setSolveStatus(String solveStatus) {
		this.solveStatus = solveStatus;
	}

	public String getSolveStatus() {
		return solveStatus;
	}

	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}

	public String getErrorMsg() {
		return errorMsg;
	}

	public void setInspectionNum(String inspectionNum) {
		this.inspectionNum = inspectionNum;
	}

	public String getInspectionNum() {
		return inspectionNum;
	}

	public void setInspectionRes(String inspectionRes) {
		this.inspectionRes = inspectionRes;
	}

	public String getInspectionRes() {
		return inspectionRes;
	}

	public void setDealMethod(String dealMethod) {
		this.dealMethod = dealMethod;
	}

	public String getDealMethod() {
		return dealMethod;
	}

}
