package com.hand.hqm.hqm_qua_ins_time_h.dto;

import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_QUA_INS_TIME_H")
public class QuaInsTimeH extends BaseDTO {

	@Id
	@GeneratedValue
	private Float timeId;

	private Float plantId;

	private Float prodLineId;

	@Length(max = 20)
	private String shiftCode;

	@Length(max = 1)
	private String enableFlag;

	private Float inspectorId;

	@Transient
	private String inspectorEmployeeName;

	@Transient
	private String plantCode;

	@Transient
	private String prodLineCode;

	@Transient
	private String updateBy;

	@Transient
	private String updateDate;

	@Transient
	private Date checkDate;
	
	private String inspectionTime;

	public String getInspectionTime() {
		return inspectionTime;
	}

	public void setInspectionTime(String inspectionTime) {
		this.inspectionTime = inspectionTime;
	}

	public Date getCheckDate() {
		return checkDate;
	}

	public void setCheckDate(Date checkDate) {
		this.checkDate = checkDate;
	}

	public Float getInspectorId() {
		return inspectorId;
	}

	public void setInspectorId(Float inspectorId) {
		this.inspectorId = inspectorId;
	}

	public String getInspectorEmployeeName() {
		return inspectorEmployeeName;
	}

	public void setInspectorEmployeeName(String inspectorEmployeeName) {
		this.inspectorEmployeeName = inspectorEmployeeName;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getProdLineCode() {
		return prodLineCode;
	}

	public void setProdLineCode(String prodLineCode) {
		this.prodLineCode = prodLineCode;
	}

	public String getUpdateBy() {
		return updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	public String getUpdateDate() {
		return updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public void setTimeId(Float timeId) {
		this.timeId = timeId;
	}

	public Float getTimeId() {
		return timeId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setProdLineId(Float prodLineId) {
		this.prodLineId = prodLineId;
	}

	public Float getProdLineId() {
		return prodLineId;
	}

	public void setShiftCode(String shiftCode) {
		this.shiftCode = shiftCode;
	}

	public String getShiftCode() {
		return shiftCode;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

}
