package com.hand.hqm.hqm_sample_manage.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_SAMPLE_MANAGE")
public class SampleManage extends BaseDTO {

	@Id
	@GeneratedValue
	private Float sampleWayId;

	@Length(max = 100)
	private String sampleWayCode;

	@Transient
	private String sampleTypeMeaning;

	@Length(max = 200)
	private String description;

	@Length(max = 10)
	private String sampleType;

	private String parameter;

	@Length(max = 30)
	private String sampleProcedureType;

	@Length(max = 30)
	private String inspectionLevels;

	@Length(max = 30)
	private String acceptanceQualityLimit;

	@Length(max = 30)
	private String standradUom;

	@Length(max = 5)
	private String enableFlag;

	@Length(max = 200)
	private String remark;
	
	private Float parameterS;
	
	private Float parameterL;

	public Float getParameterS() {
		return parameterS;
	}

	public void setParameterS(Float parameterS) {
		this.parameterS = parameterS;
	}

	public Float getParameterL() {
		return parameterL;
	}

	public void setParameterL(Float parameterL) {
		this.parameterL = parameterL;
	}

	public String getSampleTypeMeaning() {
		return sampleTypeMeaning;
	}

	public void setSampleTypeMeaning(String sampleTypeMeaning) {
		this.sampleTypeMeaning = sampleTypeMeaning;
	}

	public void setSampleWayId(Float sampleWayId) {
		this.sampleWayId = sampleWayId;
	}

	public Float getSampleWayId() {
		return sampleWayId;
	}

	public void setSampleWayCode(String sampleWayCode) {
		this.sampleWayCode = sampleWayCode;
	}

	public String getSampleWayCode() {
		return sampleWayCode;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

	public void setSampleType(String sampleType) {
		this.sampleType = sampleType;
	}

	public String getSampleType() {
		return sampleType;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	public String getParameter() {
		return parameter;
	}

	public void setSampleProcedureType(String sampleProcedureType) {
		this.sampleProcedureType = sampleProcedureType;
	}

	public String getSampleProcedureType() {
		return sampleProcedureType;
	}

	public void setInspectionLevels(String inspectionLevels) {
		this.inspectionLevels = inspectionLevels;
	}

	public String getInspectionLevels() {
		return inspectionLevels;
	}

	public void setAcceptanceQualityLimit(String acceptanceQualityLimit) {
		this.acceptanceQualityLimit = acceptanceQualityLimit;
	}

	public String getAcceptanceQualityLimit() {
		return acceptanceQualityLimit;
	}

	public void setStandradUom(String standradUom) {
		this.standradUom = standradUom;
	}

	public String getStandradUom() {
		return standradUom;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRemark() {
		return remark;
	}

}
