package com.hand.hcs.hcs_suppliers.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HCS_SUPPLIERS")
public class Suppliers extends BaseDTO {

	public static final String FIELD_SUPPLIER_ID = "supplierId";
	public static final String FIELD_SUPPLIER_CODE = "supplierCode";
	public static final String FIELD_SUPPLIER_NAME = "supplierName";
	public static final String FIELD_SUPPLIER_NAME_ALT = "supplierNameAlt";
	public static final String FIELD_START_DATE = "startDate";
	public static final String FIELD_END_DATE = "endDate";
	public static final String FIELD_CID = "cid";

	@Id
	@GeneratedValue
	private Float supplierId;

	@Length(max = 30)
	private String supplierCode;

	@Length(max = 240)
	private String supplierName;

	@Length(max = 320)
	private String supplierNameAlt;

	private Date startDate;

	private Date endDate;

	private Float cid;

	@Transient
	private Float supplersSiteId;

	@Transient
	private String supplierSiteCode;

	@Transient
	private Float userId;

	@Transient
	private String userName;

	@Transient
	private String userType;

	@Transient
	private String supplierSiteDescription;

	@Transient
	private String email;

	private Float paymentTerms;

	public Float getPaymentTerms() {
		return paymentTerms;
	}

	public void setPaymentTerms(Float paymentTerms) {
		this.paymentTerms = paymentTerms;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSupplierSiteDescription() {
		return supplierSiteDescription;
	}

	public void setSupplierSiteDescription(String supplierSiteDescription) {
		this.supplierSiteDescription = supplierSiteDescription;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public Float getUserId() {
		return userId;
	}

	public void setUserId(Float userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Float getSupplersSiteId() {
		return supplersSiteId;
	}

	public void setSupplersSiteId(Float supplersSiteId) {
		this.supplersSiteId = supplersSiteId;
	}

	public String getSupplierSiteCode() {
		return supplierSiteCode;
	}

	public void setSupplierSiteCode(String supplierSiteCode) {
		this.supplierSiteCode = supplierSiteCode;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	public String getSupplierCode() {
		return supplierCode;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierNameAlt(String supplierNameAlt) {
		this.supplierNameAlt = supplierNameAlt;
	}

	public String getSupplierNameAlt() {
		return supplierNameAlt;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setCid(Float cid) {
		this.cid = cid;
	}

	public Float getCid() {
		return cid;
	}

}
