package com.hand.hqm.hqm_msa_consistency_value.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import java.util.List;
import java.util.Map;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_MSA_CONSISTENCY_VALUE")
public class MsaConsistencyValue extends BaseDTO {

	public static final String FIELD_MSA_CONSISTENCY_VALUE_ID = "msaConsistencyValueId";
	public static final String FIELD_MSA_PLAN_ID = "msaPlanId";
	public static final String FIELD_SAMPLE_NUM = "sampleNum";
	public static final String FIELD_MEASURE_DATE = "measureDate";
	public static final String FIELD_MEASURE_NUM = "measureNum";
	public static final String FIELD_MEASURE_VALUE = "measureValue";
	public static final String FIELD_MEASURED_BY = "measuredBy";
	public static final String FIELD_STANDARD_VALUE = "standardValue";

	@Id
	@GeneratedValue
	private Float msaConsistencyValueId;

	private Float msaPlanId;

	@Length(max = 50)
	private String sampleNum;

	private Date measureDate;

	private Float measureNum;
	@Length(max = 30)
	private String measureValue;

	@Length(max = 50)
	private String measuredBy;

	@Length(max = 30)
	private String standardValue;

	@Transient
    private String sampleDescription;//样品名称
    @Transient
    private String measureCharacter;//待测特性
    
	@Transient
	private List<String> sampleAndStandardList;
	
	@Transient
	private Map<String, Map<Float, List<MsaConsistencyValue>>> map;

	@Transient
	private Map<String, Map<Float, List<MsaConsistencyValue>>> sampleNumAndmeasuredByMap;
	
	@Transient
	private Map<String, List<MsaConsistencyValue>> sampleNumMap;
	
	

	public Map<String, List<MsaConsistencyValue>> getSampleNumMap() {
		return sampleNumMap;
	}

	public void setSampleNumMap(Map<String, List<MsaConsistencyValue>> sampleNumMap) {
		this.sampleNumMap = sampleNumMap;
	}

	public Map<String, Map<Float, List<MsaConsistencyValue>>> getSampleNumAndmeasuredByMap() {
		return sampleNumAndmeasuredByMap;
	}

	public void setSampleNumAndmeasuredByMap(Map<String, Map<Float, List<MsaConsistencyValue>>> sampleNumAndmeasuredByMap) {
		this.sampleNumAndmeasuredByMap = sampleNumAndmeasuredByMap;
	}

	public String getSampleDescription() {
		return sampleDescription;
	}

	public String getMeasureCharacter() {
		return measureCharacter;
	}

	public void setSampleDescription(String sampleDescription) {
		this.sampleDescription = sampleDescription;
	}

	public void setMeasureCharacter(String measureCharacter) {
		this.measureCharacter = measureCharacter;
	}

	public Map<String, Map<Float, List<MsaConsistencyValue>>> getMap() {
		return map;
	}

	public void setMap(Map<String, Map<Float, List<MsaConsistencyValue>>> map) {
		this.map = map;
	}

	public List<String> getSampleAndStandardList() {
		return sampleAndStandardList;
	}

	public void setSampleAndStandardList(List<String> sampleAndStandardList) {
		this.sampleAndStandardList = sampleAndStandardList;
	}

	public String getSampleAndStandard() {
		return this.sampleNum + "," + this.standardValue;
	}

	public void setMsaConsistencyValueId(Float msaConsistencyValueId) {
		this.msaConsistencyValueId = msaConsistencyValueId;
	}

	public Float getMsaConsistencyValueId() {
		return msaConsistencyValueId;
	}

	public void setMsaPlanId(Float msaPlanId) {
		this.msaPlanId = msaPlanId;
	}

	public Float getMsaPlanId() {
		return msaPlanId;
	}

	public void setSampleNum(String sampleNum) {
		this.sampleNum = sampleNum;
	}

	public String getSampleNum() {
		return sampleNum;
	}

	public void setMeasureDate(Date measureDate) {
		this.measureDate = measureDate;
	}

	public Date getMeasureDate() {
		return measureDate;
	}

	public void setMeasureNum(Float measureNum) {
		this.measureNum = measureNum;
	}

	public Float getMeasureNum() {
		return measureNum;
	}

	

	public String getMeasureValue() {
		return measureValue;
	}

	public void setMeasureValue(String measureValue) {
		this.measureValue = measureValue;
	}

	public void setMeasuredBy(String measuredBy) {
		this.measuredBy = measuredBy;
	}

	public String getMeasuredBy() {
		return measuredBy;
	}

	public void setStandardValue(String standardValue) {
		this.standardValue = standardValue;
	}

	public String getStandardValue() {
		return standardValue;
	}

}
