package com.hand.sys.sys_user.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = false)
@Table(name = "SYS_USER")
public class UserSys extends BaseDTO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2842989004540418527L;

	@Id
	@GeneratedValue
	private Float userId;

	@Length(max = 30)
	private String userType;

	@Length(max = 40)
	private String userName;

	@Length(max = 80)
	private String passwordEncrypted;

	@Length(max = 150)
	private String email;

	@Length(max = 40)
	private String phone;

	@Length(max = 11)
	private String startActiveDate;

	@Length(max = 11)
	private String endActiveDate;

	@Length(max = 30)
	private String status;

	@Length(max = 11)
	private String lastLoginDate;

	@Length(max = 11)
	private String lastPasswordUpdateDate;

	@Length(max = 1)
	private String firstLogin;

	@Length(max = 255)
	private String description;

	private Float employeeId;

	private Float customerId;

	private Float supplierId;

	@Transient
	private String supplierName;

	@Transient
	private String employeeCode;

	@Transient
	private String employeeName;
	
	@Transient
	private String successFlag;
	
	public String getSuccessFlag() {
		return successFlag;
	}

	public void setSuccessFlag(String successFlag) {
		this.successFlag = successFlag;
	}

	public String getEmployeeCode() {
		return employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public Float getUserId() {
		return userId;
	}

	public void setUserId(Float userId) {
		this.userId = userId;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserName() {
		return userName;
	}

	public void setPasswordEncrypted(String passwordEncrypted) {
		this.passwordEncrypted = passwordEncrypted;
	}

	public String getPasswordEncrypted() {
		return passwordEncrypted;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return email;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPhone() {
		return phone;
	}

	public void setStartActiveDate(String startActiveDate) {
		this.startActiveDate = startActiveDate;
	}

	public String getStartActiveDate() {
		return startActiveDate;
	}

	public void setEndActiveDate(String endActiveDate) {
		this.endActiveDate = endActiveDate;
	}

	public String getEndActiveDate() {
		return endActiveDate;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

	public void setLastLoginDate(String lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public String getLastLoginDate() {
		return lastLoginDate;
	}

	public void setLastPasswordUpdateDate(String lastPasswordUpdateDate) {
		this.lastPasswordUpdateDate = lastPasswordUpdateDate;
	}

	public String getLastPasswordUpdateDate() {
		return lastPasswordUpdateDate;
	}

	public void setFirstLogin(String firstLogin) {
		this.firstLogin = firstLogin;
	}

	public String getFirstLogin() {
		return firstLogin;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

	public void setEmployeeId(Float employeeId) {
		this.employeeId = employeeId;
	}

	public Float getEmployeeId() {
		return employeeId;
	}

	public void setCustomerId(Float customerId) {
		this.customerId = customerId;
	}

	public Float getCustomerId() {
		return customerId;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getSupplierId() {
		return supplierId;
	}

}
