package com.hand.dimension.hqm_dimension_improving_actions.dto;

import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_8D_IMPROVING_ACTIONS")
public class DimensionImprovingActions extends BaseDTO {
     private Float step;

     @Id
     @GeneratedValue
     private Float actionId;

     private Float orderId;

     private String improvingAction;

     @Length(max = 300)
     private String actionDescription;
     
     private String enableFlag;

     public String getEnableFlag() {
		return enableFlag;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}
     public String getImprovingAction() {
		return improvingAction;
	}

	public void setImprovingAction(String improvingAction) {
		this.improvingAction = improvingAction;
	}

	private Float userId;

     private Float principalId;
     
     private Float totalScore;
     
     private Date estimatedFinishTime;
     
     private Date actualFinishiTime;
     
     @Transient
     private Float rowNum;
     
     @Transient
     private String employeeName;

     public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public Float getPrincipalId() {
		return principalId;
	}

	public Float getRowNum() {
		return rowNum;
	}

	public void setRowNum(Float rowNum) {
		this.rowNum = rowNum;
	}

	public void setPrincipalId(Float principalId) {
		this.principalId = principalId;
	}

	public Date getEstimatedFinishTime() {
		return estimatedFinishTime;
	}

	public void setEstimatedFinishTime(Date estimatedFinishTime) {
		this.estimatedFinishTime = estimatedFinishTime;
	}

	public Date getActualFinishiTime() {
		return actualFinishiTime;
	}

	public void setActualFinishiTime(Date actualFinishiTime) {
		this.actualFinishiTime = actualFinishiTime;
	}

	@Length(max = 300)
     private String remark;
     
     @Transient
     private String userNames;
     @Transient
     private String userName;
     @Transient
     private String userIds;
     @Transient
     private String evaluateIds;
     @Transient
     private String principalName;
     
     private String cfNum;
     private String actionStatus;

     public String getCfNum() {
    return cfNum;
  }

  public void setCfNum(String cfNum) {
    this.cfNum = cfNum;
  }

  public String getActionStatus() {
    return actionStatus;
  }

  public void setActionStatus(String actionStatus) {
    this.actionStatus = actionStatus;
  }

	public String getPrincipalName() {
		return principalName;
	}

	public void setPrincipalName(String principalName) {
		this.principalName = principalName;
	}

	public String getUserNames() {
		return userNames;
	}

	public void setUserNames(String userNames) {
		this.userNames = userNames;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserIds() {
		return userIds;
	}

	public void setUserIds(String userIds) {
		this.userIds = userIds;
	}

	public String getEvaluateIds() {
		return evaluateIds;
	}

	public void setEvaluateIds(String evaluateIds) {
		this.evaluateIds = evaluateIds;
	}

	public void setStep(Float step){
         this.step = step;
     }

     public Float getStep(){
         return step;
     }

     public void setActionId(Float actionId){
         this.actionId = actionId;
     }

     public Float getActionId(){
         return actionId;
     }

     public void setOrderId(Float orderId){
         this.orderId = orderId;
     }

     public Float getOrderId(){
         return orderId;
     }
     
     


     public void setActionDescription(String actionDescription){
         this.actionDescription = actionDescription;
     }

     public String getActionDescription(){
         return actionDescription;
     }

     public void setUserId(Float userId){
         this.userId = userId;
     }

     public Float getUserId(){
         return userId;
     }

     public void setTotalScore(Float totalScore){
         this.totalScore = totalScore;
     }

     public Float getTotalScore(){
         return totalScore;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     }
