package com.hand.dimension.hqm_dimension_team_assembled.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_8D_TEAM_ASSEMBLED")
public class DimensionTeamAssembled extends BaseDTO {

     public static final String FIELD_KID = "kid";
     public static final String FIELD_STEP = "step";
     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_MEMBER_ID = "memberId";
     public static final String FIELD_MEMBER_ROLE = "memberRole";
     public static final String FIELD_REMARK = "remark";


     @Id
     @GeneratedValue
     private Float kid;

     private Float step;

     private Float orderId;

     private Float memberId;

     @Length(max = 300)
     private String memberRole;

     @Length(max = 300)
     private String remark;

     @Transient
     private String employeeName;
     @Transient
     private String employeeMobil;
     @Transient
     private String orgPositionName;
     @Transient
     private String orgUnitDes;
     @Transient
     private String employeeEmail;
     @Transient
     private Float userId;
     @Transient
     private Float employeeId;
     public Float getUserId() {
		return userId;
	}

	public Float getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Float employeeId) {
		this.employeeId = employeeId;
	}

	public void setUserId(Float userId) {
		this.userId = userId;
	}

	public String getEmployeeEmail() {
		return employeeEmail;
	}

	public void setEmployeeEmail(String employeeEmail) {
		this.employeeEmail = employeeEmail;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getEmployeeMobil() {
		return employeeMobil;
	}

	public void setEmployeeMobil(String employeeMobil) {
		this.employeeMobil = employeeMobil;
	}

	public String getOrgPositionName() {
		return orgPositionName;
	}

	public void setOrgPositionName(String orgPositionName) {
		this.orgPositionName = orgPositionName;
	}

	public String getOrgUnitDes() {
		return orgUnitDes;
	}

	public void setOrgUnitDes(String orgUnitDes) {
		this.orgUnitDes = orgUnitDes;
	}

	public void setKid(Float kid){
         this.kid = kid;
     }

     public Float getKid(){
         return kid;
     }
     public void setStep(Float step){
         this.step = step;
     }

     public Float getStep(){
         return step;
     }

     public void setOrderId(Float orderId){
         this.orderId = orderId;
     }

     public Float getOrderId(){
         return orderId;
     }

     public void setMemberId(Float memberId){
         this.memberId = memberId;
     }

     public Float getMemberId(){
         return memberId;
     }

     public void setMemberRole(String memberRole){
         this.memberRole = memberRole;
     }

     public String getMemberRole(){
         return memberRole;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     }
