package com.hand.spc.pspc_count_sample_data_class.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.springframework.beans.factory.annotation.Autowired;

@ExtensionAttribute(disable=true)
@Table(name = "PSPC_COUNT_SAMPLE_DATA_CLASS")
public class CountSampleDataClass extends BaseDTO {

     public static final String FIELD_COUNT_SAMPLE_DATA_CLASSIFY_ID = "countSampleDataClassifyId";
     public static final String FIELD_TENANT_ID = "tenantId";
     public static final String FIELD_SITE_ID = "siteId";
     public static final String FIELD_COUNT_SAMPLE_DATA_ID = "countSampleDataId";
     public static final String FIELD_CLASSIFY_ID = "classifyId";
     public static final String FIELD_CLASSIFY_COUNT_VALUE = "classifyCountValue";

     @Id
     @GeneratedValue
     private Long countSampleDataClassifyId;

     private Long tenantId;

     private Long siteId;

     private Long countSampleDataId;

     private Long classifyId;

     private Double classifyCountValue;

    /**
     * 分类项描述
     */
    @Transient
     private String classifyDescription;

    public String getClassifyDescription() {
        return classifyDescription;
    }

    public void setClassifyDescription(String classifyDescription) {
        this.classifyDescription = classifyDescription;
    }

    public Long getCountSampleDataClassifyId() {
        return countSampleDataClassifyId;
    }

    public void setCountSampleDataClassifyId(Long countSampleDataClassifyId) {
        this.countSampleDataClassifyId = countSampleDataClassifyId;
    }

    public Long getTenantId() {
        return tenantId;
    }

    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    public Long getSiteId() {
        return siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
    }

    public Long getCountSampleDataId() {
        return countSampleDataId;
    }

    public void setCountSampleDataId(Long countSampleDataId) {
        this.countSampleDataId = countSampleDataId;
    }

    public Long getClassifyId() {
        return classifyId;
    }

    public void setClassifyId(Long classifyId) {
        this.classifyId = classifyId;
    }

    public Double getClassifyCountValue() {
        return classifyCountValue;
    }

    public void setClassifyCountValue(Double classifyCountValue) {
        this.classifyCountValue = classifyCountValue;
    }
}
