package com.hand.hqm.hqm_platform_program.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_PLATFORM_PROGRAM")
public class PlatformProgram extends BaseDTO {

	@Id
	@GeneratedValue
	private Float platformId;

	private Float plantId;

	@Length(max = 30)
	private String programType;

	@Length(max = 30)
	private String sampleType;

	@Length(max = 1)
	private String enableFlag;

	private String platformType;

	@Transient
	private String plantCode;
	
	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getPlatformType() {
		return platformType;
	}

	public void setPlatformType(String platformType) {
		this.platformType = platformType;
	}

	public void setPlatformId(Float platformId) {
		this.platformId = platformId;
	}

	public Float getPlatformId() {
		return platformId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setProgramType(String programType) {
		this.programType = programType;
	}

	public String getProgramType() {
		return programType;
	}

	public void setSampleType(String sampleType) {
		this.sampleType = sampleType;
	}

	public String getSampleType() {
		return sampleType;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

}
