package com.hand.hqm.hqm_sample_account_after.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_SAMPLE_ACCOUNT")
public class SampleAccountAfter extends BaseDTO {

     
     @Id
     @GeneratedValue
     private Float sampleId;

     private String sampleCode;
     
     private String productIssue;
     
     private String badElement;
     
     private String analysisStatus;
     
     public String getAnalysisStatus() {
		return analysisStatus;
	}

	public void setAnalysisStatus(String analysisStatus) {
		this.analysisStatus = analysisStatus;
	}

	public String getBadElement() {
		return badElement;
	}

	public void setBadElement(String badElement) {
		this.badElement = badElement;
	}

	public String getProductIssue() {
		return productIssue;
	}

	public void setProductIssue(String productIssue) {
		this.productIssue = productIssue;
	}

	public String getSampleCode() {
		return sampleCode;
	}

	public void setSampleCode(String sampleCode) {
		this.sampleCode = sampleCode;
	}

	@Length(max = 1)
     private String sampleType;

     private Float plantId;

     @Length(max = 50)
     private String sampleModel;

     private Float itemId;

     @Length(max = 2)
     private String sealingSampleVerson;

     @Length(max = 50)
     private String description;

     @Length(max = 10)
     private String sealingSamplePositionStatus;

     @Length(max = 10)
     private String sealingSampleStatus;

     private Float sealingSamplePrincipal;

     private Float registrationBy;

     @Length(max = 50)
     private String storageLocation;
     
     @Length(max = 1)
     private String machineComponent;
     
     @Length(max = 20)
     private String appealNunber;
     
     @Length(max = 1)
     private String productType;
     @Length(max =200)
     private String returnReason;
     @Length(max = 200)
     private String analysisResult;
     @Length(max = 200)
     private String badComponent;
     
     private Float analyst;
     @Transient
     @Length(max = 200)
     private String analystName;
     private Date analysisDate;
     public String getAnalystName() {
		return analystName;
	}

	public void setAnalystName(String analystName) {
		this.analystName = analystName;
	}

	public String getMachineComponent() {
		return machineComponent;
	}

	public void setMachineComponent(String machineComponent) {
		this.machineComponent = machineComponent;
	}

	public String getAppealNunber() {
		return appealNunber;
	}

	public void setAppealNunber(String appealNunber) {
		this.appealNunber = appealNunber;
	}

	public String getProductType() {
		return productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getReturnReason() {
		return returnReason;
	}

	public void setReturnReason(String returnReason) {
		this.returnReason = returnReason;
	}

	public String getAnalysisResult() {
		return analysisResult;
	}

	public void setAnalysisResult(String analysisResult) {
		this.analysisResult = analysisResult;
	}

	public String getBadComponent() {
		return badComponent;
	}

	public void setBadComponent(String badComponent) {
		this.badComponent = badComponent;
	}

	public Float getAnalyst() {
		return analyst;
	}

	public void setAnalyst(Float analyst) {
		this.analyst = analyst;
	}

	public Date getAnalysisDate() {
		return analysisDate;
	}

	public void setAnalysisDate(Date analysisDate) {
		this.analysisDate = analysisDate;
	}

	public String getDealResult() {
		return dealResult;
	}

	public void setDealResult(String dealResult) {
		this.dealResult = dealResult;
	}

	@Length(max = 50)
     private String dealResult;
     
     private Float supplierId;

     private Float sampleGiver;

     private Date sampleGiveDate;

     private Float sampleUser;

     private Date sampleUseDate;

     @Length(max = 10)
     @Transient
     private String sampleUseDepartment;

     @Length(max = 5)
     private String enableFlag;

     private Date invalidDate;

     @Length(max = 5)
     private String scrappedFlag;

     private Date scrappedDate;

     @Length(max = 50)
     private String scrappedDocument;

     @Length(max = 1)
     private String aftersaleSampleType;

     @Length(max = 100)
     private String dealer;

     private Date productionDate;

     @Length(max = 1)
     private String returnStatus;

     private Float testCode;

     @Length(max = 1)
     private String sampleAttribute;

     @Length(max = 50)
     private String competingBrand;

     @Length(max = 1)
     private String availableStatus;

     @Length(max = 10)
     private String keepBy;

     @Length(max = 10)
     private String testBy;

     @Transient
     private String plantCode;
     
     @Transient
     private String itemCode;
     
     @Transient
     private String itemDescriptions;
     
     @Transient
     private String itemType;
     
     @Transient
     private String createdName;
     
     @Transient
     private String supplierCode;
     
     @Transient
     private String supplierName;
     
     @Transient
     private String sampleGiverName;
     
     @Transient
     private String applicantDocumentCode;
     
     @Transient
     private String sampleUserName;
     
     @Transient
     private String useDocumentCode;

     @Transient
     private String plantDescriptions;
     
     @Transient
     private String scrappedIds;
     
     @Transient
     private String useIds;
     
     @Transient
     private String sampleGiveDateFrom;
     
     @Transient
     private String sampleGiveDateTo;
     
     private String processingMethod;
     private String reworkStatus;
     private String returnSupplierStatus;
     private String scrapStatus;
     private String userId;
     private String useDepartment;
     
     public String getProcessingMethod() {
		return processingMethod;
	}

	public void setProcessingMethod(String processingMethod) {
		this.processingMethod = processingMethod;
	}

	public String getReworkStatus() {
		return reworkStatus;
	}

	public void setReworkStatus(String reworkStatus) {
		this.reworkStatus = reworkStatus;
	}

	public String getReturnSupplierStatus() {
		return returnSupplierStatus;
	}

	public void setReturnSupplierStatus(String returnSupplierStatus) {
		this.returnSupplierStatus = returnSupplierStatus;
	}

	public String getScrapStatus() {
		return scrapStatus;
	}

	public void setScrapStatus(String scrapStatus) {
		this.scrapStatus = scrapStatus;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUseDepartment() {
		return useDepartment;
	}

	public void setUseDepartment(String useDepartment) {
		this.useDepartment = useDepartment;
	}

	public String getSampleGiveDateFrom() {
		return sampleGiveDateFrom;
	}

	public void setSampleGiveDateFrom(String sampleGiveDateFrom) {
		this.sampleGiveDateFrom = sampleGiveDateFrom;
	}

	public String getSampleGiveDateTo() {
		return sampleGiveDateTo;
	}

	public void setSampleGiveDateTo(String sampleGiveDateTo) {
		this.sampleGiveDateTo = sampleGiveDateTo;
	}

	public String getScrappedIds() {
		return scrappedIds;
	}

	public void setScrappedIds(String scrappedIds) {
		this.scrappedIds = scrappedIds;
	}

	public String getUseIds() {
		return useIds;
	}

	public void setUseIds(String useIds) {
		this.useIds = useIds;
	}

	public String getPlantDescriptions() {
		return plantDescriptions;
	}

	public void setPlantDescriptions(String plantDescriptions) {
		this.plantDescriptions = plantDescriptions;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemDescriptions() {
		return itemDescriptions;
	}

	public void setItemDescriptions(String itemDescriptions) {
		this.itemDescriptions = itemDescriptions;
	}

	public String getItemType() {
		return itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	public String getCreatedName() {
		return createdName;
	}

	public void setCreatedName(String createdName) {
		this.createdName = createdName;
	}

	public String getSupplierCode() {
		return supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getSampleGiverName() {
		return sampleGiverName;
	}

	public void setSampleGiverName(String sampleGiverName) {
		this.sampleGiverName = sampleGiverName;
	}

	public String getApplicantDocumentCode() {
		return applicantDocumentCode;
	}

	public void setApplicantDocumentCode(String applicantDocumentCode) {
		this.applicantDocumentCode = applicantDocumentCode;
	}

	public String getSampleUserName() {
		return sampleUserName;
	}

	public void setSampleUserName(String sampleUserName) {
		this.sampleUserName = sampleUserName;
	}

	public String getUseDocumentCode() {
		return useDocumentCode;
	}

	public void setUseDocumentCode(String useDocumentCode) {
		this.useDocumentCode = useDocumentCode;
	}

	public void setSampleId(Float sampleId){
         this.sampleId = sampleId;
     }

     public Float getSampleId(){
         return sampleId;
     }

     public void setSampleType(String sampleType){
         this.sampleType = sampleType;
     }

     public String getSampleType(){
         return sampleType;
     }

     public void setPlantId(Float plantId){
         this.plantId = plantId;
     }

     public Float getPlantId(){
         return plantId;
     }

     public void setSampleModel(String sampleModel){
         this.sampleModel = sampleModel;
     }

     public String getSampleModel(){
         return sampleModel;
     }

     public void setItemId(Float itemId){
         this.itemId = itemId;
     }

     public Float getItemId(){
         return itemId;
     }

     public void setSealingSampleVerson(String sealingSampleVerson){
         this.sealingSampleVerson = sealingSampleVerson;
     }

     public String getSealingSampleVerson(){
         return sealingSampleVerson;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setSealingSamplePositionStatus(String sealingSamplePositionStatus){
         this.sealingSamplePositionStatus = sealingSamplePositionStatus;
     }

     public String getSealingSamplePositionStatus(){
         return sealingSamplePositionStatus;
     }

     public void setSealingSampleStatus(String sealingSampleStatus){
         this.sealingSampleStatus = sealingSampleStatus;
     }

     public String getSealingSampleStatus(){
         return sealingSampleStatus;
     }

     public void setSealingSamplePrincipal(Float sealingSamplePrincipal){
         this.sealingSamplePrincipal = sealingSamplePrincipal;
     }

     public Float getSealingSamplePrincipal(){
         return sealingSamplePrincipal;
     }

     public void setRegistrationBy(Float registrationBy){
         this.registrationBy = registrationBy;
     }

     public Float getRegistrationBy(){
         return registrationBy;
     }

     public void setStorageLocation(String storageLocation){
         this.storageLocation = storageLocation;
     }

     public String getStorageLocation(){
         return storageLocation;
     }

     public void setSupplierId(Float supplierId){
         this.supplierId = supplierId;
     }

     public Float getSupplierId(){
         return supplierId;
     }

     public void setSampleGiver(Float sampleGiver){
         this.sampleGiver = sampleGiver;
     }

     public Float getSampleGiver(){
         return sampleGiver;
     }

     public void setSampleGiveDate(Date sampleGiveDate){
         this.sampleGiveDate = sampleGiveDate;
     }

     public Date getSampleGiveDate(){
         return sampleGiveDate;
     }

     public void setSampleUser(Float sampleUser){
         this.sampleUser = sampleUser;
     }

     public Float getSampleUser(){
         return sampleUser;
     }

     public void setSampleUseDate(Date sampleUseDate){
         this.sampleUseDate = sampleUseDate;
     }

     public Date getSampleUseDate(){
         return sampleUseDate;
     }

     public void setSampleUseDepartment(String sampleUseDepartment){
         this.sampleUseDepartment = sampleUseDepartment;
     }

     public String getSampleUseDepartment(){
         return sampleUseDepartment;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setInvalidDate(Date invalidDate){
         this.invalidDate = invalidDate;
     }

     public Date getInvalidDate(){
         return invalidDate;
     }

     public void setScrappedFlag(String scrappedFlag){
         this.scrappedFlag = scrappedFlag;
     }

     public String getScrappedFlag(){
         return scrappedFlag;
     }

     public void setScrappedDate(Date scrappedDate){
         this.scrappedDate = scrappedDate;
     }

     public Date getScrappedDate(){
         return scrappedDate;
     }

     public void setScrappedDocument(String scrappedDocument){
         this.scrappedDocument = scrappedDocument;
     }

     public String getScrappedDocument(){
         return scrappedDocument;
     }

     public void setAftersaleSampleType(String aftersaleSampleType){
         this.aftersaleSampleType = aftersaleSampleType;
     }

     public String getAftersaleSampleType(){
         return aftersaleSampleType;
     }

     public void setDealer(String dealer){
         this.dealer = dealer;
     }

     public String getDealer(){
         return dealer;
     }

     public void setProductionDate(Date productionDate){
         this.productionDate = productionDate;
     }

     public Date getProductionDate(){
         return productionDate;
     }

     public void setReturnStatus(String returnStatus){
         this.returnStatus = returnStatus;
     }

     public String getReturnStatus(){
         return returnStatus;
     }

     public void setTestCode(Float testCode){
         this.testCode = testCode;
     }

     public Float getTestCode(){
         return testCode;
     }

     public void setSampleAttribute(String sampleAttribute){
         this.sampleAttribute = sampleAttribute;
     }

     public String getSampleAttribute(){
         return sampleAttribute;
     }

     public void setCompetingBrand(String competingBrand){
         this.competingBrand = competingBrand;
     }

     public String getCompetingBrand(){
         return competingBrand;
     }

     public void setAvailableStatus(String availableStatus){
         this.availableStatus = availableStatus;
     }

     public String getAvailableStatus(){
         return availableStatus;
     }

     public void setKeepBy(String keepBy){
         this.keepBy = keepBy;
     }

     public String getKeepBy(){
         return keepBy;
     }

     public void setTestBy(String testBy){
         this.testBy = testBy;
     }

     public String getTestBy(){
         return testBy;
     }

     }
