package com.hand.hcm.hcm_item.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;


@MultiLanguage
@ExtensionAttribute(disable = true)
@Table(name = "HCM_ITEM_B")
public class Item {

    private Float itemId;

    private Float plantId;

    @Length(max = 30)
    private String itemCode;

    @Length(max = 10)
    private String primaryUom;

    @Length(max = 100)
    private String designCode;

    @Length(max = 100)
    private String planCode;

    @Length(max = 10)
    private String itemIdentifyCode;

    @Length(max = 30)
    private String itemType;

    @Length(max = 30)
    private String makeBuyCode;

    @Length(max = 30)
    private String supplyType;

    @Length(max = 1)
    private String keyComponentFlag;

    @Length(max = 1)
    private String scheduleFlag;

    @Length(max = 1)
    private String makeToOrderFlag;

    @Length(max = 30)
    private String prodLineRule;

    @Length(max = 100)
    private String itemSize;

    private Float unitWeight;

    @Length(max = 1)
    private String enableFlag;

    @Length(max = 30)
    private String demandMergeTimeFence;

    @Length(max = 30)
    private String supplyMergeTimeFence;

    @Length(max = 30)
    private String safetyStockMethod;

    private Float safetyStockPeriod;

    private Float safetyStockValue;

    private Float maxStockQty;

    private Float minStockQty;

    @Length(max = 30)
    private String productCapacityTimeFence;

    private Float productCapacity;

    private Float economicSplitParameter;

    private Float minOrderQty;

    private Float fixedLotMultiple;

    private Float packQty;

    @Length(max = 30)
    private String sequenceLotControl;

    @Length(max = 30)
    private String expireControlFlag;

    private Float expireDays;

    @Length(max = 30)
    private String releaseConcurrentRule;

    private Float cid;

    private Float mrpPlanningCode;

    @Length(max = 30)
    private String autoSerialAlphaPrefix;

    @Length(max = 10)
    private String inventoryItemStatusCode;

    private Float maximumOrderQuantity;

    @Length(max = 150)
    private String globalAttribute1;

    @Length(max = 150)
    private String globalAttribute2;

    @Length(max = 150)
    private String globalAttribute3;

    @Length(max = 150)
    private String globalAttribute4;

    @Length(max = 150)
    private String globalAttribute5;

    @Length(max = 150)
    private String globalAttribute6;

    @Length(max = 150)
    private String globalAttribute7;

    @Length(max = 150)
    private String globalAttribute8;

    @Length(max = 150)
    private String globalAttribute9;

    @Length(max = 150)
    private String globalAttribute10;
    
    @Length(max = 30)
    private String purchaseUom;

    private Date syncDate;
    
    @Transient
    private String itemDescriptions;
    
    @Transient
    private String itemName;//物料描述
    
    @Transient
    private String plantName;//工厂描述
    
    @Transient
    private Float supplierId;//供应商ID
    
    @Transient
    private String plantCode;
    
    private String purchaseType;

    @Transient
    private String categoryCode;
    
    public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getPurchaseUom() {
		return purchaseUom;
	}

	public void setPurchaseUom(String purchaseUom) {
		this.purchaseUom = purchaseUom;
	}

	public String getPurchaseType() {
		return purchaseType;
	}

	public void setPurchaseType(String purchaseType) {
		this.purchaseType = purchaseType;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public String getPlantName() {
		return plantName;
	}

	public void setPlantName(String plantName) {
		this.plantName = plantName;
	}

	public String getItemDescriptions() {
        return itemDescriptions;
    }

    public void setItemDescriptions(String itemDescriptions) {
        this.itemDescriptions = itemDescriptions;
    }


    public void setItemId(Float itemId) {
        this.itemId = itemId;
    }

    public Float getItemId() {
        return itemId;
    }

    public void setPlantId(Float plantId) {
        this.plantId = plantId;
    }

    public Float getPlantId() {
        return plantId;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setPrimaryUom(String primaryUom) {
        this.primaryUom = primaryUom;
    }

    public String getPrimaryUom() {
        return primaryUom;
    }

    public void setDesignCode(String designCode) {
        this.designCode = designCode;
    }

    public String getDesignCode() {
        return designCode;
    }

    public void setPlanCode(String planCode) {
        this.planCode = planCode;
    }

    public String getPlanCode() {
        return planCode;
    }

    public void setItemIdentifyCode(String itemIdentifyCode) {
        this.itemIdentifyCode = itemIdentifyCode;
    }

    public String getItemIdentifyCode() {
        return itemIdentifyCode;
    }

    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    public String getItemType() {
        return itemType;
    }

    public void setMakeBuyCode(String makeBuyCode) {
        this.makeBuyCode = makeBuyCode;
    }

    public String getMakeBuyCode() {
        return makeBuyCode;
    }

    public void setSupplyType(String supplyType) {
        this.supplyType = supplyType;
    }

    public String getSupplyType() {
        return supplyType;
    }

    public void setKeyComponentFlag(String keyComponentFlag) {
        this.keyComponentFlag = keyComponentFlag;
    }

    public String getKeyComponentFlag() {
        return keyComponentFlag;
    }

    public void setScheduleFlag(String scheduleFlag) {
        this.scheduleFlag = scheduleFlag;
    }

    public String getScheduleFlag() {
        return scheduleFlag;
    }

    public void setMakeToOrderFlag(String makeToOrderFlag) {
        this.makeToOrderFlag = makeToOrderFlag;
    }

    public String getMakeToOrderFlag() {
        return makeToOrderFlag;
    }

    public void setProdLineRule(String prodLineRule) {
        this.prodLineRule = prodLineRule;
    }

    public String getProdLineRule() {
        return prodLineRule;
    }

    public void setItemSize(String itemSize) {
        this.itemSize = itemSize;
    }

    public String getItemSize() {
        return itemSize;
    }

    public void setUnitWeight(Float unitWeight) {
        this.unitWeight = unitWeight;
    }

    public Float getUnitWeight() {
        return unitWeight;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

    public void setDemandMergeTimeFence(String demandMergeTimeFence) {
        this.demandMergeTimeFence = demandMergeTimeFence;
    }

    public String getDemandMergeTimeFence() {
        return demandMergeTimeFence;
    }

    public void setSupplyMergeTimeFence(String supplyMergeTimeFence) {
        this.supplyMergeTimeFence = supplyMergeTimeFence;
    }

    public String getSupplyMergeTimeFence() {
        return supplyMergeTimeFence;
    }

    public void setSafetyStockMethod(String safetyStockMethod) {
        this.safetyStockMethod = safetyStockMethod;
    }

    public String getSafetyStockMethod() {
        return safetyStockMethod;
    }

    public void setSafetyStockPeriod(Float safetyStockPeriod) {
        this.safetyStockPeriod = safetyStockPeriod;
    }

    public Float getSafetyStockPeriod() {
        return safetyStockPeriod;
    }

    public void setSafetyStockValue(Float safetyStockValue) {
        this.safetyStockValue = safetyStockValue;
    }

    public Float getSafetyStockValue() {
        return safetyStockValue;
    }

    public void setMaxStockQty(Float maxStockQty) {
        this.maxStockQty = maxStockQty;
    }

    public Float getMaxStockQty() {
        return maxStockQty;
    }

    public void setMinStockQty(Float minStockQty) {
        this.minStockQty = minStockQty;
    }

    public Float getMinStockQty() {
        return minStockQty;
    }

    public void setProductCapacityTimeFence(String productCapacityTimeFence) {
        this.productCapacityTimeFence = productCapacityTimeFence;
    }

    public String getProductCapacityTimeFence() {
        return productCapacityTimeFence;
    }

    public void setProductCapacity(Float productCapacity) {
        this.productCapacity = productCapacity;
    }

    public Float getProductCapacity() {
        return productCapacity;
    }

    public void setEconomicSplitParameter(Float economicSplitParameter) {
        this.economicSplitParameter = economicSplitParameter;
    }

    public Float getEconomicSplitParameter() {
        return economicSplitParameter;
    }

    public void setMinOrderQty(Float minOrderQty) {
        this.minOrderQty = minOrderQty;
    }

    public Float getMinOrderQty() {
        return minOrderQty;
    }

    public void setFixedLotMultiple(Float fixedLotMultiple) {
        this.fixedLotMultiple = fixedLotMultiple;
    }

    public Float getFixedLotMultiple() {
        return fixedLotMultiple;
    }

    public void setPackQty(Float packQty) {
        this.packQty = packQty;
    }

    public Float getPackQty() {
        return packQty;
    }

    public void setSequenceLotControl(String sequenceLotControl) {
        this.sequenceLotControl = sequenceLotControl;
    }

    public String getSequenceLotControl() {
        return sequenceLotControl;
    }

    public void setExpireControlFlag(String expireControlFlag) {
        this.expireControlFlag = expireControlFlag;
    }

    public String getExpireControlFlag() {
        return expireControlFlag;
    }

    public void setExpireDays(Float expireDays) {
        this.expireDays = expireDays;
    }

    public Float getExpireDays() {
        return expireDays;
    }

    public void setReleaseConcurrentRule(String releaseConcurrentRule) {
        this.releaseConcurrentRule = releaseConcurrentRule;
    }

    public String getReleaseConcurrentRule() {
        return releaseConcurrentRule;
    }

    public void setCid(Float cid) {
        this.cid = cid;
    }

    public Float getCid() {
        return cid;
    }

    public void setMrpPlanningCode(Float mrpPlanningCode) {
        this.mrpPlanningCode = mrpPlanningCode;
    }

    public Float getMrpPlanningCode() {
        return mrpPlanningCode;
    }

    public void setAutoSerialAlphaPrefix(String autoSerialAlphaPrefix) {
        this.autoSerialAlphaPrefix = autoSerialAlphaPrefix;
    }

    public String getAutoSerialAlphaPrefix() {
        return autoSerialAlphaPrefix;
    }

    public void setInventoryItemStatusCode(String inventoryItemStatusCode) {
        this.inventoryItemStatusCode = inventoryItemStatusCode;
    }

    public String getInventoryItemStatusCode() {
        return inventoryItemStatusCode;
    }

    public void setMaximumOrderQuantity(Float maximumOrderQuantity) {
        this.maximumOrderQuantity = maximumOrderQuantity;
    }

    public Float getMaximumOrderQuantity() {
        return maximumOrderQuantity;
    }

    public void setGlobalAttribute1(String globalAttribute1) {
        this.globalAttribute1 = globalAttribute1;
    }

    public String getGlobalAttribute1() {
        return globalAttribute1;
    }

    public void setGlobalAttribute2(String globalAttribute2) {
        this.globalAttribute2 = globalAttribute2;
    }

    public String getGlobalAttribute2() {
        return globalAttribute2;
    }

    public void setGlobalAttribute3(String globalAttribute3) {
        this.globalAttribute3 = globalAttribute3;
    }

    public String getGlobalAttribute3() {
        return globalAttribute3;
    }

    public void setGlobalAttribute4(String globalAttribute4) {
        this.globalAttribute4 = globalAttribute4;
    }

    public String getGlobalAttribute4() {
        return globalAttribute4;
    }

    public void setGlobalAttribute5(String globalAttribute5) {
        this.globalAttribute5 = globalAttribute5;
    }

    public String getGlobalAttribute5() {
        return globalAttribute5;
    }

    public void setGlobalAttribute6(String globalAttribute6) {
        this.globalAttribute6 = globalAttribute6;
    }

    public String getGlobalAttribute6() {
        return globalAttribute6;
    }

    public void setGlobalAttribute7(String globalAttribute7) {
        this.globalAttribute7 = globalAttribute7;
    }

    public String getGlobalAttribute7() {
        return globalAttribute7;
    }

    public void setGlobalAttribute8(String globalAttribute8) {
        this.globalAttribute8 = globalAttribute8;
    }

    public String getGlobalAttribute8() {
        return globalAttribute8;
    }

    public void setGlobalAttribute9(String globalAttribute9) {
        this.globalAttribute9 = globalAttribute9;
    }

    public String getGlobalAttribute9() {
        return globalAttribute9;
    }

    public void setGlobalAttribute10(String globalAttribute10) {
        this.globalAttribute10 = globalAttribute10;
    }

    public String getGlobalAttribute10() {
        return globalAttribute10;
    }

    public void setSyncDate(Date syncDate) {
        this.syncDate = syncDate;
    }

    public Date getSyncDate() {
        return syncDate;
    }

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

}
