package com.hand.spc.ecr_main.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HPM_ECR_MAIN")
public class EcrMain extends BaseDTO {

     public static final String FIELD_ECRNO = "ecrno";
     public static final String FIELD_HAPPENDDATETIME = "happenddatetime";
     public static final String FIELD_HASSAMPLE = "hassample";
     public static final String FIELD_ISSUE = "issue";
     public static final String FIELD_ISSUESOURCENO = "issuesourceno";
     public static final String FIELD_MATNEEDCONTROL = "matneedcontrol";
     public static final String FIELD_RISKDEGREE = "riskdegree";
     public static final String FIELD_UFR = "ufr";
     public static final String FIELD_KID = "kid";
     
     
     @Length(max = 80)
     private String ecrno;

     private Date happenddatetime;

     @Length(max = 300)
     private String hassample;

     @Length(max = 300)
     private String issue;

     @Length(max = 60)
     private String issuesourceno;

     @Length(max = 10)
     private String matneedcontrol;

     @Length(max = 30)
     private String riskdegree;

     @Length(max = 10)
     private String ufr;

     @Id
     @GeneratedValue
     private Long kid;

     private String status;
     
     private String issueType;
     
     private Long processId	 ;
     private String processEmployeeCode;
     private String processStatus;
     private Date processStartDate;
     private Date processEndDate;

     private Date planFinishedDate;
     
     
     private String mainDuty;
     
     private String subDuty;
              

     private Date  actFinishedDate	;

     @Transient
     private String individuationSql;
     
     private String ecrType;
     
     // 是否做VTP
     private String vtpFlag;
     
     // 是否做QTP
     private String qtpFlag;
     
     
	public String getVtpFlag() {
		return vtpFlag;
	}

	public void setVtpFlag(String vtpFlag) {
		this.vtpFlag = vtpFlag;
	}

	public String getQtpFlag() {
		return qtpFlag;
	}

	public void setQtpFlag(String qtpFlag) {
		this.qtpFlag = qtpFlag;
	}

	public String getEcrType() {
		return ecrType;
	}

	public void setEcrType(String ecrType) {
		this.ecrType = ecrType;
	}

	public String getIndividuationSql() {
		return individuationSql;
	}

	public void setIndividuationSql(String individuationSql) {
		this.individuationSql = individuationSql;
	}

	public Date getActFinishedDate() {
		return actFinishedDate;
	}

	public void setActFinishedDate(Date actFinishedDate) {
		this.actFinishedDate = actFinishedDate;
	}

	public String getMainDuty() {
		return mainDuty;
	}

	public void setMainDuty(String mainDuty) {
		this.mainDuty = mainDuty;
	}

	public String getSubDuty() {
		return subDuty;
	}

	public void setSubDuty(String subDuty) {
		this.subDuty = subDuty;
	}

	public Date getPlanFinishedDate() {
		return planFinishedDate;
	}

	public void setPlanFinishedDate(Date planFinishedDate) {
		this.planFinishedDate = planFinishedDate;
	}

	public Long getProcessId() {
		return processId;
	}

	public void setProcessId(Long processId) {
		this.processId = processId;
	}

	public String getProcessEmployeeCode() {
		return processEmployeeCode;
	}

	public void setProcessEmployeeCode(String processEmployeeCode) {
		this.processEmployeeCode = processEmployeeCode;
	}

	public String getProcessStatus() {
		return processStatus;
	}

	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	public Date getProcessStartDate() {
		return processStartDate;
	}

	public void setProcessStartDate(Date processStartDate) {
		this.processStartDate = processStartDate;
	}

	public Date getProcessEndDate() {
		return processEndDate;
	}

	public void setProcessEndDate(Date processEndDate) {
		this.processEndDate = processEndDate;
	}

	public String getIssueType() {
		return issueType;
	}

	public void setIssueType(String issueType) {
		this.issueType = issueType;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public void setEcrno(String ecrno){
         this.ecrno = ecrno;
     }

     public String getEcrno(){
         return ecrno;
     }

     public void setHappenddatetime(Date happenddatetime){
         this.happenddatetime = happenddatetime;
     }

     public Date getHappenddatetime(){
         return happenddatetime;
     }

     public void setHassample(String hassample){
         this.hassample = hassample;
     }

     public String getHassample(){
         return hassample;
     }

     public void setIssue(String issue){
         this.issue = issue;
     }

     public String getIssue(){
         return issue;
     }

     public void setIssuesourceno(String issuesourceno){
         this.issuesourceno = issuesourceno;
     }

     public String getIssuesourceno(){
         return issuesourceno;
     }

     public void setMatneedcontrol(String matneedcontrol){
         this.matneedcontrol = matneedcontrol;
     }

     public String getMatneedcontrol(){
         return matneedcontrol;
     }

     public void setRiskdegree(String riskdegree){
         this.riskdegree = riskdegree;
     }

     public String getRiskdegree(){
         return riskdegree;
     }

     public void setUfr(String ufr){
         this.ufr = ufr;
     }

     public String getUfr(){
         return ufr;
     }

     public void setKid(Long kid){
         this.kid = kid;
     }

     public Long getKid(){
         return kid;
     }

     }
