package com.hand.spc.ecr_main.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HPM_ECR_SOLUTION_SKU")
public class EcrSolutionSku extends BaseDTO {

     public static final String FIELD_ITEM_SKU_KID = "itemSkuKid";
     public static final String FIELD_SKU_ID = "skuId";
     public static final String FIELD_PRODUCT_TYPE = "productType";
     public static final String FIELD_PRODUCTS = "products";
     public static final String FIELD_WORK_COST = "workCost";
     public static final String FIELD_ECRNO = "ecrno";
     public static final String FIELD_YEAR_PLAN_QTY = "yearPlanQty";
     public static final String FIELD_BOM_USE = "bomUse";
     public static final String FIELD_ECR_USE = "ecrUse";
     public static final String FIELD_SUB_ITEM_FLAG = "subItemFlag";
     public static final String FIELD_SUB_ITEM = "subItem";
     public static final String FIELD_FIRST_RECIEVE_TIME = "firstRecieveTime";
     public static final String FIELD_FIRST_USING_TIME = "firstUsingTime";
     public static final String FIELD_ITEM_ID = "itemId";
     public static final String FIELD_ITEM_CHANGE_TYPE = "itemChangeType";


     @Id
     @GeneratedValue
     private Long itemSkuKid;

     private Long skuId;

     @Length(max = 80)
     private String productType;

     @Length(max = 80)
     private String products;

     private Long workCost;

     @Length(max = 80)
     private String ecrno;

     private Float yearPlanQty;

     private Float bomUse;

     private Float ecrUse;

     @Length(max = 10)
     private String subItemFlag;

     @Length(max = 30)
     private String subItem;

     private Date firstRecieveTime;

     private Date firstUsingTime;

     private Long itemId;

     @Length(max = 10)
     private String itemChangeType;
     private String skuCode;     
     
     private String skuDescription;
     
     private Float stdCost;
     private Float stdPriceUnit;
     private String stdCostCurrency	;
     private Float actPriceUnit	;
     private Float actCost	;
     private String  actCostCurrency	;

     

     
  
 	public Float getStdCost() {
		return stdCost;
	}

	public void setStdCost(Float stdCost) {
		this.stdCost = stdCost;
	}

	public Float getStdPriceUnit() {
		return stdPriceUnit;
	}

	public void setStdPriceUnit(Float stdPriceUnit) {
		this.stdPriceUnit = stdPriceUnit;
	}

	public String getStdCostCurrency() {
 		return stdCostCurrency;
 	}

 	public void setStdCostCurrency(String stdCostCurrency) {
 		this.stdCostCurrency = stdCostCurrency;
 	}

 	 

 	public Float getActPriceUnit() {
		return actPriceUnit;
	}

	public void setActPriceUnit(Float actPriceUnit) {
		this.actPriceUnit = actPriceUnit;
	}

	public Float getActCost() {
		return actCost;
	}

	public void setActCost(Float actCost) {
		this.actCost = actCost;
	}

	public String getActCostCurrency() {
 		return actCostCurrency;
 	}

 	public void setActCostCurrency(String actCostCurrency) {
 		this.actCostCurrency = actCostCurrency;
 	}

  
 	
     public String getSkuCode() {
		return skuCode;
	}

	public void setSkuCode(String skuCode) {
		this.skuCode = skuCode;
	}

	public String getSkuDescription() {
		return skuDescription;
	}

	public void setSkuDescription(String skuDescription) {
		this.skuDescription = skuDescription;
	}

	public void setItemSkuKid(Long itemSkuKid){
         this.itemSkuKid = itemSkuKid;
     }

     public Long getItemSkuKid(){
         return itemSkuKid;
     }

     public void setSkuId(Long skuId){
         this.skuId = skuId;
     }

     public Long getSkuId(){
         return skuId;
     }

     public void setProductType(String productType){
         this.productType = productType;
     }

     public String getProductType(){
         return productType;
     }

     public void setProducts(String products){
         this.products = products;
     }

     public String getProducts(){
         return products;
     }

     public void setWorkCost(Long workCost){
         this.workCost = workCost;
     }

     public Long getWorkCost(){
         return workCost;
     }

     public void setEcrno(String ecrno){
         this.ecrno = ecrno;
     }

     public String getEcrno(){
         return ecrno;
     }

     public void setYearPlanQty(Float yearPlanQty){
         this.yearPlanQty = yearPlanQty;
     }

     public Float getYearPlanQty(){
         return yearPlanQty;
     }

     

     public Float getBomUse() {
		return bomUse;
	}

	public void setBomUse(Float bomUse) {
		this.bomUse = bomUse;
	}

	public Float getEcrUse() {
		return ecrUse;
	}

	public void setEcrUse(Float ecrUse) {
		this.ecrUse = ecrUse;
	}

	public void setSubItemFlag(String subItemFlag){
         this.subItemFlag = subItemFlag;
     }

     public String getSubItemFlag(){
         return subItemFlag;
     }

     public void setSubItem(String subItem){
         this.subItem = subItem;
     }

     public String getSubItem(){
         return subItem;
     }

     public void setFirstRecieveTime(Date firstRecieveTime){
         this.firstRecieveTime = firstRecieveTime;
     }

     public Date getFirstRecieveTime(){
         return firstRecieveTime;
     }

     public void setFirstUsingTime(Date firstUsingTime){
         this.firstUsingTime = firstUsingTime;
     }

     public Date getFirstUsingTime(){
         return firstUsingTime;
     }

     public void setItemId(Long itemId){
         this.itemId = itemId;
     }

     public Long getItemId(){
         return itemId;
     }

     public void setItemChangeType(String itemChangeType){
         this.itemChangeType = itemChangeType;
     }

     public String getItemChangeType(){
         return itemChangeType;
     }

     }
