package com.hand.hcs.hcs_barcode.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HCS_SMALL_BARCODE")
public class SmallBarcode extends BaseDTO {

	@Id
	@GeneratedValue
	private Float sbarcodeId;

	@Length(max = 100)
	private String sbarcode;// 小箱条码

	@Length(max = 30)
	private String sbarcodeType;

	@Length(max = 10)
	private String status;// 状态

	private Float plantId;// 工厂 关联工厂表HCM_PLANT取code

	@Transient
	private String plantCode;

	private Float itemId;// 物料编码 关联HCM_ITEM表取code

	@Transient
	private String itemCode;

	@Transient
	private String itemDesc; // 物料描述 关联HCM_ITEM表
	@Length(max = 30)
	private String itemVersion;// 物料版本

	private Float quantity; // 数量

	@Length(max = 10)
	private String uom; // 单位
	private Date productionTime;// 生产日期

	private Date creationDate;// 创建日期

	@Length(max = 100)
	private String lotCode;// 批次

	@Length(max = 30)
	private String packingSize;// 规格

	@Length(max = 30)
	private String packingLevel;// 包装方式

	@Length(max = 240)
	private String remarks;// 备注

	@Length(max = 1)
	private String packingFlag;// 是否捆包

	@Transient
	private Float obarcodeId;

	@Transient
	private String obarcode; // 外箱条码 关联HCS_SMALL_BARCODE_CONTROL表 取code

	private Float printTime;// 打印次数

	@Length(max = 1)
	private String enableFlag;// 有效性

	@Length(max = 10)
	private String sqcSatus;
	
	@Length(max = 10)
	private String caseNumber;

	@Length(max = 30)
	private String productionRegion;
	
	@Length(max = 30)
	private String productionEquipment;
	
	@Length(max = 240)
	private String barcodeContent;
	
	@Length(max = 30)
	private String poNumberPrint;
	
	@Transient
	private String ticketNumber;// 送货单号 HCS_SMALL_BARCODE_CONTROL关联HCS_DELIVERY_TICKET_H表 取ticket_number
	@Transient
	private String ticketLineId;// 送货单行号 HCS_SMALL_BARCODE_CONTROL关联HCS_DELIVERY_TICKET_L表 取ticket_line_id
	@Transient
	private String ticketLineNum;
	@Transient
	private String poNumber;// 采购订单号 HCS_SMALL_BARCODE_CONTROL关联HCS_PO_HEADERS表 取po_number
	@Transient
	private String shipmentNum;// 发运号 HCS_SMALL_BARCODE_CONTROL关联HCS_PO_LINE_LOCATIONS表 取shipment_num
	@Transient
	private String supplierCode;// 供应商编码 HCS_SMALL_BARCODE_CONTROL关联HCS_SUPPLIERS表 取supplier_code
	@Transient
	private String supplierName;// 供应商 HCS_SMALL_BARCODE_CONTROL关联HCS_SUPPLIERS表 取supplier_name
	@Transient
	private String supplierSite;// 供应商地点 HCS_SMALL_BARCODE_CONTROL关联HCS_SUPPLIER_SITE表 取description

	@Length(max = 30)
	private String spreading;

	@Length(max = 1)
	private String freezeFlag;

	@Length(max = 1)
	private String freeFlag;

	@Transient
	private Float supplierId;
	@Transient
	private Float suppliersSiteId;
	@Transient
	private Float ticketId;
	@Transient
	private Float poHeaderId;
	@Transient
	private Float poLineId;
	@Transient
	private Float lineLocationId;
	@Transient
	private Float refundOrderId;
	@Transient
	private Float bigId;

	@Transient
	private String creationStartTime;// 创建日期从

	@Transient
	private String creationEndTime;// 创建日期至

	@Transient
	private String productionStartTime;// 生产日期从

	@Transient
	private String productionEndTime;// 生产日期至

	@Transient
	private String itemName;// 物料名称

	@Transient
	private String plantName;// 工厂
	@Transient
	private String bindFlag;// 绑定标识

	@Transient
	private Long codeSum;// 条码张数

	@Transient
	private String obarcodeNum;//容器序列
	@Transient
	private String obarcodeType;
	@Transient
	private String purchaseGroup;//采购组
	
	
	public String getPurchaseGroup() {
		return purchaseGroup;
	}

	public void setPurchaseGroup(String purchaseGroup) {
		this.purchaseGroup = purchaseGroup;
	}

	public String getObarcodeType() {
		return obarcodeType;
	}

	public void setObarcodeType(String obarcodeType) {
		this.obarcodeType = obarcodeType;
	}

	public String getObarcodeNum() {
		return obarcodeNum;
	}

	public void setObarcodeNum(String obarcodeNum) {
		this.obarcodeNum = obarcodeNum;
	}

	public String getCaseNumber() {
		return caseNumber;
	}

	public void setCaseNumber(String caseNumber) {
		this.caseNumber = caseNumber;
	}

	public String getProductionRegion() {
		return productionRegion;
	}

	public void setProductionRegion(String productionRegion) {
		this.productionRegion = productionRegion;
	}

	public String getProductionEquipment() {
		return productionEquipment;
	}

	public void setProductionEquipment(String productionEquipment) {
		this.productionEquipment = productionEquipment;
	}

	public String getBarcodeContent() {
		return barcodeContent;
	}

	public void setBarcodeContent(String barcodeContent) {
		this.barcodeContent = barcodeContent;
	}

	public String getPoNumberPrint() {
		return poNumberPrint;
	}

	public void setPoNumberPrint(String poNumberPrint) {
		this.poNumberPrint = poNumberPrint;
	}

	public String getTicketLineNum() {
		return ticketLineNum;
	}

	public void setTicketLineNum(String ticketLineNum) {
		this.ticketLineNum = ticketLineNum;
	}

	public Float getSbarcodeId() {
		return sbarcodeId;
	}

	public Float sbarcodeId() {
		return sbarcodeId;
	}

	public void setSbarcodeId(Float sbarcodeId) {
		this.sbarcodeId = sbarcodeId;
	}

	public String getSbarcode() {
		return sbarcode;
	}

	public void setSbarcode(String sbarcode) {
		this.sbarcode = sbarcode;
	}

	public String getSbarcodeType() {
		return sbarcodeType;
	}

	public void setSbarcodeType(String sbarcodeType) {
		this.sbarcodeType = sbarcodeType;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public Float getItemId() {
		return itemId;
	}

	public void setItemId(Float itemId) {
		this.itemId = itemId;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemDesc() {
		return itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	

	public String getItemVersion() {
		return itemVersion;
	}

	public void setItemVersion(String itemVersion) {
		this.itemVersion = itemVersion;
	}

	public Float getQuantity() {
		return quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	public String getUom() {
		return uom;
	}

	public void setUom(String uom) {
		this.uom = uom;
	}

	public Date getProductionTime() {
		return productionTime;
	}

	public void setProductionTime(Date productionTime) {
		this.productionTime = productionTime;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getLotCode() {
		return lotCode;
	}

	public void setLotCode(String lotCode) {
		this.lotCode = lotCode;
	}

	public String getPackingSize() {
		return packingSize;
	}

	public void setPackingSize(String packingSize) {
		this.packingSize = packingSize;
	}

	public String getPackingLevel() {
		return packingLevel;
	}

	public void setPackingLevel(String packingLevel) {
		this.packingLevel = packingLevel;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getPackingFlag() {
		return packingFlag;
	}

	public void setPackingFlag(String packingFlag) {
		this.packingFlag = packingFlag;
	}

	public Float getObarcodeId() {
		return obarcodeId;
	}

	public void setObarcodeId(Float obarcodeId) {
		this.obarcodeId = obarcodeId;
	}

	public String getObarcode() {
		return obarcode;
	}

	public void setObarcode(String obarcode) {
		this.obarcode = obarcode;
	}

	public Float getPrintTime() {
		return printTime;
	}

	public void setPrintTime(Float printTime) {
		this.printTime = printTime;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getSqcSatus() {
		return sqcSatus;
	}

	public void setSqcSatus(String sqcSatus) {
		this.sqcSatus = sqcSatus;
	}

	public String getTicketNumber() {
		return ticketNumber;
	}

	public void setTicketNumber(String ticketNumber) {
		this.ticketNumber = ticketNumber;
	}

	public String getTicketLineId() {
		return ticketLineId;
	}

	public void setTicketLineId(String ticketLineId) {
		this.ticketLineId = ticketLineId;
	}

	public String getPoNumber() {
		return poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	public String getShipmentNum() {
		return shipmentNum;
	}

	public void setShipmentNum(String shipmentNum) {
		this.shipmentNum = shipmentNum;
	}

	public String getSupplierCode() {
		return supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getSupplierSite() {
		return supplierSite;
	}

	public void setSupplierSite(String supplierSite) {
		this.supplierSite = supplierSite;
	}

	public String getSpreading() {
		return spreading;
	}

	public void setSpreading(String spreading) {
		this.spreading = spreading;
	}

	public String getFreezeFlag() {
		return freezeFlag;
	}

	public void setFreezeFlag(String freezeFlag) {
		this.freezeFlag = freezeFlag;
	}

	public String getFreeFlag() {
		return freeFlag;
	}

	public void setFreeFlag(String freeFlag) {
		this.freeFlag = freeFlag;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getSuppliersSiteId() {
		return suppliersSiteId;
	}

	public void setSuppliersSiteId(Float suppliersSiteId) {
		this.suppliersSiteId = suppliersSiteId;
	}

	public Float getTicketId() {
		return ticketId;
	}

	public void setTicketId(Float ticketId) {
		this.ticketId = ticketId;
	}

	public Float getPoHeaderId() {
		return poHeaderId;
	}

	public void setPoHeaderId(Float poHeaderId) {
		this.poHeaderId = poHeaderId;
	}

	public Float getPoLineId() {
		return poLineId;
	}

	public void setPoLineId(Float poLineId) {
		this.poLineId = poLineId;
	}

	public Float getLineLocationId() {
		return lineLocationId;
	}

	public void setLineLocationId(Float lineLocationId) {
		this.lineLocationId = lineLocationId;
	}

	public Float getRefundOrderId() {
		return refundOrderId;
	}

	public void setRefundOrderId(Float refundOrderId) {
		this.refundOrderId = refundOrderId;
	}

	public Float getBigId() {
		return bigId;
	}

	public void setBigId(Float bigId) {
		this.bigId = bigId;
	}

	public String getCreationStartTime() {
		return creationStartTime;
	}

	public void setCreationStartTime(String creationStartTime) {
		this.creationStartTime = creationStartTime;
	}

	public String getCreationEndTime() {
		return creationEndTime;
	}

	public void setCreationEndTime(String creationEndTime) {
		this.creationEndTime = creationEndTime;
	}

	public String getProductionStartTime() {
		return productionStartTime;
	}

	public void setProductionStartTime(String productionStartTime) {
		this.productionStartTime = productionStartTime;
	}

	public String getProductionEndTime() {
		return productionEndTime;
	}

	public void setProductionEndTime(String productionEndTime) {
		this.productionEndTime = productionEndTime;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getPlantName() {
		return plantName;
	}

	public void setPlantName(String plantName) {
		this.plantName = plantName;
	}

	public String getBindFlag() {
		return bindFlag;
	}

	public void setBindFlag(String bindFlag) {
		this.bindFlag = bindFlag;
	}

	public Long getCodeSum() {
		return codeSum;
	}

	public void setCodeSum(Long codeSum) {
		this.codeSum = codeSum;
	}

}
