package com.hand.spc.hqm_d_order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "hqm_8d_order")
public class EightDOrder extends BaseDTO {

     public static final String FIELD_ORDER_ID = "orderId";
     public static final String FIELD_PLANT_ID = "plantId";
     public static final String FIELD_ORDER_THEME = "orderTheme";
     public static final String FIELD_ORDER_CODE = "orderCode";
     public static final String FIELD_ORDER_STATUS = "orderStatus";
     public static final String FIELD_ORDER_PROCESS = "orderProcess";
     public static final String FIELD_EXPECTED_COMPLETE_TIME = "expectedCompleteTime";
     public static final String FIELD_SOURCE_TYPE = "sourceType";
     public static final String FIELD_SOURCE_ORDER = "sourceOrder";


     @Id
     @GeneratedValue
     private Long orderId;

     private Long plantId;

     @Length(max = 200)
     private String orderTheme;

     @Length(max = 50)
     private String orderCode;

     @Length(max = 30)
     private String orderStatus;

     @Length(max = 30)
     private String orderProcess;

     private Date expectedCompleteTime;

     @Length(max = 30)
     private String sourceType;

     @Length(max = 300)
     private String sourceOrder;

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getPlantId() {
        return plantId;
    }

    public void setPlantId(Long plantId) {
        this.plantId = plantId;
    }

    public void setOrderTheme(String orderTheme){
         this.orderTheme = orderTheme;
     }

     public String getOrderTheme(){
         return orderTheme;
     }

     public void setOrderCode(String orderCode){
         this.orderCode = orderCode;
     }

     public String getOrderCode(){
         return orderCode;
     }

     public void setOrderStatus(String orderStatus){
         this.orderStatus = orderStatus;
     }

     public String getOrderStatus(){
         return orderStatus;
     }

     public void setOrderProcess(String orderProcess){
         this.orderProcess = orderProcess;
     }

     public String getOrderProcess(){
         return orderProcess;
     }

     public void setExpectedCompleteTime(Date expectedCompleteTime){
         this.expectedCompleteTime = expectedCompleteTime;
     }

     public Date getExpectedCompleteTime(){
         return expectedCompleteTime;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setSourceOrder(String sourceOrder){
         this.sourceOrder = sourceOrder;
     }

     public String getSourceOrder(){
         return sourceOrder;
     }

     }
