package com.hand.hqm.hqm_iqc_inspection_template_l_his.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_IQC_INSPECTION_TEMPLATE_L_HIS")
public class IqcInspectionTemplateLHis extends BaseDTO {

     @Id
     @GeneratedValue
     private Float eventId;
     
	private Float eventHId;

     private Long eventBy;

     private Date eventTime;

     private Float lineId;

     private Float headerId;

     @Length(max = 100)
     private String inspectionAttribute;

     private Float orderCode;

     @Length(max = 30)
     private String enableType;

     @Length(max = 30)
     private String sampleProcedureType;

     @Length(max = 30)
     private String inspectionLevels;

     @Length(max = 30)
     private String qualityCharacterGrade;

     @Length(max = 30)
     private String acceptanceQualityLimit;

     @Length(max = 30)
     private String standardType;

     @Length(max = 200)
     private String textStandrad;

     @Length(max = 30)
     private String standradFrom;

     @Length(max = 30)
     private String standradTo;

     @Length(max = 30)
     private String standradUom;

     @Length(max = 30)
     private String frequencyType;

     private Float frequency;

     @Length(max = 30)
     private String inspectionTool;

     @Length(max = 200)
     private String remark;

     private Date enableTime;

     private Date disableTime;

     @Length(max = 30)
     private String sourceType;

     private Float historyNum;

     @Length(max = 1)
     private String isSync;

     @Length(max = 30)
     private String fillInType;

     @Length(max = 1)
     private String enableFlag;

     private Float precision;

     @Length(max = 30)
     private String inspectionMethod;

     private Float sampleWayId;

     @Length(max = 30)
     private String samplePlan;
     
     private String attributeType;
     
     private Float attributeId;


     public String getAttributeType() {
		return attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	public Float getAttributeId() {
		return attributeId;
	}

	public void setAttributeId(Float attributeId) {
		this.attributeId = attributeId;
	}

	public Float getEventHId() {
		return eventHId;
	}

	public void setEventHId(Float eventHId) {
		this.eventHId = eventHId;
	}

	public void setEventId(Float eventId){
         this.eventId = eventId;
     }

     public Float getEventId(){
         return eventId;
     }

     public void setEventBy(Long eventBy){
         this.eventBy = eventBy;
     }

     public Long getEventBy(){
         return eventBy;
     }

     public void setEventTime(Date eventTime){
         this.eventTime = eventTime;
     }

     public Date getEventTime(){
         return eventTime;
     }

     public void setLineId(Float lineId){
         this.lineId = lineId;
     }

     public Float getLineId(){
         return lineId;
     }

     public void setHeaderId(Float headerId){
         this.headerId = headerId;
     }

     public Float getHeaderId(){
         return headerId;
     }

     public void setInspectionAttribute(String inspectionAttribute){
         this.inspectionAttribute = inspectionAttribute;
     }

     public String getInspectionAttribute(){
         return inspectionAttribute;
     }

     public void setOrderCode(Float orderCode){
         this.orderCode = orderCode;
     }

     public Float getOrderCode(){
         return orderCode;
     }

     public void setEnableType(String enableType){
         this.enableType = enableType;
     }

     public String getEnableType(){
         return enableType;
     }

     public void setSampleProcedureType(String sampleProcedureType){
         this.sampleProcedureType = sampleProcedureType;
     }

     public String getSampleProcedureType(){
         return sampleProcedureType;
     }

     public void setInspectionLevels(String inspectionLevels){
         this.inspectionLevels = inspectionLevels;
     }

     public String getInspectionLevels(){
         return inspectionLevels;
     }

     public void setQualityCharacterGrade(String qualityCharacterGrade){
         this.qualityCharacterGrade = qualityCharacterGrade;
     }

     public String getQualityCharacterGrade(){
         return qualityCharacterGrade;
     }

     public void setAcceptanceQualityLimit(String acceptanceQualityLimit){
         this.acceptanceQualityLimit = acceptanceQualityLimit;
     }

     public String getAcceptanceQualityLimit(){
         return acceptanceQualityLimit;
     }

     public void setStandardType(String standardType){
         this.standardType = standardType;
     }

     public String getStandardType(){
         return standardType;
     }

     public void setTextStandrad(String textStandrad){
         this.textStandrad = textStandrad;
     }

     public String getTextStandrad(){
         return textStandrad;
     }

     public void setStandradFrom(String standradFrom){
         this.standradFrom = standradFrom;
     }

     public String getStandradFrom(){
         return standradFrom;
     }

     public void setStandradTo(String standradTo){
         this.standradTo = standradTo;
     }

     public String getStandradTo(){
         return standradTo;
     }

     public void setStandradUom(String standradUom){
         this.standradUom = standradUom;
     }

     public String getStandradUom(){
         return standradUom;
     }

     public void setFrequencyType(String frequencyType){
         this.frequencyType = frequencyType;
     }

     public String getFrequencyType(){
         return frequencyType;
     }

     public void setFrequency(Float frequency){
         this.frequency = frequency;
     }

     public Float getFrequency(){
         return frequency;
     }

     public void setInspectionTool(String inspectionTool){
         this.inspectionTool = inspectionTool;
     }

     public String getInspectionTool(){
         return inspectionTool;
     }

     public void setRemark(String remark){
         this.remark = remark;
     }

     public String getRemark(){
         return remark;
     }

     public void setEnableTime(Date enableTime){
         this.enableTime = enableTime;
     }

     public Date getEnableTime(){
         return enableTime;
     }

     public void setDisableTime(Date disableTime){
         this.disableTime = disableTime;
     }

     public Date getDisableTime(){
         return disableTime;
     }

     public void setSourceType(String sourceType){
         this.sourceType = sourceType;
     }

     public String getSourceType(){
         return sourceType;
     }

     public void setHistoryNum(Float historyNum){
         this.historyNum = historyNum;
     }

     public Float getHistoryNum(){
         return historyNum;
     }

     public void setIsSync(String isSync){
         this.isSync = isSync;
     }

     public String getIsSync(){
         return isSync;
     }

     public void setFillInType(String fillInType){
         this.fillInType = fillInType;
     }

     public String getFillInType(){
         return fillInType;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setPrecision(Float precision){
         this.precision = precision;
     }

     public Float getPrecision(){
         return precision;
     }

     public void setInspectionMethod(String inspectionMethod){
         this.inspectionMethod = inspectionMethod;
     }

     public String getInspectionMethod(){
         return inspectionMethod;
     }

     public void setSampleWayId(Float sampleWayId){
         this.sampleWayId = sampleWayId;
     }

     public Float getSampleWayId(){
         return sampleWayId;
     }

     public void setSamplePlan(String samplePlan){
         this.samplePlan = samplePlan;
     }

     public String getSamplePlan(){
         return samplePlan;
     }

     }
