package com.hand.sys.sys_if_invoke_outbound.dto;

import java.util.Date;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "SYS_IF_INVOKE_OUTBOUND")
public class IfInvokeOutbound extends BaseDTO {

	@Id
	@GeneratedValue
	private Float outboundId;

	@Length(max = 255)
	private String interfaceName;

	@Length(max = 2000)
	private String interfaceUrl;

	private Date requestTime;

	@Length(max = 4000)
	private String requestParameter;

	@Length(max = 10)
	private String requestStatus;

	@Length(max = 4000)
	private String responseContent;

	private Date responseTime;

	@Length(max = 30)
	private String responseCode;

	@Length(max = 4000)
	private String stacktrace;

	@Length(max = 2)
	private String outType;
	
	public String getOutType() {
		return outType;
	}

	public void setOutType(String outType) {
		this.outType = outType;
	}

	public void setOutboundId(Float outboundId) {
		this.outboundId = outboundId;
	}

	public Float getOutboundId() {
		return outboundId;
	}

	public void setInterfaceName(String interfaceName) {
		this.interfaceName = interfaceName;
	}

	public String getInterfaceName() {
		return interfaceName;
	}

	public void setInterfaceUrl(String interfaceUrl) {
		this.interfaceUrl = interfaceUrl;
	}

	public String getInterfaceUrl() {
		return interfaceUrl;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public Date getRequestTime() {
		return requestTime;
	}

	public void setRequestParameter(String requestParameter) {
		this.requestParameter = requestParameter;
	}

	public String getRequestParameter() {
		return requestParameter;
	}

	public void setRequestStatus(String requestStatus) {
		this.requestStatus = requestStatus;
	}

	public String getRequestStatus() {
		return requestStatus;
	}

	public void setResponseContent(String responseContent) {
		this.responseContent = responseContent;
	}

	public String getResponseContent() {
		return responseContent;
	}

	public void setResponseTime(Date responseTime) {
		this.responseTime = responseTime;
	}

	public Date getResponseTime() {
		return responseTime;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	public String getResponseCode() {
		return responseCode;
	}

	public void setStacktrace(String stacktrace) {
		this.stacktrace = stacktrace;
	}

	public String getStacktrace() {
		return stacktrace;
	}

}
