package com.hand.hqm.hqm_fqc_barcode.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_FQC_BARCODE")
public class FqcBarcode extends BaseDTO {

     public static final String FIELD_KID = "kid";
     public static final String FIELD_ORDER_NUM = "orderNum";
     public static final String FIELD_ITEM_ID = "itemId";
     public static final String FIELD_SERIAL_NUMBER = "serialNumber";
     public static final String FIELD_IS_SAMPLE = "isSample";


     @Id
     @GeneratedValue
     private Float kid;

     @Length(max = 50)
     private String orderNum;

     private Float itemId;

     @Length(max = 50)
     private String serialNumber;

     @Length(max = 50)
     private String isSample;


     public void setKid(Float kid){
         this.kid = kid;
     }

     public Float getKid(){
         return kid;
     }

     public void setOrderNum(String orderNum){
         this.orderNum = orderNum;
     }

     public String getOrderNum(){
         return orderNum;
     }

     public void setItemId(Float itemId){
         this.itemId = itemId;
     }

     public Float getItemId(){
         return itemId;
     }

     public void setSerialNumber(String serialNumber){
         this.serialNumber = serialNumber;
     }

     public String getSerialNumber(){
         return serialNumber;
     }

     public void setIsSample(String isSample){
         this.isSample = isSample;
     }

     public String getIsSample(){
         return isSample;
     }

     }
