package com.hand.hqm.hqm_pqc_calendar_b.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.core.annotation.MultiLanguage;

@ExtensionAttribute(disable=true)
@Table(name = "HQM_PQC_CALENDAR_B")
public class PqcCalendarB extends BaseDTO {

     private Float calendarId;

     @Id
     @GeneratedValue
     private Float calendarBId;

     private Float safetyPerson;

     @Length(max = 10)
     private String safetyStatus;


     public void setCalendarId(Float calendarId){
         this.calendarId = calendarId;
     }

     public Float getCalendarId(){
         return calendarId;
     }

     public void setCalendarBId(Float calendarBId){
         this.calendarBId = calendarBId;
     }

     public Float getCalendarBId(){
         return calendarBId;
     }

     public void setSafetyPerson(Float safetyPerson){
         this.safetyPerson = safetyPerson;
     }

     public Float getSafetyPerson(){
         return safetyPerson;
     }

     public void setSafetyStatus(String safetyStatus){
         this.safetyStatus = safetyStatus;
     }

     public String getSafetyStatus(){
         return safetyStatus;
     }

     }
