package com.hand.npi.npi_route.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "NPI_TECHNOLOGY_WP_ACTION_EQUIP_DETAIL")
public class TechnologyWpActionEquipDetail extends BaseDTO {
	//工艺动作-工装设备夹具表
	public static final String FIELD_ID = "id";
	public static final String FIELD_WP_ACTION_ID = "wpActionId";
	public static final String FIELD_ACTION_ID = "actionId";
	public static final String FIELD_EQUIPMENT_CODE = "equipmentCode";
	public static final String FIELD_EQUIPMENT_NAME = "equipmentName";
	public static final String FIELD_STATUS = "status";
	public static final String FIELD_QTY = "qty";
	public static final String FIELD_ACTION_TYPE = "actionType";

	@Id
	@GeneratedValue
	private Float actionEquipId;

	/**
	 * 工艺动作ID
	 */
	private Float wpActionId;

	/**
	 * 动作ID(包括标准和辅助)
	 */
	private Float actionId;
	
	/**
	 * 动作名称(包括标准和辅助)
	 */
	@Transient
	private String actionName;

	/**
	 * 工装/工具/设备编码
	 */
	@Length(max = 50)
	private String equipmentCode;

	/**
	 * 工装/工具/设备名称
	 */
	@Length(max = 240)
	private String equipmentName;

	/**
	 * 状态
	 */
	@Length(max = 10)
	private String status;

	/**
	 * 数量
	 */
	private Float qty;

	/**
	 * 动作类型 --aux辅助 str标准
	 */
	@Length(max = 10)
	private String actionType;

	

	public Float getActionEquipId() {
		return actionEquipId;
	}

	public void setActionEquipId(Float actionEquipId) {
		this.actionEquipId = actionEquipId;
	}

	public void setWpActionId(Float wpActionId) {
		this.wpActionId = wpActionId;
	}

	public Float getWpActionId() {
		return wpActionId;
	}

	public void setActionId(Float actionId) {
		this.actionId = actionId;
	}

	public Float getActionId() {
		return actionId;
	}

	public void setEquipmentCode(String equipmentCode) {
		this.equipmentCode = equipmentCode;
	}

	public String getEquipmentCode() {
		return equipmentCode;
	}

	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName;
	}

	public String getEquipmentName() {
		return equipmentName;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

	public void setQty(Float qty) {
		this.qty = qty;
	}

	public Float getQty() {
		return qty;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getActionType() {
		return actionType;
	}

	public String getActionName() {
		return actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	

}
