package com.hand.npi.npi_route.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

@ExtensionAttribute(disable = true)
@Table(name = "NPI_TECHNOLOGY_ROUTE")
public class TechnologyRoute extends BaseDTO {
	//工艺路径信息表
	public static final String FIELD_ROUTE_ID = "routeId";
	public static final String FIELD_ROUTE_NUMBER = "routeNumber";
	public static final String FIELD_SKU = "sku";
	public static final String FIELD_STANDARD_WORKING_HOURS_TOTAL = "standardWorkingHoursTotal";
	public static final String FIELD_LINE = "line";
	public static final String FIELD_VERSION_NUMBER = "versionNumber";
	public static final String FIELD_PROJECT_ID = "projectId";

	@Id
	@GeneratedValue
	private Float routeId;

	/**
	 *工艺路径编号
	 */
	@Length(max = 50)
	private String routeNumber;

	private Float skuId;

	/**
	 *标准工时小计(s)
	 */
	private Float standardWorkingHoursTotal;

	/**
	 *加工线
	 */
	@Length(max = 10)
	private String line;

	/**
	 *版本
	 */
	@Length(max = 10)
	private String routeVersion;

	/**
	 *项目ID
	 */
	@Length(max = 10)
	private String projectId;

	/**
	 *审批状态
	 */
	@Length(max = 10)
	private String status;
	
	/**
	 *E-Bom版本
	 */
	@Length(max = 10)
	private String eBomVersion;
	
	/**
	 *复制来源Code
	 */
	@Length(max = 50)
	private String copyFromRn ;
	
	/**
	 *复制来源Version
	 */
	@Length(max = 10)
	private String copyFromRv;

	public void setRouteId(Float routeId) {
		this.routeId = routeId;
	}

	public Float getRouteId() {
		return routeId;
	}

	public void setRouteNumber(String routeNumber) {
		this.routeNumber = routeNumber;
	}

	public String getRouteNumber() {
		return routeNumber;
	}

	public void setStandardWorkingHoursTotal(Float standardWorkingHoursTotal) {
		this.standardWorkingHoursTotal = standardWorkingHoursTotal;
	}

	public Float getStandardWorkingHoursTotal() {
		return standardWorkingHoursTotal;
	}

	public void setLine(String line) {
		this.line = line;
	}

	public String getLine() {
		return line;
	}


	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getProjectId() {
		return projectId;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String geteBomVersion() {
		return eBomVersion;
	}

	public void seteBomVersion(String eBomVersion) {
		this.eBomVersion = eBomVersion;
	}

	public String getCopyFromRn() {
		return copyFromRn;
	}

	public void setCopyFromRn(String copyFromRn) {
		this.copyFromRn = copyFromRn;
	}

	public String getCopyFromRv() {
		return copyFromRv;
	}

	public void setCopyFromRv(String copyFromRv) {
		this.copyFromRv = copyFromRv;
	}


	public String getRouteVersion() {
		return routeVersion;
	}

	public void setRouteVersion(String routeVersion) {
		this.routeVersion = routeVersion;
	}

	public Float getSkuId() {
		return skuId;
	}

	public void setSkuId(Float skuId) {
		this.skuId = skuId;
	}
}
