package com.hand.hqm.hqm_pqc_warning_record.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_PQC_WARNING_RECORD")
public class PqcWarningRecord extends BaseDTO {

     public static final String FIELD_KID = "kid";
     public static final String FIELD_PLANT_ID = "plantId";
     public static final String FIELD_WARNING_ID = "warningId";
     public static final String FIELD_TASK_ID = "taskId";
     public static final String FIELD_WARNING_DESC = "warningDesc";
     public static final String FIELD_WARNING_OBJECT = "warningObject";
     public static final String FIELD_IS_SEND = "isSend";


     @Id
     @GeneratedValue
     private Float kid;

     private Float plantId;

     private Float warningId;

     private Float taskId;

     @Length(max = 240)
     private String warningDesc;

     @Length(max = 240)
     private String warningObject;

     @Length(max = 1)
     private String isSend;


     public void setKid(Float kid){
         this.kid = kid;
     }

     public Float getKid(){
         return kid;
     }

     public void setPlantId(Float plantId){
         this.plantId = plantId;
     }

     public Float getPlantId(){
         return plantId;
     }

     public void setWarningId(Float warningId){
         this.warningId = warningId;
     }

     public Float getWarningId(){
         return warningId;
     }

     public void setTaskId(Float taskId){
         this.taskId = taskId;
     }

     public Float getTaskId(){
         return taskId;
     }

     public void setWarningDesc(String warningDesc){
         this.warningDesc = warningDesc;
     }

     public String getWarningDesc(){
         return warningDesc;
     }

     public void setWarningObject(String warningObject){
         this.warningObject = warningObject;
     }

     public String getWarningObject(){
         return warningObject;
     }

     public void setIsSend(String isSend){
         this.isSend = isSend;
     }

     public String getIsSend(){
         return isSend;
     }

     }
