package com.hand.hqm.hqm_pfmea_detail.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import java.util.List;
@ExtensionAttribute(disable=true)
@Table(name = "HQM_PFMEA_DETAIL")
public class PfmeaDetail extends BaseDTO {

     public static final String FIELD_FMEA_ID = "fmeaId";
     public static final String FIELD_BRANCH_ID = "branchId";
     public static final String FIELD_PARENT_BRANCH_ID = "parentBranchId";
     public static final String FIELD_RANKS = "ranks";
     public static final String FIELD_BRANCH_NAME = "branchName";
     public static final String FIELD_INVALID_CONSEQUENCE = "invalidConsequence";
     public static final String FIELD_FAILURE_CONSEQUENCES = "failureConsequences";
     public static final String FIELD_SEVERITY = "severity";
     public static final String FIELD_SPECIAL_CHARACTERISTIC_TYPE = "specialCharacteristicType";
     public static final String FIELD_FAILURE_REASON = "failureReason";
     public static final String FIELD_PREVENTIVE_MEASURE = "preventiveMeasure";
     public static final String FIELD_OCCURRENCE = "occurrence";
     public static final String FIELD_DETECTION_MEASURE = "detectionMeasure";
     public static final String FIELD_DETECTION = "detection";
     public static final String FIELD_RPN = "rpn";
     public static final String FIELD_SUGGEST_MEASURE = "suggestMeasure";
     public static final String FIELD_CHARGE_ID = "chargeId";
     public static final String FIELD_ESTIMATED_FINISH_TIME = "estimatedFinishTime";
     public static final String FIELD_MEASURE_RESULT = "measureResult";
     public static final String FIELD_POST_OCCURRENCE = "postOccurrence";
     public static final String FIELD_POST_DETECTION = "postDetection";
     public static final String FIELD_POST_RPN = "postRpn";
     public static final String FIELD_POST_SEVERITY = "postSeverity";


     private Float fmeaId;

     @Id
     @GeneratedValue
     private Long branchId;

     private Long parentBranchId;

     private Long ranks;

     @Length(max = 50)
     private String branchName;

     @Length(max = 2000)
     private String invalidConsequence;

     @Length(max = 2000)
     private String failureConsequences;

     private Long severity;

     @Length(max = 10)
     private String specialCharacteristicType;

     @Length(max = 2000)
     private String failureReason;

     @Length(max = 2000)
     private String preventiveMeasure;

     private Long occurrence;

     @Length(max = 2000)
     private String detectionMeasure;

     private Long detection;

     private Long rpn;

     @Length(max = 2000)
     private String suggestMeasure;

     private Float chargeId;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     @JsonFormat(pattern="yyyy-MM-dd",timezone = "GMT+8")
     private Date estimatedFinishTime;

     @Length(max = 2000)
     private String measureResult;

     private Float postOccurrence;

     private Float postDetection;

     private Float postRpn;

     private Float postSeverity;

     private String claim;
     
     private String potentialFailureMode;
     
     public String getClaim() {
		return claim;
	}

	public void setClaim(String claim) {
		this.claim = claim;
	}

	public String getPotentialFailureMode() {
		return potentialFailureMode;
	}

	public void setPotentialFailureMode(String potentialFailureMode) {
		this.potentialFailureMode = potentialFailureMode;
	}

	@Transient
     private String useName;   
  	@Transient
  	private Long functionId;
  	@Transient
  	private Long structureId;

  	@Transient
  	private String functionName;

  	@Transient
  	private String structureName;

  	@Transient
  	private Float rownum;

  	@Transient
  	private String fmeaCode;
  	@Transient
  	private String fmeaName;
  	@Transient
  	private String fmeaType;
  	@Transient
  	private String fmeaUseName;
  	@Transient
  	private String currentVersion;
  	@Transient
  	private String useNames;
  	
  	@Transient
  	private String analysisObject;
  	
  	
  	@Transient
  	private Date lastUpdateDate;
  	
  	@Transient
  	private Float kid;
  	
  	@Transient
 	private String estimatedFinishTimeStart;
 	
 	@Transient
 	private String estimatedFinishTimeEnd;
 	
 	@Transient
 	private List<String> postDetectionList;
 	
 	@Transient
 	private String postDetections;
 	@Transient
 	private List<String> severityList;
 	
 	@Transient
 	private String severitys;
 	@Transient
 	private List<String> occurrenceList;
 	
 	@Transient
 	private String occurrences;
 	@Transient
 	private List<String> detectionList;
 	
 	@Transient
 	private String detections;
 	@Transient
 	private List<String> postSeverityList;
 	
 	@Transient
 	private String postSeveritys;
 	@Transient
 	private List<String> postOccurrenceList;
 	
 	@Transient
 	private String postOccurrences;
 	@Transient
 	private List<String> specialCharacteristicTypeList;
 	
 	@Transient
 	private String specialCharacteristicTypes;
     
 	public String getPostDetections() {
		return postDetections;
	}

	public void setPostDetections(String postDetections) {
		this.postDetections = postDetections;
	}

	public String getSeveritys() {
		return severitys;
	}

	public void setSeveritys(String severitys) {
		this.severitys = severitys;
	}

	public String getOccurrences() {
		return occurrences;
	}

	public void setOccurrences(String occurrences) {
		this.occurrences = occurrences;
	}

	public String getDetections() {
		return detections;
	}

	public void setDetections(String detections) {
		this.detections = detections;
	}

	public String getPostSeveritys() {
		return postSeveritys;
	}

	public void setPostSeveritys(String postSeveritys) {
		this.postSeveritys = postSeveritys;
	}

	public String getPostOccurrences() {
		return postOccurrences;
	}

	public void setPostOccurrences(String postOccurrences) {
		this.postOccurrences = postOccurrences;
	}

	public String getSpecialCharacteristicTypes() {
		return specialCharacteristicTypes;
	}

	public void setSpecialCharacteristicTypes(String specialCharacteristicTypes) {
		this.specialCharacteristicTypes = specialCharacteristicTypes;
	}

	public String getEstimatedFinishTimeStart() {
		return estimatedFinishTimeStart;
	}

	public void setEstimatedFinishTimeStart(String estimatedFinishTimeStart) {
		this.estimatedFinishTimeStart = estimatedFinishTimeStart;
	}

	public String getEstimatedFinishTimeEnd() {
		return estimatedFinishTimeEnd;
	}

	public void setEstimatedFinishTimeEnd(String estimatedFinishTimeEnd) {
		this.estimatedFinishTimeEnd = estimatedFinishTimeEnd;
	}

	public List<String> getPostDetectionList() {
		return postDetectionList;
	}

	public void setPostDetectionList(List<String> postDetectionList) {
		this.postDetectionList = postDetectionList;
	}

	public List<String> getSeverityList() {
		return severityList;
	}

	public void setSeverityList(List<String> severityList) {
		this.severityList = severityList;
	}

	public List<String> getOccurrenceList() {
		return occurrenceList;
	}

	public void setOccurrenceList(List<String> occurrenceList) {
		this.occurrenceList = occurrenceList;
	}

	public List<String> getDetectionList() {
		return detectionList;
	}

	public void setDetectionList(List<String> detectionList) {
		this.detectionList = detectionList;
	}

	public List<String> getPostSeverityList() {
		return postSeverityList;
	}

	public void setPostSeverityList(List<String> postSeverityList) {
		this.postSeverityList = postSeverityList;
	}

	public List<String> getPostOccurrenceList() {
		return postOccurrenceList;
	}

	public void setPostOccurrenceList(List<String> postOccurrenceList) {
		this.postOccurrenceList = postOccurrenceList;
	}

	public List<String> getSpecialCharacteristicTypeList() {
		return specialCharacteristicTypeList;
	}

	public void setSpecialCharacteristicTypeList(List<String> specialCharacteristicTypeList) {
		this.specialCharacteristicTypeList = specialCharacteristicTypeList;
	}

	public void setFmeaId(Float fmeaId){
         this.fmeaId = fmeaId;
     }

     public Float getFmeaId(){
         return fmeaId;
     }

     public void setBranchId(Long branchId){
         this.branchId = branchId;
     }

     public Long getBranchId(){
         return branchId;
     }

     public void setParentBranchId(Long parentBranchId){
         this.parentBranchId = parentBranchId;
     }

     public Long getParentBranchId(){
         return parentBranchId;
     }

     public void setRanks(Long ranks){
         this.ranks = ranks;
     }

     public Long getRanks(){
         return ranks;
     }

     public void setBranchName(String branchName){
         this.branchName = branchName;
     }

     public String getBranchName(){
         return branchName;
     }

     public void setInvalidConsequence(String invalidConsequence){
         this.invalidConsequence = invalidConsequence;
     }

     public String getInvalidConsequence(){
         return invalidConsequence;
     }

     public void setFailureConsequences(String failureConsequences){
         this.failureConsequences = failureConsequences;
     }

     public String getFailureConsequences(){
         return failureConsequences;
     }

     public void setSeverity(Long severity){
         this.severity = severity;
     }

     public Long getSeverity(){
         return severity;
     }

     public void setSpecialCharacteristicType(String specialCharacteristicType){
         this.specialCharacteristicType = specialCharacteristicType;
     }

     public String getSpecialCharacteristicType(){
         return specialCharacteristicType;
     }

     public void setFailureReason(String failureReason){
         this.failureReason = failureReason;
     }

     public String getFailureReason(){
         return failureReason;
     }

     public void setPreventiveMeasure(String preventiveMeasure){
         this.preventiveMeasure = preventiveMeasure;
     }

     public String getPreventiveMeasure(){
         return preventiveMeasure;
     }

     public void setOccurrence(Long occurrence){
         this.occurrence = occurrence;
     }

     public Long getOccurrence(){
         return occurrence;
     }

     public void setDetectionMeasure(String detectionMeasure){
         this.detectionMeasure = detectionMeasure;
     }

     public String getDetectionMeasure(){
         return detectionMeasure;
     }

     public void setDetection(Long detection){
         this.detection = detection;
     }

     public Long getDetection(){
         return detection;
     }

     public void setRpn(Long rpn){
         this.rpn = rpn;
     }

     public Long getRpn(){
         return rpn;
     }

     public Long getFunctionId() {
		return functionId;
	}

	public void setFunctionId(Long functionId) {
		this.functionId = functionId;
	}

	public Long getStructureId() {
		return structureId;
	}

	public void setStructureId(Long structureId) {
		this.structureId = structureId;
	}

	public String getAnalysisObject() {
		return analysisObject;
	}

	public void setAnalysisObject(String analysisObject) {
		this.analysisObject = analysisObject;
	}

	public Float getKid() {
		return kid;
	}

	public void setKid(Float kid) {
		this.kid = kid;
	}

	public String getUseName() {
		return useName;
	}

	public void setUseName(String useName) {
		this.useName = useName;
	}

	public String getFunctionName() {
		return functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public String getStructureName() {
		return structureName;
	}

	public void setStructureName(String structureName) {
		this.structureName = structureName;
	}

	public Float getRownum() {
		return rownum;
	}

	public void setRownum(Float rownum) {
		this.rownum = rownum;
	}

	public String getFmeaCode() {
		return fmeaCode;
	}

	public void setFmeaCode(String fmeaCode) {
		this.fmeaCode = fmeaCode;
	}

	public String getFmeaName() {
		return fmeaName;
	}

	public void setFmeaName(String fmeaName) {
		this.fmeaName = fmeaName;
	}

	public String getFmeaType() {
		return fmeaType;
	}

	public void setFmeaType(String fmeaType) {
		this.fmeaType = fmeaType;
	}

	public String getFmeaUseName() {
		return fmeaUseName;
	}

	public void setFmeaUseName(String fmeaUseName) {
		this.fmeaUseName = fmeaUseName;
	}

	public String getCurrentVersion() {
		return currentVersion;
	}

	public void setCurrentVersion(String currentVersion) {
		this.currentVersion = currentVersion;
	}

	public String getUseNames() {
		return useNames;
	}

	public void setUseNames(String useNames) {
		this.useNames = useNames;
	}

	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public void setSuggestMeasure(String suggestMeasure){
         this.suggestMeasure = suggestMeasure;
     }

     public String getSuggestMeasure(){
         return suggestMeasure;
     }

     public void setChargeId(Float chargeId){
         this.chargeId = chargeId;
     }

     public Float getChargeId(){
         return chargeId;
     }

     public void setEstimatedFinishTime(Date estimatedFinishTime){
         this.estimatedFinishTime = estimatedFinishTime;
     }

     public Date getEstimatedFinishTime(){
         return estimatedFinishTime;
     }

     public void setMeasureResult(String measureResult){
         this.measureResult = measureResult;
     }

     public String getMeasureResult(){
         return measureResult;
     }

     public void setPostOccurrence(Float postOccurrence){
         this.postOccurrence = postOccurrence;
     }

     public Float getPostOccurrence(){
         return postOccurrence;
     }

     public void setPostDetection(Float postDetection){
         this.postDetection = postDetection;
     }

     public Float getPostDetection(){
         return postDetection;
     }

     public void setPostRpn(Float postRpn){
         this.postRpn = postRpn;
     }

     public Float getPostRpn(){
         return postRpn;
     }

     public void setPostSeverity(Float postSeverity){
         this.postSeverity = postSeverity;
     }

     public Float getPostSeverity(){
         return postSeverity;
     }

     }
