package com.hand.hqm.hqm_sample_scheme.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

//disable = false 启用15个备用字段
@ExtensionAttribute(disable = false)
@Table(name = "HQM_SAMPLE_SCHEME")
public class SampleScheme extends BaseDTO {

	@Id
	@GeneratedValue
	private Float schemeId;

	@Length(max = 30)
	private String samplePlanType;

	@Length(max = 30)
	@NotEmpty
	private String sampleProcedureType;

	@Length(max = 30)
	private String sampleSizeCodeLetter;

	@Length(max = 30)
	private String acceptanceQualityLimit;

	private Float sampleSize;

	private Float acValue;

	private Float reValue;

	@Length(max = 1)
	private String enableFlag;

	public void setSchemeId(Float schemeId) {
		this.schemeId = schemeId;
	}

	public Float getSchemeId() {
		return schemeId;
	}

	public void setSamplePlanType(String samplePlanType) {
		this.samplePlanType = samplePlanType;
	}

	public String getSamplePlanType() {
		return samplePlanType;
	}

	public void setSampleProcedureType(String sampleProcedureType) {
		this.sampleProcedureType = sampleProcedureType;
	}

	public String getSampleProcedureType() {
		return sampleProcedureType;
	}

	public void setSampleSizeCodeLetter(String sampleSizeCodeLetter) {
		this.sampleSizeCodeLetter = sampleSizeCodeLetter;
	}

	public String getSampleSizeCodeLetter() {
		return sampleSizeCodeLetter;
	}

	public void setAcceptanceQualityLimit(String acceptanceQualityLimit) {
		this.acceptanceQualityLimit = acceptanceQualityLimit;
	}

	public String getAcceptanceQualityLimit() {
		return acceptanceQualityLimit;
	}

	public void setSampleSize(Float sampleSize) {
		this.sampleSize = sampleSize;
	}

	public Float getSampleSize() {
		return sampleSize;
	}

	public void setAcValue(Float acValue) {
		this.acValue = acValue;
	}

	public Float getAcValue() {
		return acValue;
	}

	public void setReValue(Float reValue) {
		this.reValue = reValue;
	}

	public Float getReValue() {
		return reValue;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

}
