package com.hand.spc.his.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "PSPC_SUBGROUP_STATISTIC_HIS")
public class SubgroupStatisticHis extends BaseDTO {

     public static final String FIELD_SUBGROUP_STATISTIC_HIS_ID = "subgroupStatisticHisId";
     public static final String FIELD_SUBGROUP_STATISTIC_ID = "subgroupStatisticId";
     public static final String FIELD_TENANT_ID = "tenantId";
     public static final String FIELD_SITE_ID = "siteId";
     public static final String FIELD_SAMPLE_SUBGROUP_ID = "sampleSubgroupId";
     public static final String FIELD_ENTITY_CODE = "entityCode";
     public static final String FIELD_ENTITY_VERSION = "entityVersion";
     public static final String FIELD_SUBGROUP_BAR = "subgroupBar";
     public static final String FIELD_SUBGROUP_R = "subgroupR";
     public static final String FIELD_SUBGROUP_MAX = "subgroupMax";
     public static final String FIELD_SUBGROUP_MIN = "subgroupMin";
     public static final String FIELD_SUBGROUP_SIGMA = "subgroupSigma";
     public static final String FIELD_SUBGROUP_ME = "subgroupMe";
     public static final String FIELD_SUBGROUP_RM = "subgroupRm";

    @Id
    @GeneratedValue
     private Float subgroupStatisticHisId;

     private Float subgroupStatisticId;

     private Float tenantId;

     private Float siteId;

     private Float sampleSubgroupId;

     @Length(max = 100)
     private String entityCode;

     @Length(max = 30)
     private String entityVersion;

     private Float subgroupBar;

     private Float subgroupR;

     private Float subgroupMax;

     private Float subgroupMin;

     private Float subgroupSigma;

     private Float subgroupMe;

     private Float subgroupRm;


     public void setSubgroupStatisticHisId(Float subgroupStatisticHisId){
         this.subgroupStatisticHisId = subgroupStatisticHisId;
     }

     public Float getSubgroupStatisticHisId(){
         return subgroupStatisticHisId;
     }

     public void setSubgroupStatisticId(Float subgroupStatisticId){
         this.subgroupStatisticId = subgroupStatisticId;
     }

     public Float getSubgroupStatisticId(){
         return subgroupStatisticId;
     }

     public void setTenantId(Float tenantId){
         this.tenantId = tenantId;
     }

     public Float getTenantId(){
         return tenantId;
     }

     public void setSiteId(Float siteId){
         this.siteId = siteId;
     }

     public Float getSiteId(){
         return siteId;
     }

     public void setSampleSubgroupId(Float sampleSubgroupId){
         this.sampleSubgroupId = sampleSubgroupId;
     }

     public Float getSampleSubgroupId(){
         return sampleSubgroupId;
     }

     public void setEntityCode(String entityCode){
         this.entityCode = entityCode;
     }

     public String getEntityCode(){
         return entityCode;
     }

     public void setEntityVersion(String entityVersion){
         this.entityVersion = entityVersion;
     }

     public String getEntityVersion(){
         return entityVersion;
     }

     public void setSubgroupBar(Float subgroupBar){
         this.subgroupBar = subgroupBar;
     }

     public Float getSubgroupBar(){
         return subgroupBar;
     }

     public void setSubgroupR(Float subgroupR){
         this.subgroupR = subgroupR;
     }

     public Float getSubgroupR(){
         return subgroupR;
     }

     public void setSubgroupMax(Float subgroupMax){
         this.subgroupMax = subgroupMax;
     }

     public Float getSubgroupMax(){
         return subgroupMax;
     }

     public void setSubgroupMin(Float subgroupMin){
         this.subgroupMin = subgroupMin;
     }

     public Float getSubgroupMin(){
         return subgroupMin;
     }

     public void setSubgroupSigma(Float subgroupSigma){
         this.subgroupSigma = subgroupSigma;
     }

     public Float getSubgroupSigma(){
         return subgroupSigma;
     }

     public void setSubgroupMe(Float subgroupMe){
         this.subgroupMe = subgroupMe;
     }

     public Float getSubgroupMe(){
         return subgroupMe;
     }

     public void setSubgroupRm(Float subgroupRm){
         this.subgroupRm = subgroupRm;
     }

     public Float getSubgroupRm(){
         return subgroupRm;
     }

     }
