package com.hand.spc.message_type_maintenance.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "PSPC_MESSAGE_TYPE")
public class MessageType extends BaseDTO {

     public static final String FIELD_MESSAGE_TYPE_ID = "messageTypeId";
     public static final String FIELD_TENANT_ID = "tenantId";
     public static final String FIELD_SITE_ID = "siteId";
     public static final String FIELD_MESSAGE_TYPE_CODE = "messageTypeCode";
     public static final String FIELD_MESSAGE_TYPE_STATUS = "messageTypeStatus";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";

    @Id
    @GeneratedValue
     private Float messageTypeId;

    @NotNull
     private Float tenantId;

    @NotNull
     private Float siteId;

    @NotNull
     @Length(max = 20)
     private String messageTypeCode;

    @NotNull
     @Length(max = 1)
     private String messageTypeStatus;

     private Float programApplicationId;

     private Date programUpdateDate;


     public void setMessageTypeId(Float messageTypeId){
         this.messageTypeId = messageTypeId;
     }

     public Float getMessageTypeId(){
         return messageTypeId;
     }

     public void setTenantId(Float tenantId){
         this.tenantId = tenantId;
     }

     public Float getTenantId(){
         return tenantId;
     }

     public void setSiteId(Float siteId){
         this.siteId = siteId;
     }

     public Float getSiteId(){
         return siteId;
     }

     public void setMessageTypeCode(String messageTypeCode){
         this.messageTypeCode = messageTypeCode;
     }

     public String getMessageTypeCode(){
         return messageTypeCode;
     }

     public void setMessageTypeStatus(String messageTypeStatus){
         this.messageTypeStatus = messageTypeStatus;
     }

     public String getMessageTypeStatus(){
         return messageTypeStatus;
     }

     public void setProgramApplicationId(Float programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Float getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
