package com.hand.spc.message_type_maintenance.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "PSPC_MESSAGE_TYPE_UPLOAD_REL")
public class MessageTypeUploadRel extends BaseDTO {

     public static final String FIELD_REL_ID = "relId";
     public static final String FIELD_UPLOAD_CONFIG_ID = "uploadConfigId";
     public static final String FIELD_MESSAGE_TYPE_ID = "messageTypeId";
     public static final String FIELD_TENANT_ID = "tenantId";
     public static final String FIELD_SITE_ID = "siteId";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";

    @Id
    @GeneratedValue
     private Float relId;

    @NotNull
     private Float uploadConfigId;

    @NotNull
     private Float messageTypeId;

    @NotNull
     private Float tenantId;

    @NotNull
     private Float siteId;

     private Float programApplicationId;

     private Date programUpdateDate;

     @Transient
     private String configCode;
    @Transient
    private String configType;

    @Transient
    private String configValue;

    @Transient
    private String configDescription;


    public String getConfigCode() {
        return configCode;
    }

    public void setConfigCode(String configCode) {
        this.configCode = configCode;
    }

    public String getConfigType() {
        return configType;
    }

    public void setConfigType(String configType) {
        this.configType = configType;
    }

    public String getConfigValue() {
        return configValue;
    }

    public void setConfigValue(String configValue) {
        this.configValue = configValue;
    }

    public String getConfigDescription() {
        return configDescription;
    }

    public void setConfigDescription(String configDescription) {
        this.configDescription = configDescription;
    }

    public void setRelId(Float relId){
         this.relId = relId;
     }

     public Float getRelId(){
         return relId;
     }

     public void setUploadConfigId(Float uploadConfigId){
         this.uploadConfigId = uploadConfigId;
     }

     public Float getUploadConfigId(){
         return uploadConfigId;
     }

     public void setMessageTypeId(Float messageTypeId){
         this.messageTypeId = messageTypeId;
     }

     public Float getMessageTypeId(){
         return messageTypeId;
     }

     public void setTenantId(Float tenantId){
         this.tenantId = tenantId;
     }

     public Float getTenantId(){
         return tenantId;
     }

     public void setSiteId(Float siteId){
         this.siteId = siteId;
     }

     public Float getSiteId(){
         return siteId;
     }

     public void setProgramApplicationId(Float programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Float getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
