package com.hand.spc.message_type_maintenance.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "PSPC_MESSAGE_TYPE_DETAIL")
public class MessageTypeDetail extends BaseDTO {

     public static final String FIELD_MESSAGE_TYPE_DETAIL_ID = "messageTypeDetailId";
     public static final String FIELD_MESSAGE_TYPE_ID = "messageTypeId";
     public static final String FIELD_TENANT_ID = "tenantId";
     public static final String FIELD_SITE_ID = "siteId";
     public static final String FIELD_ELEMENT_CATEGORY = "elementCategory";
     public static final String FIELD_ELEMENT_CODE = "elementCode";
     public static final String FIELD_ELEMENT_STATUS = "elementStatus";
     public static final String FIELD_PROGRAM_APPLICATION_ID = "programApplicationId";
     public static final String FIELD_PROGRAM_UPDATE_DATE = "programUpdateDate";

    @Id
    @GeneratedValue
     private Float messageTypeDetailId;

    @NotNull
     private Float messageTypeId;

    @NotNull
     private Float tenantId;

    @NotNull
     private Float siteId;

    @NotNull
     @Length(max = 10)
     private String elementCategory;

    @NotNull
     @Length(max = 50)
     private String elementCode;

    @NotNull
     @Length(max = 1)
     private String elementStatus;

     private Float programApplicationId;

     private Date programUpdateDate;



     public void setMessageTypeDetailId(Float messageTypeDetailId){
         this.messageTypeDetailId = messageTypeDetailId;
     }

     public Float getMessageTypeDetailId(){
         return messageTypeDetailId;
     }

     public void setMessageTypeId(Float messageTypeId){
         this.messageTypeId = messageTypeId;
     }

     public Float getMessageTypeId(){
         return messageTypeId;
     }

     public void setTenantId(Float tenantId){
         this.tenantId = tenantId;
     }

     public Float getTenantId(){
         return tenantId;
     }

     public void setSiteId(Float siteId){
         this.siteId = siteId;
     }

     public Float getSiteId(){
         return siteId;
     }

     public void setElementCategory(String elementCategory){
         this.elementCategory = elementCategory;
     }

     public String getElementCategory(){
         return elementCategory;
     }

     public void setElementCode(String elementCode){
         this.elementCode = elementCode;
     }

     public String getElementCode(){
         return elementCode;
     }

     public void setElementStatus(String elementStatus){
         this.elementStatus = elementStatus;
     }

     public String getElementStatus(){
         return elementStatus;
     }

     public void setProgramApplicationId(Float programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Float getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     }
