package com.hand.hqm.hqm_pqc_inspection_h.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HQM_PQC_INSPECTION_H")
public class PqcInspectionH extends BaseDTO {

	@Id
	@GeneratedValue
	private Float headerId;

	@Length(max = 30)
	private String inspectionNum;

	@Length(max = 30)
	private String inspectionType;

	@Length(max = 30)
	private String inspectionFrom;

	private Float plantId;

	private Float prodLineId;

	@Length(max = 30)
	private String inspectionStatus;

	@Length(max = 30)
	private String inspectionRes;

	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	private Date shouldInspectionDate;

	private Date inspectionDate;

	@Length(max = 30)
	private String inspectorId;

	@Length(max = 30)
	private String nonconformingOrder;

	@Length(max = 30)
	private String sourceInspecId;

	@Length(max = 500)
	private String remark;

	@Length(max = 500)
	private String instruction;

	private Float okQty;

	private Float ngQty;

	@Length(max = 500)
	private String inspectionDes;

	@Length(max = 500)
	private String inspectionItemImg;

	@Length(max = 30)
	private String inspectionJudge;

	@Length(max = 30)
	private String approvalResult;

	@Length(max = 30)
	private String approvalId;

	@Length(max = 30)
	private String solveWay;

	@Length(max = 500)
	private String approvalDes;

	@Length(max = 30)
	private String sourceType;

	@Transient
	private String plantCode;

	@Transient
	private String prodLineCode;

	@Transient
	private String prodLineDescriptions;

	@Transient
	private String inspectorUserName;

	@Transient
	private String lineList;

	@Transient
	private String shouldInspectionDateFrom;

	@Transient
	private String shouldInspectionDateTo;

	@Transient
	private String orderCode;

	@Transient
	private Float orderId;

	private String sourceOrder;

	private Float itemId;

	private Float productionQty;

	@Transient
	private String itemCode;

	@Transient
	private String itemDescriptions;

	private String productionBatch;

	@Transient
	private String categoryDescription;

	@Transient
	private String itemName;

	@Transient
	private String inspectionAttribute;

	@Transient

	private String attributeType;

	@Transient
	private String standardType;

	@Transient
	private String qualityCharacterGrade;

	@Transient
	private Float sampleWayId;

	@Transient
	private String description;

	@Transient
	private String standradUom;

	@Transient
	private Float standradFrom;

	@Transient
	private Float standradTo;

	@Transient
	private String attributeInspectionRes;

	@Transient
	private Float lineId;

	@Transient
	private String orderNum;

	@Transient
	private String dataInfo;

	@Transient
	private String judgement;

	@Transient
	private String inspectorEmployeeName;

	@Transient
	private Float forkId;

	@Transient
	private String forkType;

	@Transient
	private String ngQueryFlag;

	@Transient
	private String standardOpId;

	@Transient
	private String workstationId;

	@Transient
	private String itemEdition;

	public String getItemEdition() {
		return itemEdition;
	}

	public void setItemEdition(String itemEdition) {
		this.itemEdition = itemEdition;
	}

	public String getStandardOpId() {
		return standardOpId;
	}

	public void setStandardOpId(String standardOpId) {
		this.standardOpId = standardOpId;
	}

	public String getWorkstationId() {
		return workstationId;
	}

	public void setWorkstationId(String workstationId) {
		this.workstationId = workstationId;
	}

	public String getNgQueryFlag() {
		return ngQueryFlag;
	}

	public void setNgQueryFlag(String ngQueryFlag) {
		this.ngQueryFlag = ngQueryFlag;
	}

	public Float getForkId() {
		return forkId;
	}

	public void setForkId(Float forkId) {
		this.forkId = forkId;
	}

	public String getForkType() {
		return forkType;
	}

	public void setForkType(String forkType) {
		this.forkType = forkType;
	}

	public String getInspectorEmployeeName() {
		return inspectorEmployeeName;
	}

	public void setInspectorEmployeeName(String inspectorEmployeeName) {
		this.inspectorEmployeeName = inspectorEmployeeName;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getInspectionAttribute() {
		return inspectionAttribute;
	}

	public void setInspectionAttribute(String inspectionAttribute) {
		this.inspectionAttribute = inspectionAttribute;
	}

	public String getAttributeType() {
		return attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	public String getStandardType() {
		return standardType;
	}

	public void setStandardType(String standardType) {
		this.standardType = standardType;
	}

	public String getQualityCharacterGrade() {
		return qualityCharacterGrade;
	}

	public void setQualityCharacterGrade(String qualityCharacterGrade) {
		this.qualityCharacterGrade = qualityCharacterGrade;
	}

	public Float getSampleWayId() {
		return sampleWayId;
	}

	public void setSampleWayId(Float sampleWayId) {
		this.sampleWayId = sampleWayId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStandradUom() {
		return standradUom;
	}

	public void setStandradUom(String standradUom) {
		this.standradUom = standradUom;
	}

	public Float getStandradFrom() {
		return standradFrom;
	}

	public void setStandradFrom(Float standradFrom) {
		this.standradFrom = standradFrom;
	}

	public Float getStandradTo() {
		return standradTo;
	}

	public void setStandradTo(Float standradTo) {
		this.standradTo = standradTo;
	}

	public String getAttributeInspectionRes() {
		return attributeInspectionRes;
	}

	public void setAttributeInspectionRes(String attributeInspectionRes) {
		this.attributeInspectionRes = attributeInspectionRes;
	}

	public Float getLineId() {
		return lineId;
	}

	public void setLineId(Float lineId) {
		this.lineId = lineId;
	}

	public String getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public String getDataInfo() {
		return dataInfo;
	}

	public void setDataInfo(String dataInfo) {
		this.dataInfo = dataInfo;
	}

	public String getJudgement() {
		return judgement;
	}

	public void setJudgement(String judgement) {
		this.judgement = judgement;
	}

	public String getCategoryDescription() {
		return categoryDescription;
	}

	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	public String getProductionBatch() {
		return productionBatch;
	}

	public void setProductionBatch(String productionBatch) {
		this.productionBatch = productionBatch;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemDescriptions() {
		return itemDescriptions;
	}

	public void setItemDescriptions(String itemDescriptions) {
		this.itemDescriptions = itemDescriptions;
	}

	public String getSourceOrder() {
		return sourceOrder;
	}

	public void setSourceOrder(String sourceOrder) {
		this.sourceOrder = sourceOrder;
	}

	public Float getItemId() {
		return itemId;
	}

	public void setItemId(Float itemId) {
		this.itemId = itemId;
	}

	public Float getProductionQty() {
		return productionQty;
	}

	public void setProductionQty(Float productionQty) {
		this.productionQty = productionQty;
	}

	public String getOrderCode() {
		return orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	public Float getOrderId() {
		return orderId;
	}

	public void setOrderId(Float orderId) {
		this.orderId = orderId;
	}

	public String getShouldInspectionDateFrom() {
		return shouldInspectionDateFrom;
	}

	public void setShouldInspectionDateFrom(String shouldInspectionDateFrom) {
		this.shouldInspectionDateFrom = shouldInspectionDateFrom;
	}

	public String getShouldInspectionDateTo() {
		return shouldInspectionDateTo;
	}

	public void setShouldInspectionDateTo(String shouldInspectionDateTo) {
		this.shouldInspectionDateTo = shouldInspectionDateTo;
	}

	public String getPlantCode() {
		return plantCode;
	}

	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}

	public String getProdLineCode() {
		return prodLineCode;
	}

	public void setProdLineCode(String prodLineCode) {
		this.prodLineCode = prodLineCode;
	}

	public String getProdLineDescriptions() {
		return prodLineDescriptions;
	}

	public void setProdLineDescriptions(String prodLineDescriptions) {
		this.prodLineDescriptions = prodLineDescriptions;
	}

	public String getInspectorUserName() {
		return inspectorUserName;
	}

	public void setInspectorUserName(String inspectorUserName) {
		this.inspectorUserName = inspectorUserName;
	}

	public String getLineList() {
		return lineList;
	}

	public void setLineList(String lineList) {
		this.lineList = lineList;
	}

	public void setHeaderId(Float headerId) {
		this.headerId = headerId;
	}

	public Float getHeaderId() {
		return headerId;
	}

	public void setInspectionNum(String inspectionNum) {
		this.inspectionNum = inspectionNum;
	}

	public String getInspectionNum() {
		return inspectionNum;
	}

	public void setInspectionType(String inspectionType) {
		this.inspectionType = inspectionType;
	}

	public String getInspectionType() {
		return inspectionType;
	}

	public void setInspectionFrom(String inspectionFrom) {
		this.inspectionFrom = inspectionFrom;
	}

	public String getInspectionFrom() {
		return inspectionFrom;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setProdLineId(Float prodLineId) {
		this.prodLineId = prodLineId;
	}

	public Float getProdLineId() {
		return prodLineId;
	}

	public void setInspectionStatus(String inspectionStatus) {
		this.inspectionStatus = inspectionStatus;
	}

	public String getInspectionStatus() {
		return inspectionStatus;
	}

	public void setInspectionRes(String inspectionRes) {
		this.inspectionRes = inspectionRes;
	}

	public String getInspectionRes() {
		return inspectionRes;
	}

	public void setShouldInspectionDate(Date shouldInspectionDate) {
		this.shouldInspectionDate = shouldInspectionDate;
	}

	public Date getShouldInspectionDate() {
		return shouldInspectionDate;
	}

	public void setInspectionDate(Date inspectionDate) {
		this.inspectionDate = inspectionDate;
	}

	public Date getInspectionDate() {
		return inspectionDate;
	}

	public void setInspectorId(String inspectorId) {
		this.inspectorId = inspectorId;
	}

	public String getInspectorId() {
		return inspectorId;
	}

	public void setNonconformingOrder(String nonconformingOrder) {
		this.nonconformingOrder = nonconformingOrder;
	}

	public String getNonconformingOrder() {
		return nonconformingOrder;
	}

	public void setSourceInspecId(String sourceInspecId) {
		this.sourceInspecId = sourceInspecId;
	}

	public String getSourceInspecId() {
		return sourceInspecId;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getRemark() {
		return remark;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	public String getInstruction() {
		return instruction;
	}

	public void setOkQty(Float okQty) {
		this.okQty = okQty;
	}

	public Float getOkQty() {
		return okQty;
	}

	public void setNgQty(Float ngQty) {
		this.ngQty = ngQty;
	}

	public Float getNgQty() {
		return ngQty;
	}

	public void setInspectionDes(String inspectionDes) {
		this.inspectionDes = inspectionDes;
	}

	public String getInspectionDes() {
		return inspectionDes;
	}

	public void setInspectionItemImg(String inspectionItemImg) {
		this.inspectionItemImg = inspectionItemImg;
	}

	public String getInspectionItemImg() {
		return inspectionItemImg;
	}

	public void setInspectionJudge(String inspectionJudge) {
		this.inspectionJudge = inspectionJudge;
	}

	public String getInspectionJudge() {
		return inspectionJudge;
	}

	public void setApprovalResult(String approvalResult) {
		this.approvalResult = approvalResult;
	}

	public String getApprovalResult() {
		return approvalResult;
	}

	public void setApprovalId(String approvalId) {
		this.approvalId = approvalId;
	}

	public String getApprovalId() {
		return approvalId;
	}

	public void setSolveWay(String solveWay) {
		this.solveWay = solveWay;
	}

	public String getSolveWay() {
		return solveWay;
	}

	public void setApprovalDes(String approvalDes) {
		this.approvalDes = approvalDes;
	}

	public String getApprovalDes() {
		return approvalDes;
	}

	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	public String getSourceType() {
		return sourceType;
	}

}
