package com.hand.spc.pspc_attachment_relation.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

@ExtensionAttribute(disable=true)
@Table(name = "pspc_attachment_relation")
public class AttachmentRelation extends BaseDTO {

    public static final String FIELD_ATTACHMENT_RELATION_ID = "attachmentRelationId";
    public static final String FIELD_TENANT_ID = "tenantId";
    public static final String FIELD_SITE_ID = "siteId";
    public static final String FIELD_ATTACHMENT_GROUP_ID = "attachmentGroupId";
    public static final String FIELD_ATTACHMENT_ID = "attachmentId";


    @Id
    @GeneratedValue
    private Long attachmentRelationId; //表ID，主键

    private Long tenantId; //租户ID

    private Long siteId; //站点ID

    private Long attachmentGroupId; //附着对象组ID

    private Long attachmentId; //附着对象ID

    @Transient
    private Long ceGroupId; //控制要素组ID

    @Transient
    private String attachmentIds; //附着对象ID集合


    public void setAttachmentRelationId(Long attachmentRelationId){
        this.attachmentRelationId = attachmentRelationId;
    }

    public Long getAttachmentRelationId(){
        return attachmentRelationId;
    }

    public void setTenantId(Long tenantId){
        this.tenantId = tenantId;
    }

    public Long getTenantId(){
        return tenantId;
    }

    public void setSiteId(Long siteId){
        this.siteId = siteId;
    }

    public Long getSiteId(){
        return siteId;
    }

    public void setAttachmentGroupId(Long attachmentGroupId){
        this.attachmentGroupId = attachmentGroupId;
    }

    public Long getAttachmentGroupId(){
        return attachmentGroupId;
    }

    public void setAttachmentId(Long attachmentId){
        this.attachmentId = attachmentId;
    }

    public Long getAttachmentId(){
        return attachmentId;
    }

    public Long getCeGroupId() {
        return ceGroupId;
    }

    public void setCeGroupId(Long ceGroupId) {
        this.ceGroupId = ceGroupId;
    }

    public String getAttachmentIds() {
        return attachmentIds;
    }

    public void setAttachmentIds(String attachmentIds) {
        this.attachmentIds = attachmentIds;
    }
}
