package com.hand.hcs.hcs_tax_invoice.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "HCS_TAX_INVOICE")
public class TaxInvoice extends BaseDTO {

	public static final String FIELD_WEB_INVOICE_ID = "webInvoiceId";
	public static final String FIELD_WEB_INVOICE_NUM = "webInvoiceNum";
	public static final String FIELD_WEB_INVOICE_STATUS = "webInvoiceStatus";
	public static final String FIELD_TAX_INVOICE_NUM = "taxInvoiceNum";
	public static final String FIELD_ENABLE_FLAG = "enableFlag";
	public static final String FIELD_TAX_INVOICE_QTY = "taxInvoiceQty";
	public static final String FIELD_NO_TAX_AMOUNT = "noTaxAmount";
	public static final String FIELD_INVOICE_TAX_AMOUNT = "invoiceTaxAmount";
	public static final String FIELD_INVOICE_AMOUNT = "invoiceAmount";
	public static final String FIELD_NO_TAX_AMOUNT_S = "noTaxAmountS";
	public static final String FIELD_INVOICE_TAX_AMOUNT_S = "invoiceTaxAmountS";
	public static final String FIELD_INVOICE_AMOUNT_S = "invoiceAmountS";
	public static final String FIELD_PLANT_ID = "plantId";
	public static final String FIELD_SUPPLIER_ID = "supplierId";
	public static final String FIELD_SUPPLIER_SITE_ID = "supplierSiteId";
	public static final String FIELD_SUPPLIER_REMARKS = "supplierRemarks";
	public static final String FIELD_CURRENCY = "currency";
	public static final String FIELD_APPROVED_BY = "approvedBy";
	public static final String FIELD_APPROVED_FULL_NAME = "approvedFullName";
	public static final String FIELD_SUBMITED_ID = "submitedId";
	public static final String FIELD_SUBMITED_DATE = "submitedDate";
	public static final String FIELD_APPROVED_DATE = "approvedDate";
	public static final String FIELD_APPROVED_REMARKS = "approvedRemarks";

	@Id
	@GeneratedValue
	private Float webInvoiceId;

	@Length(max = 30)
	private String webInvoiceNum;

	@Length(max = 30)
	private String webInvoiceStatus;

	@Length(max = 240)
	private String taxInvoiceNum;

	@Length(max = 1)
	private String enableFlag;

	private Float taxInvoiceQty;

	private Float noTaxAmount;

	private Float invoiceTaxAmount;

	private Float invoiceAmount;

	private Float noTaxAmountS;

	private Float invoiceTaxAmountS;

	private Float invoiceAmountS;

	private Float plantId;

	private Float supplierId;

	private Float supplierSiteId;

	@Length(max = 240)
	private String supplierRemarks;

	@Length(max = 30)
	private String currency;

	private Float approvedBy;

	@Length(max = 20)
	private String approvedFullName;

	private Float submitedId;

	private Date submitedDate;

	private Date approvedDate;

	@Length(max = 240)
	private String approvedRemarks;

	private Date creationDate;

	@Transient
	private String plantName;// 工厂
	@Transient
	private String supplierCode;// 供应商编码
	@Transient
	private String supplierName;// 供应商名称
	@Transient
	private String supplierSiteName;// 供应商地点
	@Transient
	private String creationName;// 创建人
	@Transient
	private List<Float> docSettlementIdList;
	@Transient
	private String startTime;// 创建时间从
	@Transient
	private String endTime;// 创建时间至
	@Transient
	private String startDate;// 审批日期从
	@Transient
	private String endDate;// 审批日期至
	@Transient
	private String submitEndDate;// 提交日期至
	@Transient
	private String submitStartDate;// 提交日期从
	@Transient
	private String submitName;// 提交人
	@Transient
	private String functionFlag;// 功能标识
	@Transient
	private String purchaseGroup;// 采购组

	
	public String getPurchaseGroup() {
		return purchaseGroup;
	}

	public void setPurchaseGroup(String purchaseGroup) {
		this.purchaseGroup = purchaseGroup;
	}

	public String getFunctionFlag() {
		return functionFlag;
	}

	public void setFunctionFlag(String functionFlag) {
		this.functionFlag = functionFlag;
	}

	public String getSubmitName() {
		return submitName;
	}

	public void setSubmitName(String submitName) {
		this.submitName = submitName;
	}

	public String getSubmitEndDate() {
		return submitEndDate;
	}

	public void setSubmitEndDate(String submitEndDate) {
		this.submitEndDate = submitEndDate;
	}

	public String getSubmitStartDate() {
		return submitStartDate;
	}

	public void setSubmitStartDate(String submitStartDate) {
		this.submitStartDate = submitStartDate;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getStartDate() {
		return startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public List<Float> getDocSettlementIdList() {
		return docSettlementIdList;
	}

	public void setDocSettlementIdList(List<Float> docSettlementIdList) {
		this.docSettlementIdList = docSettlementIdList;
	}

	public String getPlantName() {
		return plantName;
	}

	public void setPlantName(String plantName) {
		this.plantName = plantName;
	}

	public String getSupplierCode() {
		return supplierCode;
	}

	public void setSupplierCode(String supplierCode) {
		this.supplierCode = supplierCode;
	}

	public String getSupplierName() {
		return supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getSupplierSiteName() {
		return supplierSiteName;
	}

	public void setSupplierSiteName(String supplierSiteName) {
		this.supplierSiteName = supplierSiteName;
	}

	public String getCreationName() {
		return creationName;
	}

	public void setCreationName(String creationName) {
		this.creationName = creationName;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setWebInvoiceId(Float webInvoiceId) {
		this.webInvoiceId = webInvoiceId;
	}

	public Float getWebInvoiceId() {
		return webInvoiceId;
	}

	public void setWebInvoiceNum(String webInvoiceNum) {
		this.webInvoiceNum = webInvoiceNum;
	}

	public String getWebInvoiceNum() {
		return webInvoiceNum;
	}

	public void setWebInvoiceStatus(String webInvoiceStatus) {
		this.webInvoiceStatus = webInvoiceStatus;
	}

	public String getWebInvoiceStatus() {
		return webInvoiceStatus;
	}

	public void setTaxInvoiceNum(String taxInvoiceNum) {
		this.taxInvoiceNum = taxInvoiceNum;
	}

	public String getTaxInvoiceNum() {
		return taxInvoiceNum;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

	public void setTaxInvoiceQty(Float taxInvoiceQty) {
		this.taxInvoiceQty = taxInvoiceQty;
	}

	public Float getTaxInvoiceQty() {
		return taxInvoiceQty;
	}

	public void setNoTaxAmount(Float noTaxAmount) {
		this.noTaxAmount = noTaxAmount;
	}

	public Float getNoTaxAmount() {
		return noTaxAmount;
	}

	public void setInvoiceTaxAmount(Float invoiceTaxAmount) {
		this.invoiceTaxAmount = invoiceTaxAmount;
	}

	public Float getInvoiceTaxAmount() {
		return invoiceTaxAmount;
	}

	public void setInvoiceAmount(Float invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	public Float getInvoiceAmount() {
		return invoiceAmount;
	}

	public void setNoTaxAmountS(Float noTaxAmountS) {
		this.noTaxAmountS = noTaxAmountS;
	}

	public Float getNoTaxAmountS() {
		return noTaxAmountS;
	}

	public void setInvoiceTaxAmountS(Float invoiceTaxAmountS) {
		this.invoiceTaxAmountS = invoiceTaxAmountS;
	}

	public Float getInvoiceTaxAmountS() {
		return invoiceTaxAmountS;
	}

	public void setInvoiceAmountS(Float invoiceAmountS) {
		this.invoiceAmountS = invoiceAmountS;
	}

	public Float getInvoiceAmountS() {
		return invoiceAmountS;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setSupplierSiteId(Float supplierSiteId) {
		this.supplierSiteId = supplierSiteId;
	}

	public Float getSupplierSiteId() {
		return supplierSiteId;
	}

	public void setSupplierRemarks(String supplierRemarks) {
		this.supplierRemarks = supplierRemarks;
	}

	public String getSupplierRemarks() {
		return supplierRemarks;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getCurrency() {
		return currency;
	}

	public void setApprovedBy(Float approvedBy) {
		this.approvedBy = approvedBy;
	}

	public Float getApprovedBy() {
		return approvedBy;
	}

	public void setApprovedFullName(String approvedFullName) {
		this.approvedFullName = approvedFullName;
	}

	public String getApprovedFullName() {
		return approvedFullName;
	}

	public void setSubmitedId(Float submitedId) {
		this.submitedId = submitedId;
	}

	public Float getSubmitedId() {
		return submitedId;
	}

	public void setSubmitedDate(Date submitedDate) {
		this.submitedDate = submitedDate;
	}

	public Date getSubmitedDate() {
		return submitedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	public Date getApprovedDate() {
		return approvedDate;
	}

	public void setApprovedRemarks(String approvedRemarks) {
		this.approvedRemarks = approvedRemarks;
	}

	public String getApprovedRemarks() {
		return approvedRemarks;
	}

}
