package com.hand.hcs.hcs_po_lines.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HCS_PO_LINES")
public class PoLines extends BaseDTO {

	public static final String FIELD_PO_LINE_ID = "poLineId";
	public static final String FIELD_PO_HEADER_ID = "poHeaderId";
	public static final String FIELD_ORG_ID = "orgId";
	public static final String FIELD_LINE_NUM = "lineNum";
	public static final String FIELD_PLANT_ID = "plantId";
	public static final String FIELD_ITEM_ID = "itemId";
	public static final String FIELD_EDITION = "edition";
	public static final String FIELD_UNIT_CODE = "unitCode";
	public static final String FIELD_QUANTITY = "quantity";
	public static final String FIELD_CANCELED_FLAG = "canceledFlag";
	public static final String FIELD_CLOSED_CODE = "closedCode";
	public static final String FIELD_CLOSED_DATE = "closedDate";
	public static final String FIELD_CLOSED_FLAG = "closedFlag";
	public static final String FIELD_CLOSED_BY = "closedBy";
	public static final String FIELD_CLOSED_REASON = "closedReason";
	public static final String FIELD_ENABLE_FLAG = "enableFlag";
	public static final String FIELD_LINE_STATUS = "lineStatus";
	public static final String FIELD_LINE_AGENT_DESC = "lineAgentDesc";
	public static final String FIELD_LINE_SUPPLIER_DESC = "lineSupplierDesc";
	public static final String FIELD_SOURCE_ID = "sourceId";
	public static final String FIELD_SOURCE_HEADER_ID = "sourceHeaderId";
	public static final String FIELD_SOURCE_REFERENCE = "sourceReference";
	public static final String FIELD_SOURCE_CODE = "sourceCode";
	public static final String FIELD_DESCRIPTIONS = "descriptions";
	public static final String FIELD_CID = "cid";

	@Id
	@GeneratedValue
	private Float poLineId;

	private Float poHeaderId;

	private Float orgId;

	private Float lineNum;

	private Float plantId;

	private Float itemId;
	@Length(max = 30)
	private String edition;

	@Length(max = 10)
	private String unitCode;

	private Float quantity;

	@Length(max = 1)
	private String canceledFlag;

	@Length(max = 25)
	private String closedCode;

	private Date closedDate;

	@Length(max = 1)
	private String closedFlag;

	@Length(max = 20)
	private String closedBy;

	@Length(max = 20)
	private String closedReason;

	@Length(max = 2)
	private String enableFlag;

	@Length(max = 30)
	private String lineStatus;

	@Length(max = 240)
	private String lineAgentDesc;

	@Length(max = 240)
	private String lineSupplierDesc;

	private Float sourceId;

	private Float sourceHeaderId;

	@Length(max = 240)
	private String sourceReference;

	@Length(max = 30)
	private String sourceCode;

	@Length(max = 240)
	private String descriptions;

	private Float cid;

	private Float unitPrice;

	@Length(max = 30)
	private String currency;

	@Length(max = 30)
	private String taxRate;

	private Float lineTotalPrice;

	@Length(max = 30)
	private String priceUnit;

	private Float allowance;
	
	private Date needByDate;
	
	@Transient
	private String shipmentNum;// 发运号

	@Transient
	private String itemCode;// 物料编码

	@Transient
	private String itemName;// 物料描述

	@Transient
	private Float itemEdition;// 物料版本

	@Transient
	private String lineLocationDesc;// 发运行备注

	@Transient
	private String lineLocationSupplierDesc;// 供应商反馈信息

	@Transient
	private Float lineLocationId;// 采购发运行ID

	@Transient
	private Float packingQty;// 包装数

	@Transient
	private Date promisedDate;// 承诺日期

	@Transient
	private String shipmentStatus;// 发运行状态

	@Transient
	private String shipped;// 已发运数量

	@Transient
	private Date confirmTime;// 确认时间

	@Transient
	private String confirmName;// 确认人
	
	@Transient
	private String poStatus;

	@Transient
	private Float supplierId;
	@Transient
	private String primaryUom;
	
	@Transient
	private Float receiveQty;
	@Transient
	private Float packQty;
	@Transient
	private Float jprice;//净价
	@Transient
	private Float refundedQty;//已退货数量
	
	
	
	public Float getRefundedQty() {
		return refundedQty;
	}

	public void setRefundedQty(Float refundedQty) {
		this.refundedQty = refundedQty;
	}

	public Float getJprice() {
		return jprice;
	}

	public void setJprice(Float jprice) {
		this.jprice = jprice;
	}

	public Float getPackQty() {
		return packQty;
	}

	public void setPackQty(Float packQty) {
		this.packQty = packQty;
	}

	public Float getReceiveQty() {
		return receiveQty;
	}

	public void setReceiveQty(Float receiveQty) {
		this.receiveQty = receiveQty;
	}

	public String getPrimaryUom() {
		return primaryUom;
	}

	public void setPrimaryUom(String primaryUom) {
		this.primaryUom = primaryUom;
	}

	public Float getSupplierId() {
		return supplierId;
	}

	public void setSupplierId(Float supplierId) {
		this.supplierId = supplierId;
	}

	public Float getLineTotalPrice() {
		return lineTotalPrice;
	}

	public void setLineTotalPrice(Float lineTotalPrice) {
		this.lineTotalPrice = lineTotalPrice;
	}

	public String getPriceUnit() {
		return priceUnit;
	}

	public void setPriceUnit(String priceUnit) {
		this.priceUnit = priceUnit;
	}

	public String getPoStatus() {
		return poStatus;
	}

	public void setPoStatus(String poStatus) {
		this.poStatus = poStatus;
	}

	public String getShipmentStatus() {
		return shipmentStatus;
	}

	public void setShipmentStatus(String shipmentStatus) {
		this.shipmentStatus = shipmentStatus;
	}

	public String getShipped() {
		return shipped;
	}

	public void setShipped(String shipped) {
		this.shipped = shipped;
	}

	public Date getConfirmTime() {
		return confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	public String getConfirmName() {
		return confirmName;
	}

	public void setConfirmName(String confirmName) {
		this.confirmName = confirmName;
	}

	public Float getPackingQty() {
		return packingQty;
	}

	public void setPackingQty(Float packingQty) {
		this.packingQty = packingQty;
	}

	public Date getPromisedDate() {
		return promisedDate;
	}

	public void setPromisedDate(Date promisedDate) {
		this.promisedDate = promisedDate;
	}

	public Float getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getTaxRate() {
		return taxRate;
	}

	public void setTaxRate(String taxRate) {
		this.taxRate = taxRate;
	}

	public void setPoLineId(Float poLineId) {
		this.poLineId = poLineId;
	}

	public Float getPoLineId() {
		return poLineId;
	}

	public void setPoHeaderId(Float poHeaderId) {
		this.poHeaderId = poHeaderId;
	}

	public Float getPoHeaderId() {
		return poHeaderId;
	}

	public void setOrgId(Float orgId) {
		this.orgId = orgId;
	}

	public Float getOrgId() {
		return orgId;
	}

	public void setLineNum(Float lineNum) {
		this.lineNum = lineNum;
	}

	public Float getLineNum() {
		return lineNum;
	}

	public void setPlantId(Float plantId) {
		this.plantId = plantId;
	}

	public Float getPlantId() {
		return plantId;
	}

	public void setItemId(Float itemId) {
		this.itemId = itemId;
	}

	public Float getItemId() {
		return itemId;
	}

	public String getEdition() {
		return edition;
	}

	public void setEdition(String edition) {
		this.edition = edition;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	public String getUnitCode() {
		return unitCode;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	public Float getQuantity() {
		return quantity;
	}

	public void setCanceledFlag(String canceledFlag) {
		this.canceledFlag = canceledFlag;
	}

	public String getCanceledFlag() {
		return canceledFlag;
	}

	public void setClosedCode(String closedCode) {
		this.closedCode = closedCode;
	}

	public String getClosedCode() {
		return closedCode;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	public Date getClosedDate() {
		return closedDate;
	}

	public void setClosedFlag(String closedFlag) {
		this.closedFlag = closedFlag;
	}

	public String getClosedFlag() {
		return closedFlag;
	}

	public void setClosedBy(String closedBy) {
		this.closedBy = closedBy;
	}

	public String getClosedBy() {
		return closedBy;
	}

	public void setClosedReason(String closedReason) {
		this.closedReason = closedReason;
	}

	public String getClosedReason() {
		return closedReason;
	}

	public void setEnableFlag(String enableFlag) {
		this.enableFlag = enableFlag;
	}

	public String getEnableFlag() {
		return enableFlag;
	}

	public void setLineStatus(String lineStatus) {
		this.lineStatus = lineStatus;
	}

	public String getLineStatus() {
		return lineStatus;
	}

	public void setLineAgentDesc(String lineAgentDesc) {
		this.lineAgentDesc = lineAgentDesc;
	}

	public String getLineAgentDesc() {
		return lineAgentDesc;
	}

	public void setLineSupplierDesc(String lineSupplierDesc) {
		this.lineSupplierDesc = lineSupplierDesc;
	}

	public String getLineSupplierDesc() {
		return lineSupplierDesc;
	}

	public void setSourceId(Float sourceId) {
		this.sourceId = sourceId;
	}

	public Float getSourceId() {
		return sourceId;
	}

	public void setSourceHeaderId(Float sourceHeaderId) {
		this.sourceHeaderId = sourceHeaderId;
	}

	public Float getSourceHeaderId() {
		return sourceHeaderId;
	}

	public void setSourceReference(String sourceReference) {
		this.sourceReference = sourceReference;
	}

	public String getSourceReference() {
		return sourceReference;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	public String getSourceCode() {
		return sourceCode;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	public String getDescriptions() {
		return descriptions;
	}

	public void setCid(Float cid) {
		this.cid = cid;
	}

	public Float getCid() {
		return cid;
	}

	public String getShipmentNum() {
		return shipmentNum;
	}

	public void setShipmentNum(String shipmentNum) {
		this.shipmentNum = shipmentNum;
	}

	public String getItemCode() {
		return itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Float getItemEdition() {
		return itemEdition;
	}

	public void setItemEdition(Float itemEdition) {
		this.itemEdition = itemEdition;
	}

	public Date getNeedByDate() {
		return needByDate;
	}

	public void setNeedByDate(Date needByDate) {
		this.needByDate = needByDate;
	}

	public Float getAllowance() {
		return allowance;
	}

	public void setAllowance(Float allowance) {
		this.allowance = allowance;
	}

	public String getLineLocationDesc() {
		return lineLocationDesc;
	}

	public void setLineLocationDesc(String lineLocationDesc) {
		this.lineLocationDesc = lineLocationDesc;
	}

	public String getLineLocationSupplierDesc() {
		return lineLocationSupplierDesc;
	}

	public void setLineLocationSupplierDesc(String lineLocationSupplierDesc) {
		this.lineLocationSupplierDesc = lineLocationSupplierDesc;
	}

	public Float getLineLocationId() {
		return lineLocationId;
	}

	public void setLineLocationId(Float lineLocationId) {
		this.lineLocationId = lineLocationId;
	}

}
